neo4j/neo4j-browser

app/scripts/init/commandInterpreters.coffee
Experimental support. We need better handling of malformed css before recommending this.
=> style accepts raw grass or load via URL

app/scripts/settings.coffee
if possible, this should be folded into 3.0.2
=> disable onboarding

app/scripts/services/CurrentUser.coffee, app/scripts/services/NTN.coffee
Also removes unused code for firebase auto login
=>  Remove unused auth0 call for refreshing token

app/scripts/services/CypherTransactionBolt.coffee, app/scripts/services/CypherTransactionREST.coffee, app/scripts/services/GraphExplorer.coffee
Send params and direct the relationship match.
=> Tweak 'auto-complete' query

app/scripts/services/GraphExplorer.coffee
Bolt expects custom integers and does not pack js ints correctly
=> Do not parse node id parmater to string if it is a bolt id.

app/content/guides/northwind-graph.jade
The tutorial has a missing space between "they" and "relate".
=> Just added a space typo

app/scripts/services/Bolt.coffee, test/spec/services/UDC.coffee
Don't merge until we bump driver version
=> Remove references to bolt drivers' depecated  value

app/scripts/services/Bolt.coffee, test/spec/services/UDC.coffee
Reverts neo4j/neo4j-browser#211
The driver is not released yet.
=> Revert "Remove references to bolt drivers' depecated  value"

app/content/guides/movie-graph.jade, app/content/guides/movies.jade
Updating to match current name
https://en.wikipedia.org/wiki/The_Wachowskis#Lilly.27s_gender_transition
=> Andy Wachowski updated to Lilly Wachowski

app/index.jade, app/scripts/controllers/Main.coffee
From being `Neo4j` to being `Neo4j  - user@host:port`.
Fixes #142
=> Make better use of the titlebar

app/styles/themes/dark.styl
=> improves text color in dark theme

app/scripts/directives/playTopic.coffee, test/spec/directives/playTopic.coffee
=> Don't touch url:s on play-topics for remote guides

app/content/guides/query-template.jade, app/styles/themes/dark.styl
Includes: 
- `:play` frames
- `:sysinfo`
- graph results frame
- fullscreen frames
=> Updated dark theme styling

app/styles/inspector.styl, app/styles/themes/outline.styl
Added dark outline to nodes in visualization and labels in inspector
=> Updated outline theme

app/scripts/services/CypherTransactionREST.coffee, app/scripts/services/Server.coffee
Transaction method in Server.coffee now only calls through to post as other methods now have different signatures
=> Change rollback method in CypherTransactionRest to use delete directly instead of transaction in Server.

app/index.jade, app/scripts/controllers/DatabaseDrawer.coffee, app/views/partials/drawer-database.jade
=> Limit the number of meta items shown in database sidebar drawer

app/scripts/services/Server.coffee, app/scripts/services/UtilityREST.coffee
Transactions were left open when using REST + :queries frame
=> Ensure transactions are completed when using the REST api

app/styles/stream.styl
Fix for https://github.com/neo4j/neo4j-browser/issues/319
=> Fix issue where frame captions were hidden

app/scripts/polyfill.coffee
Fixes issue where roles are not displayed in `:server user add` and `:server user list` in IE
=> Polyfill String.prototype.includes for IE

src/browser/modules/Stream/Auth/ConnectForm.jsx, src/browser/modules/Stream/Auth/ConnectionForm.jsx
Replaces connect button with the text 'Connecting...'.
Goes back to button if connection fails.
=> Give users feedback when trying to connect and it's slow

package.json, yarn.lock
Not seing any changelogs, but all tests pass (manual tests as well).
=> Upgrade redux-observable

package.json, src/browser/modules/NevadaVisualization/NevadaWrapper.jsx, src/browser/modules/Stream/Visualization.jsx, src/shared/modules/visualization/visualizationDuck.js, yarn.lock
Not 100% necessary to merge, but pushing to get a build for user testing
=> Update to Nevada 0.0.176, added integration for saving style data

src/browser/index.jsx
Re-enables hot module replacement when in dev mode.
=> Enable HMR

src/browser/modules/DatabaseInfo/DatabaseInfo.jsx
Don't just populate the editor
=> Execute meta queries on item click

src/browser/modules/Stream/Auth/ConnectedView.jsx, src/browser/modules/Stream/Auth/ConnectionFrame.jsx, src/browser/modules/Stream/Auth/DisconnectFrame.jsx, src/browser/modules/Stream/Auth/styled.jsx
Updated to be similar to what we have in 2.0
=> Update UI and text for :server connect/disconnect frame

src/browser/modules/Guides/html/movie-graph.html
=> Fixed movie graph guide query for finding co-co-actors who haven't worked with Tom Hanks

src/browser/modules/Editor/Editor.jsx
=> Update line number in editor to return '$' when there is only one line

src/browser/modules/Stream/SchemaFrame.jsx, src/browser/modules/Stream/styled.jsx
Style schema frame as a preformatted area
=> Style schema frame

src/browser/modules/D3Visualization/components/Explorer.jsx, src/shared/services/bolt/boltMappings.js
This ensures we don't over-limit nodes and that  all rels have start and end nodes in graph
=> Dedupe and then limit nodes and reapply relationship filter

package.json, src/browser/modules/App/App.jsx, src/browser/modules/D3Visualization/components/Explorer.jsx, src/browser/modules/Main/Main.jsx, src/shared/modules/commands/commandsDuck.js, src/shared/modules/commands/helpers/grass.js, src/shared/modules/commands/helpers/grass.test.js, src/shared/modules/commands/helpers/http.js, src/shared/services/commandInterpreterHelper.js
This is the same stuff my last PR minus Nevada related code
=> Add :style command missing popup that shows current style

src/browser/modules/D3Visualization/components/Explorer.jsx, src/browser/modules/D3Visualization/components/Inspector.jsx, src/browser/modules/D3Visualization/components/RowExpandToggle.jsx, src/browser/modules/D3Visualization/components/styled.jsx
This PR resolves three issues
- Failing to show 2nd line of inspector when expanded
- Expand button disappearing although inspector grows
- Zoom buttons missing
=> Toggle expand bug, expand button & zoom buttons disappear bugs resolved

src/browser/components/icons/Icons.jsx, src/browser/components/icons/style.css, src/browser/modules/Sidebar/Sidebar.jsx
- If sync is disconnected the Cloud icon is a red disconnected cloud Icon
- If sync connected it is green connected cloud icon when active, and grey cloud  icon when passive.
=> Style cloud icon on sidebar depending on sync connection status

package.json, yarn.lock
=> Updating to a newer version of Nevada

package.json, yarn.lock
Sorry, we were missing the legend updates in the last one
=> Upgrade to 210

src/browser/external/neoPlanner.js, src/browser/modules/Stream/Planner/visualization.css
Fixed alignment in planner
_Old alignment_
_New alignment_
and fixed issue where copy in a planner row was being split across lines.
_Broken copy_
_Fixed copy_
=> Fix issues with query planner

src/browser/modules/Editor/Editor.jsx, src/browser/modules/Editor/cypher/functions.js
Added Cypher built-in functions to editor.
Proof:
=> Cypher Editor - Add built in function to schema

src/browser/components/icons/Icons.jsx, src/browser/modules/Sidebar/Favorite.jsx, src/browser/modules/Sidebar/Favorites.jsx, src/browser/modules/Sidebar/styled.jsx
Added the exec commanf button next to the favorite text ![autoexecfav](https://cloud.githubusercontent.com/assets/849508/25578921/02fbd75c-2e6b-11e7-851d-355235c024dd.gif)
=> Add exec command button to favorites

src/browser/components/buttons/index.jsx
- Extracts out a `<DefaultA />` styled component to be used for other links in the future
=> Fix json download icon color

src/browser/modules/Stream/HelpFrame.jsx
Fallback on `:help help` if user doesn't specify a help topic.
=> Empty :help => :help help

src/browser/components/TabNavigation/Navigation.jsx, src/browser/modules/Editor/Editor.jsx, src/browser/modules/Sidebar/Sidebar.jsx, src/browser/modules/Stream/FrameTitlebar.jsx
Added to 
- frame toolbar
- editor buttons
- sidebar navigation buttons
=> Add 'title' attribute to buttons for mouse over information

src/browser/components/Centered.jsx, src/browser/components/icons/Icons.jsx, src/browser/modules/Stream/CypherFrame.jsx, src/browser/modules/Stream/styled.jsx
Display spinner until a result is returned
=> Show spinner whilst waiting for a cypher result to return

src/shared/services/commandInterpreterHelper.js
Would return error rather than content
=> Fix issue where default whitelist was not being used

src/browser/modules/Stream/CypherFrame.jsx
Error: <img width="784" alt="2017-05-04_at_12 32 25" src="https://cloud.githubusercontent.com/assets/849508/25711657/67671b9c-30e7-11e7-8642-fe69a28ae0cc.png">
Fix:
=> Display error result in cypher frame when disconnected from the server

yarn.lock
Updates all dependencies to their latest version based on the version range specified in the package.json
=> Upgrade dependencies with `yarn upgrade`

package.json, src/browser/modules/NevadaVisualization/NevadaWrapper.jsx, yarn.lock
Upgraded to the latest Nevada and introduced a minor API from the browser's wrapper code to pass on information regarding Full Screen State
=> 3.0 experimental

package.json, yarn.lock
=> Remove unused jquery dependency

src/browser/modules/DatabaseInfo/DatabaseKernelInfo.jsx, src/browser/modules/DatabaseInfo/UserDetails.jsx, src/browser/modules/DatabaseInfo/styled.jsx
- Fetch kernel information from redux
- Add links to useful Browser commands based on user type
=> Update sidebar metadata and links

src/browser/modules/Sidebar/Settings.jsx
Visually simplified to just be a checkbox
=> Add bolt+routing setting in the drawer

src/browser/modules/App/App.jsx, src/browser/modules/DocTitle/index.jsx
Control the document title.
If connected: `username@url - Neo4j Browser`
If not connected: `Neo4j Browser`
=> Update document title with connected username and host

src/browser/modules/Sidebar/FileDrop.jsx
=> Accept *.grass files in the favorites dropzone

src/browser/modules/Stream/CypherFrame.jsx, src/browser/modules/Stream/Views/AsciiView.jsx, src/browser/modules/Stream/styled.jsx
To adjust the max column width of the response table.
Useful when copying the result to paste in into some other medium.
=> Add slider to text view statusbar

package.json, src/browser/modules/Guides/Carousel.jsx, src/browser/modules/Guides/CarouselSlidePicker.jsx, src/browser/modules/Guides/Guides.jsx, src/browser/modules/Guides/style.css, src/browser/modules/Guides/styled.jsx, yarn.lock
From:
To:
Things missing (new vs old):
- animation between slides
=> Replace react-swipe with custom carousel

src/browser/modules/Editor/Editor.jsx
This PR resolves the editor cursor randomly resetting back to start position while editing, which was also reported here https://github.com/neo4j/neo4j-browser/issues/526 
The solution is removing editor value from Editor component state thus leaving codemirror the only source of truth for editor value.
Fixes #526 
changelog: Fix cursor sometimes resetting to start position
=> Resolve editor cursor randomly resetting back to start position bug

src/browser/components/Render.jsx, src/browser/modules/App/App.jsx, src/browser/modules/DatabaseInfo/DatabaseKernelInfo.jsx, src/browser/modules/DatabaseInfo/MetaItems.jsx, src/browser/modules/DatabaseInfo/UserDetails.jsx, src/browser/modules/Guides/Carousel.jsx, src/browser/modules/Main/Main.jsx, src/browser/modules/Main/SyncReminderBanner.jsx, src/browser/modules/Sidebar/Favorites.jsx, src/browser/modules/Sidebar/Folder.jsx, src/browser/modules/Stream/Auth/ChangePasswordFrame.jsx, src/browser/modules/Stream/Auth/ConnectForm.jsx, src/browser/modules/Stream/Auth/ConnectedView.jsx, src/browser/modules/Stream/Auth/ConnectionFrame.jsx, src/browser/modules/Stream/Auth/DisconnectFrame.jsx, src/browser/modules/Stream/Auth/ServerStatusFrame.jsx, src/browser/modules/Stream/CypherFrame.jsx, src/browser/modules/Stream/FrameTemplate.jsx, src/browser/modules/Stream/FrameTitlebar.jsx, src/browser/modules/Stream/ParamFrame.jsx, src/browser/modules/Stream/ParamsFrame.jsx, src/browser/modules/Stream/Queries/QueriesFrame.jsx, src/browser/modules/Stream/SysInfoFrame.jsx, src/browser/modules/Stream/Views/ErrorsView.jsx
It reflects more what it does since it's actually removing / not inserting children to the DOM if false condition.
=> Rename <Visible> => <Render>

package.json, src/browser/components/buttons/index.jsx, src/browser/modules/ClickToCode/__snapshots__/index.test.js.snap, src/browser/modules/D3Visualization/components/styled.jsx, src/browser/modules/Editor/styled.jsx, src/browser/modules/Main/styled.jsx, src/browser/modules/Stream/styled.jsx, yarn.lock
Changes needed to make it work: Add semicolons where appropriate.
=> Upgrade styled-components to v2

src/browser/modules/Help/html/commands.html
=> Add links to help frames for :GET and :POST on commands frame

src/shared/modules/udc/udcDuck.js, src/shared/modules/udc/udcDuck.test.js
Also, fix a bug so events are working correctly now.
Fixes #590
=> Fix app break when no events in UDC state

package.json, yarn.lock
All _seems_ to be working fine.
It's nice to keep up to date with minor version bumps.
=> Result from `yarn --upgrade` plus added stylis for s-c

src/browser/modules/User/UserAdd.jsx, src/browser/modules/User/UserInformation.jsx, src/browser/modules/User/UserList.jsx, src/browser/modules/User/styled.jsx, src/shared/modules/features/featuresDuck.js, src/shared/modules/features/featuresDuck.test.js
- Fix issues around status messages in user add frame
- Update styling for user add and user list frames
_from this:_
_to this:_
=> Update `:server user add|list` frames

src/shared/modules/connections/connectionsDuck.js, src/shared/modules/connections/connectionsDuck.test.js
Unfortunately I hade to split the tests in different 'describe' blocks due to bugs in redux-mock-store.
=> Check if connection.host is set before attempt to connect

src/shared/modules/commands/commandsDuck.js, src/shared/modules/connections/connectionsDuck.js, src/shared/modules/currentUser/currentUserDuck.js, src/shared/modules/dbMeta/__snapshots__/dbMetaDuck.test.js.snap, src/shared/modules/dbMeta/dbMetaDuck.js, src/shared/modules/dbMeta/dbMetaDuck.test.js, src/shared/modules/discovery/discoveryDuck.js, src/shared/modules/features/featuresDuck.js, src/shared/modules/grass/grassDuck.js, src/shared/modules/grass/grassDuck.test.js, src/shared/modules/params/paramsDuck.js, src/shared/modules/requests/requestsDuck.js, src/shared/modules/settings/settingsDuck.js, src/shared/modules/stream/streamDuck.js, src/shared/modules/sync/syncDuck.js
- Stops {hydrated:true} appearing in ':params'
=> Update ducks so 'hydrated' is not stored as part of redux state

e2e_tests/integration/index.spec.js
- added a longer retry period for asserting on frame titlebar content
=> Reduce flakiness in e2e test

src/browser/modules/Stream/CypherFrame/TableView.jsx, src/browser/modules/Stream/CypherFrame/TableView.test.js, src/browser/modules/Stream/CypherFrame/__snapshots__/TableView.test.js.snap
Do a proper null-check + display null as null and stop converting `null` -> `(empty)`.
=> Fix null not rendering in table view results

src/shared/modules/settings/__snapshots__/settingsDuck.test.js.snap, src/shared/modules/settings/settingsDuck.js
=> Disable web workers by default

e2e_tests/integration/index.spec.js, src/browser/components/TabNavigation/Navigation.jsx
Simple test to assert the meta item count in the db info drawer
=> Add test to assert that meta items are added to the sidebar

src/shared/services/bolt/boltMappings.js, src/shared/services/bolt/boltMappings.test.js
=> Map Signature argument to display in a query plan

src/browser/modules/Help/html/param.html
=> Fix typo in :help param

src/browser/modules/D3Visualization/mapper.js
Fixes issue where booleans would not be displayed.
Fixes https://github.com/neo4j/neo4j-browser/issues/640
=> In the visualization convert all property values to strings

src/browser/modules/Stream/CypherFrame/helpers.test.js, src/shared/services/utils.js
Fixes https://github.com/neo4j/neo4j/issues/10034
=> Don't remap escape sequences in cypher value output

src/shared/modules/settings/__snapshots__/settingsDuck.test.js.snap, src/shared/modules/settings/settingsDuck.js
Can be opted out by `:config useCypherThread: false`
=> Enable thread to execute cypher on (web worker)

src/browser/modules/Guides/html/movie-graph.html
Fix typo "haven't work with Tom Hanks..." -> "haven't worked with Tom Hanks..."
=> Fix typo "haven't work with Tom Hanks"

package.json, yarn.lock
I've found no issues using the new version
=> Use latest released neo4j-driver

src/browser/init.js
Should have a positive effect on performance
=> Only load devtools if not in prod env

package.json, yarn.lock
preact, styled-compoennts, rxjs etc
=> Upgrade both runtime + builds deps

src/shared/modules/dbMeta/dbMetaDuck.js, src/shared/modules/jmx/jmxDuck.js
Use `.do` rather than `.mergeMap` since no primise is returned.
Also, don't append jmx values, that'll explode browser.
=> Db meta fix

e2e_tests/integration/index.spec.js, src/browser/modules/Editor/Editor.jsx, src/browser/modules/Sidebar/Favorite.jsx, src/browser/modules/Sync/BrowserSync.jsx, src/browser/modules/Sync/BrowserSyncInit.jsx, src/shared/modules/sync/syncDuck.js, src/shared/services/browserSyncService.js
_Adds e2e test to cover this fix_
=> Fix for clearing local data when not signed in to browser sync

src/browser/modules/Sidebar/About.jsx
=> Add neo4j server version and edition to 'About' drawer

src/browser/components/Tables.jsx, src/browser/modules/Stream/SysInfoFrame/index.jsx
`UsageValue` added to `:sysinfo`
=> Display page cache UsageRatio in :sysinfo is available

cypress/plugins/index.js, e2e_tests/integration/help-topics.spec.js, e2e_tests/integration/index.spec.js, e2e_tests/integration/params.spec.js, e2e_tests/integration/topics.spec.js, package.json, src/browser/modules/Help/html/commands.html, src/browser/modules/Help/html/index.js, src/browser/modules/Help/html/style.html, src/shared/modules/commands/helpers/params.js, src/shared/modules/commands/helpers/params.test.js, yarn.lock
This PR also includes a start on e2e tests for help commands.
=> Add :help style

e2e_tests/integration/index.spec.js, e2e_tests/integration/types.spec.js, src/browser/modules/D3Visualization/components/Inspector.jsx, src/browser/modules/Stream/SysInfoFrame/sysinfo.test.js, src/shared/services/bolt/boltMappings.js, src/shared/services/bolt/boltMappings.test.js
=> Render new types correctly in viz

e2e_tests/integration/plan.spec.js, src/browser/external/neoPlanner.js, src/browser/modules/Stream/CypherFrame/PlanView.jsx
Info for `LIMIT` and more are now shown.
Before:
After:
Moar!
=> Show more information on operators in plan output

src/browser/modules/Guides/html/northwind-graph.html
I noticed a missing space while going through the Northwind graph guide.
=> Adds a space that was missing in the Northwind graph guide

src/browser/modules/Stream/styled.jsx
Fixes https://github.com/neo4j/neo4j-browser/issues/681
=> Dark theme - update frame message color to be more readable

src/shared/modules/udc/udcDuck.js, src/shared/modules/udc/udcDuck.test.js
=> Limit the number of udc events being stored in state

src/browser/components/Directives.jsx
Example guide with multiple`[value-key]` tagged elements:
=> In guides allow one dynamic field to update multiple elements

README.md, e2e_tests/files/import.csv, e2e_tests/integration/index.spec.js, e2e_tests/integration/loadcsv.spec.js, e2e_tests/integration/params.spec.js, e2e_tests/integration/plan.spec.js, e2e_tests/integration/types.spec.js, e2e_tests/support/defaults.js
=> Add “LOAD CSV” e2e tests

src/browser/modules/ClickToCode/index.jsx, src/browser/modules/Help/html/param.html, src/browser/modules/Help/html/params.html, src/browser/modules/Stream/ParamsFrame.jsx
Also promote `:help param` when setting or displaying params.
=> Update :help param to promote new param format

src/browser/components/Tables.jsx, src/browser/modules/Sidebar/Favorites.jsx, src/browser/modules/Sidebar/Settings.jsx, src/browser/modules/Sidebar/Settings.test.js, src/browser/modules/Sidebar/__snapshots__/Settings.test.js.snap, src/shared/services/utils.js, src/shared/services/utils.test.js
Encode and unescape before base64 encoding.
Added tests for Settings.js and for the utility function toKeyString to demonstrate this.
=> Fix issue with creating unique keys from user input

auth_server/public/getDelegationTokenNewBrowser.html, auth_server/public/indexNewBrowser.html
Bumps auth0 and auth0-lock cdn imports to the latest version.
This pr includes a refactoring to use the new api's for the libs.
_known issues_ : auto login after Browser refresh
=> Update auth0 libs

src/browser/modules/Stream/HistoryFrame.jsx, src/shared/modules/history/historyDuck.js, src/shared/modules/history/historyDuck.test.js, src/shared/services/commandInterpreterHelper.js
Remove previously executed editor statements using `:history clear` command.
=> Add `:history clear` command

src/browser/modules/Sidebar/Folder.jsx, src/browser/modules/Sidebar/__snapshots__/Settings.test.js.snap, src/browser/modules/Sidebar/styled.jsx
Fixes broken styling when folder name is longer than available space
=> Add max width to folder label

package.json, src/browser/modules/D3Visualization/components/Explorer.jsx, yarn.lock
Fixes:
- having visualisations with no styling
- grass related errors being thrown
=> Rebase users' grass against default grass

src/browser/modules/Help/html/style.html
**Hey there,**
Just started playing around with Neo4j yesterday.
The Neo4j Browser is amazing 😍 !
Caught this tiny typo in a help command, and thought I should contribute!
**Have a great day!**
**Ryan**
=> Change "origon" to "origin"

e2e_tests/integration/bolt.spec.js, e2e_tests/support/commands.js, src/browser/modules/User/RolesSelector.jsx, src/browser/modules/User/UserInformation.jsx, src/browser/modules/User/UserList.jsx, src/shared/services/bolt/boltConnection.js
- Only invalidate certain connection errors
- Service unavailable
- Auth errors
- Password change required
- Add tests
- Make the UI for adding users and groups more clear
=> Enable users with non reader roles to connect

src/shared/modules/currentUser/currentUserDuck.js
So... The browser does not work properly when auth is off.
After this PR it is.
Before:
After:
=> Fix neo4j-browser not working properly when db auth is disabled

e2e_tests/integration/data-export.spec.js, src/browser/modules/Stream/CypherFrame/index.jsx, src/browser/modules/Stream/FrameTitlebar.jsx
The `hasVis` state must be checked in scu.
Added test for it to prevent regressions.
=> Initial image export fix

src/shared/modules/connections/connectionsDuck.js
Because it triggers the retry limit for the user.
The password have probably changed from a different client.
Only retry on connection loss for other reasons: server not reachable etc.
Check error code and bypass the retry mechanism.
Requests on server not available:
Requests on auth failure:
=> Don’t try to reconnect on lost connection because of auth failure

src/shared/modules/commands/helpers/params.js, src/shared/modules/commands/helpers/params.test.js
Bug in the regexp.
fixes: https://github.com/neo4j/neo4j-browser/issues/645
=> Fix nested :params bug

src/browser/modules/Sidebar/Documents.jsx, src/browser/modules/Sidebar/docsUtils.test.js
changelog: Update links to documentation in the sidebar
=> Split what goes in the docs sidebar on Neo4j version

src/shared/modules/features/featuresDuck.js, src/shared/modules/features/featuresDuck.test.js
=> Fix semver compare bug for non semver server versions

src/browser/modules/D3Visualization/graphStyle.js, src/browser/modules/D3Visualization/graphStyle.test.js, src/browser/modules/Stream/CypherFrame/__snapshots__/VisualizationView.test.js.snap
Use same default palette as Neo4j Bloom.
=> Replace and add more viz styling colors

src/browser/modules/Guides/html/movie-graph.html
Update the incorrect tagline on 'When Harry met Sally'.
=> Update movie-graph cypher statement

babel.config.js, e2e_tests/support/defaults.js, jest.config.js, package.json, src/browser/AppInit.jsx, src/browser/modules/DatabaseInfo/__snapshots__/MetaItems.test.js.snap, src/browser/modules/Stream/CypherFrame/__snapshots__/ErrorsView.test.js.snap, src/browser/modules/Stream/CypherFrame/__snapshots__/PlanView.test.js.snap, src/browser/modules/Stream/CypherFrame/__snapshots__/TableView.test.js.snap, src/browser/modules/Stream/CypherFrame/__snapshots__/VisualizationView.test.js.snap, src/browser/modules/Stream/__snapshots__/SchemaFrame.test.js.snap, yarn.lock
=> Upgrade dependencies 

.gitignore, build_scripts/webpack.config.js, jest.config.js, jsconfig.json, package.json, src/browser/hooks/testUtils.js, src/browser/hooks/useAutoTheme.js, src/browser/hooks/useAutoTheme.test.js, src/browser/hooks/useDetectColorScheme.js, src/browser/hooks/useDetectColorScheme.test.js, src/browser/modules/App/App.jsx, src/browser/modules/Sidebar/Settings.jsx, src/browser/styles/themes.js, src/shared/modules/settings/__snapshots__/settingsDuck.test.js.snap, src/shared/modules/settings/settingsDuck.js, yarn.lock
From a Lab day we had.
Only available in Firefox Alphas and Safari Tech Preview at the moment. And in a Neo4j Desktop environment when the corresponding feature is added there.
Done in two ways:
- Through CSS media query listener on `prefers-color-scheme`
- Through injected overrides from Neo4j Desktop
An article about it: https://medium.freecodecamp.org/how-to-detect-a-users-preferred-color-scheme-in-javascript-ec8ee514f1ef
=> Detect users’ preferred color scheme

src/browser/components/buttons/index.jsx, src/browser/modules/User/styled.jsx, src/browser/styles/themes.js
Before:
After:
changelog: Updates to dark theme
=> Update dark input and link colors.

src/browser/AppInit.jsx, src/shared/modules/app/appDuck.js, src/shared/modules/features/featuresDuck.js, src/shared/modules/settings/settingsDuck.js, src/shared/services/utils.js, src/shared/services/utils.test.js
Also opt out of showing browser-sync sidebar in an additional operating environment.
=> Detect operating enviromentments more generically

e2e_tests/integration/plan.spec.js, package.json, src/shared/services/bolt/boltConnection.js, yarn.lock
Update to neo4j-driver@@2.0.0-alpha03
https://github.com/neo4j/neo4j-javascript-driver/wiki/2.0-changelog#200-alpha03
=> Update neo4j driver

src/shared/modules/dbMeta/dbMetaDuck.js
Fixes an issue where the server version wouldn't show up when connected to the system db, making browser unaware of multi-db capabilities.
=> Make sure that server version is available.

src/shared/modules/commands/useDb.test.js, src/shared/services/commandInterpreterHelper.js
This is expected to fail the e2e test since they run against Neo4j 3.5.
=> Make `:use <db-name>` case insensitive

src/shared/modules/app/appDuck.js, src/shared/modules/discovery/discoveryDuck.js, src/shared/modules/discovery/discoveryDuck.test.js, src/shared/services/bolt/boltHelpers.js
Not just when in regular web env.
=> Request discovery endpoint in cloud env

e2e_tests/integration/bolt.spec.js, e2e_tests/integration/multi-db.spec.js, e2e_tests/integration/plan.spec.js, src/browser/modules/Editor/Codemirror.jsx, src/browser/modules/Stream/Auth/DbsFrame.jsx, src/shared/services/utils.test.js
These will not work until other PR:s have gone in: #990 #991
=> Fix + add e2e tests on canary/4.0

src/shared/modules/connections/connectionsDuck.js, src/shared/modules/connections/connectionsDuck.test.js
To clear the editor gutter when disconnected
=> Clear useDb on disconnect

src/browser/modules/DBMSInfo/UserDetails.jsx, src/browser/modules/User/UserAdd.jsx, src/browser/modules/User/UserList.jsx, src/shared/modules/dbMeta/dbMeta.utils.js
Don’t show content on frames that can’t be used (see screenshot).
And make the dbms sidebar not crash when opened.
=> Fix errors in community edition

README.md, e2e_tests/integration/0.index.spec.js, e2e_tests/integration/bolt.spec.js, e2e_tests/integration/data-export.spec.js, e2e_tests/integration/loadcsv.spec.js, e2e_tests/integration/multi-db.spec.js, e2e_tests/integration/multistatements.spec.js, e2e_tests/integration/params.spec.js, e2e_tests/integration/plan.spec.js, e2e_tests/integration/style.spec.js, e2e_tests/integration/topics.spec.js, e2e_tests/integration/types.spec.js, e2e_tests/integration/viz.zpec.js, e2e_tests/support/commands.js, src/browser/documentation/help/param.jsx, src/browser/documentation/help/params.jsx, src/browser/documentation/help/partials/params-on-systemdb.jsx, src/shared/modules/commands/helpers/params.js, src/shared/services/commandInterpreterHelper.js
Show client side error message when trying to set parameters when using system database.
Links to `:help params` and `:help param` which both has more info on this..
Added E2E test for it.
=> Error message when declaring params on system db

package.json, yarn.lock
=> patch bump neo4j-driver

package.json, yarn.lock
- Bump cypher-codemirror version
=> Cypher codemirror bump

.eslintrc.json, src/browser/modules/App/App.test.js, src/browser/modules/Sidebar/Sidebar.jsx
Shut off `react/no-unescaped-entities` and do some refactoring to shut off `react/display-name`.
=> Put out lint warnings

src/browser/modules/Sidebar/About.jsx, src/browser/modules/Sidebar/Documents.jsx
=> Add sidebar links to browser release, changelog, and developer pages

e2e_tests/integration/play-command.spec.js, src/browser/modules/Carousel/Carousel.jsx, src/browser/modules/Docs/Docs.jsx, src/browser/modules/Stream/PlayFrame.jsx, src/shared/services/commandInterpreterHelper.js, src/shared/services/commandUtils.js
- Fix bug in re-run guides
- Fix specific slide linking regressions
- `:play concepts#slide-3` and `:play http://guides.neo4j.com/reco/index.html#slide-2` now works.
=> Fix release blockers

package.json, yarn.lock
bumps other deps minor + patch versions
=> Upgrade neo4j-driver to 4.1.0

src/browser/components/Form.jsx, src/browser/modules/Sidebar/Settings.jsx, src/browser/modules/Sidebar/__snapshots__/Settings.test.js.snap, src/browser/modules/Sidebar/styled.jsx
While doing the walk through with Liza I noticed some labels were not clickable. I connected the labels to the inputs and made some smaller readability changes
=> Connect labels to form inputs

LICENSES.txt, NOTICE.txt, e2e_tests/integration/user.spec.js, package.json, src/browser/modules/App/styled.jsx, src/browser/modules/DBMSInfo/MetaItems.jsx, src/browser/modules/Editor/Codemirror.jsx, src/browser/modules/Editor/styled.jsx, src/browser/modules/Main/Main.jsx, src/browser/modules/Main/SyncConsentBanner.jsx, src/browser/modules/Main/styled.jsx, src/browser/modules/Stream/Auth/ChangePasswordForm.jsx, src/browser/modules/Stream/Auth/revealable-password-input.jsx, src/browser/modules/Stream/styled.jsx, yarn.lock
* Removed the classname dependency:
[Here's a gif to show the focus class is still applied like before](http://g.recordit.co/XIr0foLfRe.gif)
* Fixed some misalignment on the pop-up banner. It used to look like [this](http://g.recordit.co/mpbCgJ2euC.gif), now it looks like [this](http://g.recordit.co/O9G7MdpXQp.gif). 
I'm out of ideas on how to make this look better. The popup now instead misaligns when the scrollbar is present instead. 
Edit: This is the current best idea i have. It does make the banner scroll as well.
* The password is now generated for both fields, and is show by default. You'll need to show it to know your password anyway. [Like this](http://g.recordit.co/CjvGvJ6OKr.gif)
Also, I think it would be clearer if the generate button instead said "suggest password", thoughts?
=> Generate both fields

src/browser/modules/Frame/FrameTitlebar.jsx
See video:
http://g.recordit.co/GrLs7ktguc.gif
=> Cypher frames would not unpin

src/browser/modules/D3Visualization/lib/visualization/renders/init.js, src/browser/modules/Stream/CypherFrame/__snapshots__/VisualizationView.test.js.snap
=> Fix text position in GraphComponent for rtl languages

e2e_tests/integration/editor.spec.js, e2e_tests/integration/multistatements.spec.js, e2e_tests/support/commands.js, src/browser/modules/Editor/Editor.jsx, src/browser/modules/Frame/styled.jsx
Also prevent empty commands from running.
=> Full screen is always in multiline

e2e_tests/integration/0.index.spec.js, e2e_tests/integration/debug-command.spec.js, e2e_tests/integration/multi-db.spec.js, e2e_tests/support/commands.js, src/browser/components/buttons/index.jsx, src/browser/modules/Editor/Editor.jsx, src/browser/modules/Editor/EditorFrame.tsx, src/browser/modules/Editor/styled.tsx
Makes the update favorite icon look more clickable.
Show a shortcut on run.
Naming update on the discard icon.
Animation changes is to prevent static height and elements jumping
=> Update animation and minor ui details

cypress.json, e2e_tests/integration/multistatements.spec.js, e2e_tests/support/commands.js, src/browser/modules/Stream/CypherScriptFrame/CypherScriptFrame.jsx
neo4j can take more than 10 seconds to set initial password on slower build agents
=> increase wait for neo4j change password

.eslintrc.json, src/browser/modules/Editor/Editor.jsx, src/browser/modules/Editor/EditorFrame.tsx, src/browser/modules/Editor/styled.tsx
Move to position absolute solution for the double editor problem, and make animation smaller
=> Fix flaky animation

src/browser/documentation/templates/DynamicTopics.jsx, src/browser/modules/D3Visualization/components/RowExpandToggle.jsx, src/browser/styles/neo4j-world.css, src/browser/styles/streamline.css, src/shared/services/export-favorites/export-favorites.utils.js, src/shared/services/utils.js
=> Fix smells/bugs reported by sonarcube

src/browser/modules/Editor/Editor.jsx
Pasting a large query before:
Pasting a large query now:
=> Make sure editor grows as needed

src/browser/modules/Editor/EditorFrame.tsx
Currently you can't stop editing a saved script without a refresh.
=> Clear resets favorite

src/browser/modules/Frame/styled.jsx
=> Prevent overflow in :play

src/browser/modules/Stream/PlayFrame.jsx
=> Alias :play to :play start

src/browser/modules/Stream/CypherScriptFrame/Summary.jsx, src/browser/modules/Stream/PlayFrame.jsx, src/shared/modules/commands/commandsDuck.js, src/shared/modules/commands/helpers/config.js, src/shared/modules/commands/helpers/config.test.js, src/shared/modules/commands/helpers/grass.js, src/shared/modules/commands/helpers/grass.test.js, src/shared/modules/commands/helpers/play.js, src/shared/modules/commands/remoteGuides.test.js, src/shared/modules/dbMeta/__snapshots__/dbMetaDuck.test.js.snap, src/shared/modules/dbMeta/dbMetaDuck.js, src/shared/rootEpic.js, src/shared/services/commandInterpreterHelper.js, src/shared/services/utils.js, src/shared/services/utils.test.js
=> Add support for browser.remote_content_hostname_allowlist

src/browser/modules/Editor/EditorFrame.tsx, src/browser/modules/Sidebar/ProjectsFilesScripts.tsx
=> Clear editor on deleting script

src/browser/modules/Editor/EditorFrame.tsx, src/browser/modules/Sidebar/ProjectsFilesScripts.tsx, src/browser/modules/Sidebar/Sidebar.tsx, src/browser/modules/Sidebar/static-scripts.js, src/shared/modules/editor/editorDuck.js, src/shared/modules/favorites/favoritesDuck.js
Add static scripts back in the favorite drawer
=> Re-add static scripts

src/browser/modules/App/keyboardShortcuts.ts, src/browser/modules/Editor/EditorFrame.tsx, src/browser/modules/Editor/ProjectFilesButton.tsx, src/browser/modules/Sidebar/NewSavedScript.tsx, src/browser/modules/Sidebar/ProjectsFilesScripts.tsx, src/browser/modules/Sidebar/project-files.constants.ts, src/browser/modules/Sidebar/project-files.utils.ts
- Add in a very basic util for file path creation for Project Files (with OS path consideration)
=> file path util added

src/browser/modules/Stream/Auth/ConnectionForm.jsx, src/browser/modules/Stream/Auth/ConnectionForm.test.js
When completing the connection form i makes sense to move focus to the main editor.
=> Focus editor when connected through form

.github/workflows/pr-builder.yml
Before merging this action needs SURGE_LOGIN and SURGE_TOKEN set in github secrets.
=> Automatic PR-previews

src/browser/modules/Editor/styled.tsx
Previously fullscreen still was capped at 12-ish lines
=> Fixes fullscreen not being fullscreen

package.json
=> Remove unused jar commands

.eslintrc.json, package.json, src/browser/modules/App/App.jsx, src/browser/modules/App/keyboardShortcuts.ts, src/browser/modules/Editor/EditorFrame.tsx, src/browser/modules/Editor/Monaco.tsx, src/browser/modules/Editor/ProjectFilesButton.tsx, src/browser/modules/Main/Main.jsx, src/browser/modules/Sidebar/ProjectsFilesScripts.tsx, src/browser/modules/Sidebar/Sidebar.tsx, src/shared/modules/features/featuresDuck.js, yarn.lock
- add [eslint-plugin-react-hooks](https://www.npmjs.com/package/eslint-plugin-react-hooks)
- had to change `useBrowserSync` to `utilizeBrowserSync` because of [this](https://github.com/facebook/react/issues/17636)
=> add eslint-plugin-react-hooks

src/browser/modules/DBMSInfo/DBMSInfo.jsx, src/browser/modules/DBMSInfo/MetaItems.jsx
=> Add color to relationships in sidebar

src/browser/components/Directives.jsx, src/browser/components/FileDrop/FileDrop.jsx, src/browser/modules/App/App.jsx, src/browser/modules/ClickToCode/index.jsx, src/browser/modules/DBMSInfo/DBMSInfo.jsx, src/browser/modules/DBMSInfo/DatabaseKernelInfo.jsx, src/browser/modules/DecoratedText/TextCommand.jsx, src/browser/modules/Editor/Editor.jsx, src/browser/modules/Editor/EditorFrame.tsx, src/browser/modules/Frame/FrameTitlebar.jsx, src/browser/modules/Sidebar/ProjectsFilesScripts.tsx, src/browser/modules/Sidebar/favorites.js, src/browser/modules/Sidebar/static-scripts.js, src/browser/modules/Stream/CypherFrame/ErrorsView.jsx, src/browser/modules/Stream/EditFrame.tsx, src/browser/modules/Stream/PlayFrame.jsx, src/browser/modules/Stream/StyleFrame.jsx, src/browser/modules/Stream/auto-exec-button.jsx, src/browser/modules/Stream/auto-exec-button.test.jsx, src/browser/modules/User/UserAdd.jsx, src/browser/modules/User/UserList.jsx, src/shared/modules/commands/commandsDuck.js, src/shared/modules/dbMeta/dbMetaDuck.js, src/shared/modules/editor/editorDuck.js, src/shared/modules/editor/editorDuck.test.js, src/shared/modules/udc/udcDuck.js, src/shared/modules/udc/udcEpics.test.js, src/shared/rootEpic.js
Adds better usage stats. Keeps track of where commands are run from (but not what commands). Most common non-sensitive settings etc.
=> Improve user statistics

src/browser/documentation/help/param.tsx
We we're asked to add this example in the param docs
=> Add params docs example

src/shared/modules/udc/udcDuck.ts
Now keeps track of words, lines and statement count in cypher queries.
=> Add more detail in cypher stats

src/browser/modules/DBMSInfo/UserDetails.tsx
Add `:server disconnect` to the sidebar.
=> Add `:server disconnect` link to the sidebar

LICENSES.txt, NOTICE.txt, e2e_tests/integration/saved-scripts.spec.ts, package.json, src/browser/components/SavedScripts/SavedScripts.tsx, src/browser/components/SavedScripts/icons.tsx, src/browser/components/SavedScripts/index.ts, src/browser/components/SavedScripts/saved-scripts-edit-button.tsx, src/browser/components/SavedScripts/saved-scripts-exec-button.tsx, src/browser/components/SavedScripts/saved-scripts-export-button.tsx, src/browser/components/SavedScripts/saved-scripts-folder.tsx, src/browser/components/SavedScripts/saved-scripts-list-item.tsx, src/browser/components/SavedScripts/saved-scripts-new-folder-button.tsx, src/browser/components/SavedScripts/saved-scripts-remove-button.tsx, src/browser/components/SavedScripts/saved-scripts.constants.ts, src/browser/components/SavedScripts/saved-scripts.hooks.ts, src/browser/components/SavedScripts/saved-scripts.styled.ts, src/browser/components/SavedScripts/saved-scripts.tsx, src/browser/components/SavedScripts/saved-scripts.utils.test.ts, src/browser/components/SavedScripts/saved-scripts.utils.ts, src/browser/components/SavedScripts/types.ts, src/browser/modules/Editor/EditorFrame.tsx, src/browser/modules/Sidebar/NewSavedScript.tsx, src/browser/modules/Sidebar/ProjectsFilesScripts.tsx, src/browser/modules/Sidebar/favorites.ts, src/browser/modules/Sidebar/favorites.utils.ts, src/browser/modules/Sidebar/static-scripts.ts, src/shared/services/export-favorites/export-favorites.utils.ts, yarn.lock
Continuation of, merge that PR first #1262. To confirm behaviour stays the same as I refactor.
=> Add e2e tests for favorites

e2e_tests/integration/connect-form.spec.ts
=> Don't run bolt dependent tests in aura

src/browser/documentation/guides/start.tsx, src/browser/modules/Sidebar/About.tsx
Preview: http://automatic_copyright.surge.sh
Affects about section in the side bar and :play start
=> Set copyright year automatically

src/browser/AppInit.tsx, src/browser/components/SavedScripts/SavedScripts.tsx, src/browser/modules/Sidebar/favorites.ts, src/browser/modules/Sidebar/static-scripts.test.tsx, src/shared/modules/favorites/favoritesDuck.ts
Without these changes you can't move a favorite outside of it folder. Preview: http://drag_from_folder.surge.sh
=> Allow dropping outside folder

src/browser/AppInit.tsx, src/shared/modules/udc/udcDuck.ts, src/shared/services/commandInterpreterHelper.ts
Changes:
- Send fewer performance transactions (was eating up our quota)
- Set a better default transaction name
- Move command type to metadata rather than label in mixpanel (request from anurag)
=> Metadata updates

src/browser/modules/Stream/Auth/ConnectForm.tsx
=> Update hovertext to clarify when to use each protocol

src/browser/components/ClickableUrls.tsx
Closes #1267, reproduction steps available there also.
Preview at: http://prevent_hover_crash.surge.sh
=> Prevent crash on null property values

e2e_tests/integration/0.index.spec.ts, e2e_tests/integration/commands.spec.ts, src/browser/modules/Frame/FrameTitlebar.tsx, src/browser/modules/Frame/styled.tsx, src/browser/modules/Stream/CypherFrame/index.test.tsx, src/browser/modules/Stream/EditFrame.test.tsx, src/browser/modules/Stream/styled.tsx, src/shared/modules/experimentalFeatures/experimentalFeaturesDuck.ts
This is an improvement on https://github.com/neo4j/neo4j-browser/pull/1285.
See http://better_auto_show.surge.sh
=> Improve auto showing

src/shared/modules/editor/editorDuck.ts
Demo: http://autoclose-single-quotes.surge.sh/
=> autoclose single quotes in cypher editor

e2e_tests/integration/connect-form.spec.ts, src/browser/modules/Stream/CypherFrame/AsciiView.tsx, src/browser/modules/Stream/CypherFrame/__snapshots__/AsciiView.test.tsx.snap, src/browser/modules/Stream/CypherFrame/__snapshots__/CodeView.test.tsx.snap, src/browser/modules/Stream/CypherFrame/__snapshots__/ErrorsView.test.tsx.snap, src/browser/modules/Stream/CypherFrame/__snapshots__/VisualizationView.test.tsx.snap, src/browser/modules/Stream/CypherFrame/__snapshots__/relatable-view.test.tsx.snap, src/browser/modules/Stream/__snapshots__/HistoryRow.test.tsx.snap, src/browser/modules/Stream/__snapshots__/SchemaFrame.test.tsx.snap, src/browser/modules/Stream/styled.tsx
Updated Jest snapshots to pass the Jest tests, and disconnected user from browser on cypress Contact form test before running.
=> Fix ligatures text view

src/browser/components/SavedScripts/SavedScriptsListItem.tsx
Remove the need for several clicks to preview a favorite before running it. Favorite: http://normal_selection.surge.sh
=> Populate editor with clicked text like before

docs/modules/ROOT/content-nav.adoc, docs/modules/ROOT/pages/overview.adoc
=> Improved the overview section

docs/preview.yml
Updates the ui bundle version for the docs to the latest: 0.10.5
=> Update ui bundle to 0.10.5

docs/modules/ROOT/pages/about-browser.adoc, docs/modules/ROOT/pages/index.adoc
=> Improved Index and About Neo4j Browser

build_scripts/webpack-plugins.js, jest.config.js, src/browser/modules/App/App.tsx, src/browser/modules/Intercom/index.tsx, src/browser/modules/Segment/index.tsx, src/shared/modules/app/appDuck.ts
=> add segment tracking

docs/modules/ROOT/content-nav.adoc, docs/modules/ROOT/pages/reference-commands.adoc
Appendix that list available commands.
=> Docs appendix commands

docs/antora.yml, docs/modules/ROOT/content-nav.adoc, docs/modules/ROOT/pages/deployment-modes.adoc
Improved deployment modes content.
Dedicated web server documentation.
=> Added content about deployment modes

docs/modules/ROOT/content-nav.adoc, docs/modules/ROOT/pages/operations.adoc
=> Added the credentials handling from the Operations manual

docs/modules/ROOT/pages/operations.adoc
=> Added the missing settings' descriptions

src/browser/AppInit.tsx, src/browser/modules/App/App.tsx, src/browser/modules/Sidebar/Documents.tsx, src/browser/services/canny.ts
=> Respect outgoing connections canny

docs/modules/ROOT/pages/operations.adoc
Added section about browser query component
=> browser query component

docs/modules/ROOT/content-nav.adoc, docs/modules/ROOT/pages/operations.adoc, docs/modules/ROOT/pages/reference-commands.adoc
Added some text about the REST commands.
=> REST commands

src/browser/images/device-icons/browserconfig.xml, src/browser/images/device-icons/manifest.json
Some prefixes got dropped in the branding update. This PR re-adds them. Thanks @jharris4
=> Re-add missing prefixes

docs/modules/ROOT/pages/about-browser.adoc, docs/modules/ROOT/pages/deployment-modes.adoc, docs/modules/ROOT/pages/operations.adoc
Addressed the comments from PR #1360
=> Minor improvements to the Browser manual

src/browser/documentation/sidebar-guides/movie-graph.tsx, src/browser/modules/Carousel/styled.tsx
=> Increases contrast and fixes typo

src/browser/modules/Sidebar/Documents.tsx
=> Add link to new browser docs

docs/antora.yml, docs/preview.yml
=> updated version of docs

docs/modules/ROOT/pages/operations.adoc
=> fixed link to grass file

src/browser/styles/themes.ts, tsconfig.json
=> Fix rgb function used by mistake

e2e_tests/integration/plan.spec.ts
=> fix planner e2e test to handle new 4-3 planner output

e2e_tests/integration/plan.spec.ts
=> tweak query planner e2e test to pass on 4.3

src/shared/modules/dbMeta/dbMeta.utils.ts
http://fix_crash_on_invalid_version.surge.sh/
=> Fix crash on invalid version

src/shared/modules/connections/connectionsDuck.ts, src/shared/modules/dbMeta/dbMetaDuck.ts
also clear history on disconnect from server when settings is false
also improve disconnect handling
=> fix clear history happening too often when setting is false

NOTICE.txt, docs/modules/ROOT/pages/operations.adoc, docs/preview.yml, e2e_tests/integration/plan.spec.ts, e2e_tests/integration/saved-scripts.spec.ts, package.json, src/browser/AppInit.tsx, src/browser/modules/App/App.tsx, src/browser/modules/DBMSInfo/DatabaseSelector.tsx, src/browser/modules/Sync/BrowserSync.tsx, src/shared/modules/connections/connectionsDuck.ts, src/shared/modules/dbMeta/__snapshots__/dbMetaDuck.test.ts.snap, src/shared/modules/dbMeta/dbMeta.utils.ts, src/shared/modules/dbMeta/dbMetaDuck.ts, src/shared/services/localstorage.test.ts, src/shared/services/localstorage.ts, yarn.lock
=> Merge changes from release 4.3.0 to master

src/browser/components/icons/Icons.tsx, src/browser/icons/hierarchy-9.svg
preview at http://result_frame_icon.surge.sh
=> Update icon on Cypher Frames

docs/antora.yml, docs/modules/ROOT/pages/operations.adoc, docs/modules/ROOT/pages/reference-commands.adoc, docs/modules/ROOT/pages/visual-tour.adoc
4.3 now has the guide command.
Also bumped the version.
=> guide command

src/browser/modules/Editor/language/consoleCommands.ts
Preview @ http://autocomplete_guide.surge.sh
=> Add autocomplete for guides

src/browser/documentation/sidebar-guides/concepts.tsx, src/browser/documentation/sidebar-guides/cypher.tsx, src/browser/documentation/sidebar-guides/guideIndex.tsx, src/browser/documentation/sidebar-guides/intro.tsx, src/browser/documentation/sidebar-guides/movie-graph.tsx, src/browser/documentation/sidebar-guides/northwind-graph.tsx, src/browser/documentation/sidebar-guides/unfound.tsx, src/browser/modules/Carousel/Slide.tsx, src/browser/modules/ClickToCode/__snapshots__/index.test.tsx.snap, src/browser/modules/GuideCarousel/Pagination.tsx, src/browser/modules/GuideCarousel/styled.tsx, src/browser/modules/Sidebar/GuidesDrawer.tsx, src/browser/modules/Sidebar/styled.tsx, src/browser/modules/Stream/CypherFrame/__snapshots__/ErrorsView.test.tsx.snap, src/browser/modules/Stream/CypherFrame/__snapshots__/VisualizationView.test.tsx.snap, src/browser/modules/Stream/__snapshots__/SchemaFrame.test.tsx.snap, src/browser/styles/themes.ts
Moves padding that was on the Guide Sidebar into our built in guides. This way we don't get misaligned padding on ascidoc guides. Also changes color of next buttons in pagination.
http://more_guide_polish.surge.sh/
=> More guide polish

docs/modules/ROOT/pages/visual-tour.adoc
=> Added the send to editor and removed the guides that does not support the :guide command 

.github/ISSUE_TEMPLATE.md
=> Update issue template to mention canny.io

package.json
Demo says it all @ http://update_manifest.surge.sh/manifest.json
=> Include browser version in manifest

src/browser/documentation/play-guides/northwind-graph.tsx, src/browser/documentation/sidebar-guides/northwind-graph.tsx
@jexp requested the northwind guide be updated to have more indexes to increase lookup speed. This pr replaces #1434 as per offline discussion with Hunger. 
Preview @ http://guide_indexes.surge.sh
=> Add index on productName for northwind guides

NOTICE.txt, src/browser/modules/Stream/CypherFrame/PlanView.tsx
=> Move memoize call to ensure cache is kept between renders

src/browser/modules/Editor/Monaco.test.tsx, src/browser/modules/Editor/Monaco.tsx, src/browser/modules/Frame/FrameEditor.tsx
This PR aims to refactor our Monaco component to be a class rather than function component and preserve the same functionality. This might seem odd at first glance, but for dealing with a mutable, external library, I've found the class component approach works better, since it allows for handling mutable state.
=> Monaco class comp

src/browser/modules/Stream/SysInfoFrame/helpers.tsx
Preview @ sysinfo_update.surge.sh
=> Add "Database size" metric to sysinfo by request

src/shared/services/bolt/boltWorker.ts
Accidentally sneaked in here -> https://github.com/neo4j/neo4j-browser/pull/1274/files#diff-e72c2ede991a00c772668dd35acf2349cdb1fe3ce11f405d73cb3bd25bf03702R119
=> Remove test message left in by mistake

src/shared/services/commandInterpreterHelper.ts
=> do not allow sysinfo command when using system db

src/shared/modules/auth/common.js, src/shared/modules/auth/index.js, src/shared/modules/auth/settings.js, src/shared/modules/discovery/discoveryDuck.ts
Fix typos and a bug that caused sso_redirect param not to work
=> Fix redirect bug

src/browser/components/SavedScripts/SavedScripts.tsx
Preview @ https://unbreak_export.surge.sh
=> Unbreak export of favorites

docs/modules/ROOT/content-nav.adoc, docs/modules/ROOT/pages/browser-sso.adoc
=> added sso content and updated content-nav

LICENSES.txt, NOTICE.txt, package.json, yarn.lock
=> Bump driver to 4.3.3

docs/modules/ROOT/pages/browser-sso.adoc
=> fixed some rendering bugs

docs/modules/ROOT/pages/index.adoc
Improved the front page so it is inline with other manual.
=> improved the front page

src/shared/modules/connections/connectionsDuck.ts
=> Make sure we always run :server connect when there's no connection

src/shared/modules/dbMeta/dbMetaDuck.ts
Preview @ http://db_fallback.surge.sh
=> Fallback to system if default not available

docs/modules/ROOT/pages/index.adoc
=> Update index.adoc to include reference to Aura

README.md, e2e_tests/support/defaults.ts, now.json, package.json
Hoping to address some pain points I and new contributors experienced with getting started and testing. I've also updated the screenshot and some structure.  
Preview: https://github.com/OskarDamkjaer/neo4j-browser/tree/repo_cleanup
=> Github repo spring cleaning

package.json, yarn.lock
=> Update neo4j driver to 4.4.0

src/browser/components/TabNavigation/Navigation.test.tsx, src/browser/components/TabNavigation/Navigation.tsx, src/browser/modules/App/App.tsx, src/browser/modules/D3Visualization/components/NodeInspectorDrawer.tsx, src/browser/modules/D3Visualization/components/NodeInspectorPanel.tsx, src/browser/modules/D3Visualization/components/styled.tsx, src/browser/modules/Sidebar/Sidebar.tsx, src/browser/modules/Stream/CypherFrame/__snapshots__/VisualizationView.test.tsx.snap
also cleanup of Navigation.tsx, removed unused stuff and fixed so showing content also on close.
=> Animate opening/closing of Node Inspector

src/browser/components/InputEnterStepping/InputEnterStepping.test.tsx, src/browser/components/desktop-api/desktop-api.test.tsx, src/browser/modules/FeatureToggle/FeatureToggle.test.tsx
=> Replaced deprecated wait and waitForElement

src/browser/modules/Stream/CypherFrame/CodeView.test.tsx, src/browser/modules/Stream/CypherFrame/relatable-view.test.tsx, src/browser/modules/Stream/CypherFrame/relatable-view.tsx, src/shared/services/utils.ts
=> Fix typescript issues

src/browser/components/ManualLink.tsx, src/browser/modules/ClickToCode/__snapshots__/index.test.tsx.snap, src/browser/modules/Sidebar/Documents.tsx, src/browser/modules/Sidebar/docsUtils.test.ts, src/browser/modules/Sidebar/docsUtils.ts, src/browser/modules/Stream/CypherFrame/__snapshots__/ErrorsView.test.tsx.snap, src/browser/modules/Stream/CypherFrame/__snapshots__/VisualizationView.test.tsx.snap, src/browser/modules/Stream/__snapshots__/SchemaFrame.test.tsx.snap
Move the formatDocVersion dep to a utils file to avoid a circular dependency
=> Remove circular dependency in manual link

docs/modules/ROOT/pages/operations/browser-sso.adoc
=> update SSO content

src/browser/modules/Sidebar/docsUtils.ts
Forgot to add the copyright header in the last file I created
=> add copyright header

package.json, yarn.lock
and then got rid of ts errors due to different @types/react versions
=> Upgrade to react 17

src/browser/modules/D3Visualization/components/DetailsPane.test.tsx, src/browser/modules/D3Visualization/components/DetailsPane.tsx
=> Cut long property values cleanup

docs/modules/ROOT/pages/operations/browser-sso.adoc
=> Keycloak not KeyCloak

src/browser/components/ManualLink.test.tsx, src/browser/components/ManualLink.tsx, src/browser/modules/DBMSInfo/DatabaseKernelInfo.tsx, src/browser/modules/Sidebar/About.tsx, src/browser/modules/Sidebar/Documents.tsx, src/browser/modules/Sidebar/docsUtils.ts, src/browser/modules/Stream/Queries/QueriesFrame.test.tsx, src/browser/modules/Stream/Queries/QueriesFrame.tsx, src/browser/modules/Stream/SchemaFrame.tsx, src/shared/modules/connections/connectionsDuck.ts, src/shared/modules/dbMeta/dbMeta.utils.ts, src/shared/modules/dbMeta/dbMetaDuck.ts, src/shared/modules/features/featureDuck.utils.ts, src/shared/modules/features/featuresDuck.test.ts, src/shared/modules/features/versionedFeatures.ts
=> Show current manuals instead of old if not connected to server

docs/modules/ROOT/pages/deployment-modes/neo4j-server.adoc, docs/modules/ROOT/pages/deployment-modes/web-application.adoc
=> updated centrally hosted browser

package.json, yarn.lock
The lib needed an update to work with on aura
=> Bump neo4j-client-sso

e2e_tests/integration/viz.spec.ts, src/browser/modules/D3Visualization/components/DetailsPane.test.tsx, src/browser/modules/D3Visualization/components/DetailsPane.tsx, src/browser/modules/D3Visualization/components/Explorer.tsx, src/browser/modules/D3Visualization/components/GrassEditor.tsx, src/browser/modules/D3Visualization/components/NodeInspectorPanel.tsx, src/browser/modules/D3Visualization/components/OverviewPane.test.tsx, src/browser/modules/D3Visualization/components/OverviewPane.tsx, src/browser/modules/D3Visualization/components/StyleableNodeLabel.tsx, src/browser/modules/D3Visualization/components/StyleableRelType.tsx, src/browser/modules/D3Visualization/graphStyle.test.ts, src/browser/modules/D3Visualization/graphStyle.ts, src/browser/modules/D3Visualization/lib/visualization/components/graphView.ts, src/browser/modules/DBMSInfo/MetaItems.tsx, src/shared/services/grassUtils.ts
Cleanup of graphstyle file and adjacent stuff and getting rids of lots of typescript warnings.
Still a lot left, but decided to draw the line here for this PR so not changing too much in one PR.
=> Cleanup graphstyle

e2e_tests/integration/frame-interactions.spec.ts, src/browser/components/buttons/index.tsx
=> Added e2e tests for frame interactions

src/browser/modules/D3Visualization/components/Explorer.tsx
Sorry about the diff in the imports, it's from our new prettier rule. Not yet merged the PR reformatting the codebase
=> Improve viz performance by only deduplicating nodes until we have enough for display

e2e_tests/integration/viz.spec.ts, src/browser/modules/D3Visualization/components/Graph.tsx, src/browser/modules/D3Visualization/lib/visualization/components/GraphView.ts, src/browser/modules/D3Visualization/lib/visualization/components/Visualization.ts, src/browser/modules/D3Visualization/lib/visualization/components/mouseEventHandlers.ts, src/browser/modules/D3Visualization/lib/visualization/constants.ts, src/browser/modules/Stream/CypherFrame/__snapshots__/VisualizationView.test.tsx.snap
Also bugfix issue where wheel zoom is not working in safari.
=> Disable zoom buttons when limit reached

e2e_tests/integration/viz.spec.ts, src/browser/modules/D3Visualization/components/Graph.tsx, src/browser/modules/D3Visualization/lib/visualization/components/GraphView.ts, src/browser/modules/D3Visualization/lib/visualization/components/Visualization.ts, src/browser/modules/D3Visualization/lib/visualization/components/mouseEventHandlers.ts
also in fullscreen no mod key is required for wheel zoom.
=> Use shift, cmd or ctrl as mod key for wheel zoom

src/browser/documentation/index.ts, src/browser/modules/Stream/CypherFrame/CypherFrame.tsx, src/browser/modules/Stream/CypherFrame/ErrorsView.test.tsx, src/browser/modules/Stream/CypherFrame/ErrorsView.tsx, src/browser/modules/Stream/PlayFrame.tsx, src/browser/modules/Stream/Queries/QueriesFrame.tsx, src/shared/services/utils.ts
=> Typescript fixes

LICENSES.txt, NOTICE.txt, package.json, yarn.lock
Also ran the license update script
=> Bump driver to 4.4.2

src/shared/services/WorkPool.test.ts, src/shared/services/WorkPool.ts, src/shared/services/bolt/bolt.ts, src/shared/services/bolt/handleBoltWorkerMessage.ts, src/shared/services/bolt/setup-bolt-worker.ts
Follow up from https://github.com/neo4j/neo4j-browser/pull/1661. As in the previous PR, there are no functional changes here, only simplifying the code to make it easier to understand.
=> Bolt worker and work pool cleanup

src/browser/modules/App/App.tsx
=> Add neo4j edition to stats

e2e_tests/integration/params.spec.ts, e2e_tests/support/commands.ts, src/browser/modules/Stream/CypherFrame/ErrorsView/MissingParamsTemplateLink.tsx
=> Added e2e test for params template

package.json, src/browser/styles/themes.ts, yarn.lock
Now since Needle is released picked colors from there instead
=> Added Needle dependency and started to pick colors from there

package.json, src/browser/components/buttons/__snapshots__/ConfirmationButton.test.tsx.snap, src/browser/modules/ClickToCode/__snapshots__/index.test.tsx.snap, src/browser/modules/DBMSInfo/__snapshots__/MetaItems.test.tsx.snap, src/browser/modules/Sidebar/__snapshots__/GuideDrawer.test.tsx.snap, src/browser/modules/Sidebar/__snapshots__/UserSettings.test.tsx.snap, src/browser/modules/Stream/CypherFrame/ErrorsView/__snapshots__/ErrorsStatusbar.test.tsx.snap, src/browser/modules/Stream/CypherFrame/ErrorsView/__snapshots__/ErrorsView.test.tsx.snap, src/browser/modules/Stream/CypherFrame/RelatableView/__snapshots__/relatable-view.test.tsx.snap, src/browser/modules/Stream/CypherFrame/VisualizationView/__snapshots__/VisualizationView.test.tsx.snap, src/browser/modules/Stream/CypherFrame/__snapshots__/AsciiView.test.tsx.snap, src/browser/modules/Stream/CypherFrame/__snapshots__/CodeView.test.tsx.snap, src/browser/modules/Stream/CypherFrame/__snapshots__/WarningsView.test.tsx.snap, src/browser/modules/Stream/__snapshots__/HistoryRow.test.tsx.snap, src/browser/modules/Stream/__snapshots__/SchemaFrame.test.tsx.snap, src/common/icons/IconContainer.tsx, src/graphVisualization/components/styled.tsx, yarn.lock
Vulnerability in lodash. https://www.npmjs.com/advisories/1065345
=> Updated styled components to get audit fix

README.md
=> Update readme to mention arc

src/neo4j-arc/package.json
Test commit to see if the github action for automatic releases works properly!
=> Test release

src/neo4j-arc/package.json
=> Release 0.0.5

src/neo4j-arc/package.json, src/neo4j-arc/yarn.lock
=> Added missing deps in arc lib

e2e_tests/integration/frame-interactions.spec.ts, e2e_tests/integration/multi-db.spec.ts, src/browser/components/SavedScripts/styled.ts, src/browser/components/buttons/__snapshots__/ConfirmationButton.test.tsx.snap, src/browser/components/buttons/index.tsx, src/browser/init.ts, src/browser/modules/Editor/MainEditor.tsx, src/browser/modules/Sidebar/__snapshots__/GuideDrawer.test.tsx.snap, src/browser/modules/Sidebar/__snapshots__/UserSettings.test.tsx.snap, src/browser/modules/Stream/CypherFrame/ErrorsView/__snapshots__/ErrorsStatusbar.test.tsx.snap, src/browser/modules/Stream/CypherFrame/ErrorsView/__snapshots__/ErrorsView.test.tsx.snap, src/browser/modules/Stream/CypherFrame/RelatableView/__snapshots__/relatable-view.test.tsx.snap, src/browser/modules/Stream/CypherFrame/VisualizationView/__snapshots__/VisualizationView.test.tsx.snap, src/browser/modules/Stream/CypherFrame/__snapshots__/AsciiView.test.tsx.snap, src/browser/modules/Stream/CypherFrame/__snapshots__/CodeView.test.tsx.snap, src/browser/modules/Stream/CypherFrame/__snapshots__/WarningsView.test.tsx.snap, src/browser/modules/Stream/__snapshots__/HistoryRow.test.tsx.snap, src/browser/modules/Stream/styled.tsx, src/neo4j-arc/common/icons/IconContainer.tsx
and fixed styled that were broken when these global styles were added, also some cleanup of li:s that should be buttons.
=> Added needle base style file

.github/workflows/release-arc.yml
=> Update action env

.github/workflows/test-arc.yml, src/neo4j-arc/package.json
=> Add test step for arc

src/browser/modules/Stream/CypherFrame/VisualizationView/PropertiesPanelContent/DetailsPane.tsx, src/browser/modules/Stream/CypherFrame/VisualizationView/PropertiesPanelContent/styled.tsx, src/neo4j-arc/common/components/WarningMessage.tsx, src/neo4j-arc/graph-visualization/GraphVisualizer/DefaultPanelContent/DefaultDetailsPane.tsx, src/neo4j-arc/graph-visualization/GraphVisualizer/styled.tsx
=> Fixed issues where icon and text not on the same line

src/shared/modules/connections/connectionsDuck.ts
=> Set SSO as default if sso providers were present

src/browser/modules/Sidebar/__snapshots__/GuideDrawer.test.tsx.snap, src/browser/modules/Stream/CypherFrame/RelatableView/__snapshots__/relatable-view.test.tsx.snap, src/browser/modules/Stream/CypherFrame/RelatableView/relatable-view.tsx, src/browser/modules/Stream/CypherFrame/VisualizationView/__snapshots__/VisualizationView.test.tsx.snap, src/browser/modules/Stream/CypherFrame/__snapshots__/AsciiView.test.tsx.snap, src/browser/modules/Stream/CypherFrame/__snapshots__/CodeView.test.tsx.snap, src/browser/modules/Stream/CypherFrame/helpers.ts, src/browser/modules/Stream/__snapshots__/HistoryRow.test.tsx.snap, src/browser/modules/Stream/styled.tsx
fix so statusbar is back on one line istead of several.
Before:
After:
=> Bugfix statusbar on multiple lines

src/neo4j-arc/cypher-language-support/cypher-editor/CypherEditor.tsx, src/neo4j-arc/package.json, src/neo4j-arc/rollup.config.js
=> Change import to fix autocomplete

src/neo4j-arc/common/index.ts, src/neo4j-arc/common/types/cypherDataTypes.ts, src/neo4j-arc/common/utils/cypherTypeUtils.ts, src/neo4j-arc/package.json
And fixed bug causing float number to be formated weirdly with numberformat (2.2 => 2.2.0)
=> Added utils for checking type in cypherDataTypes.ts

docs/modules/ROOT/pages/operations/dbms-connection.adoc, docs/modules/ROOT/pages/visual-tour.adoc
Depends on https://github.com/neo-technology/neo4j-manual-modeling/pull/2774, which should be merged first.
=> Add a note that `+ssc` schemes are not supported

README.md, package.json
Fix the wording from *administrate* to *administer* in the readme and package.json.
=> Adjust wording in readme/package.json.

e2e_tests/integration/types.spec.ts, src/browser/modules/D3Visualization/queryPlan/queryPlan.ts, src/browser/modules/Stream/CypherFrame/VisualizationView/VisualizationView.styled.tsx, src/browser/modules/Stream/CypherFrame/VisualizationView/__snapshots__/VisualizationView.test.tsx.snap, src/browser/modules/Stream/HistoryFrame.tsx, src/neo4j-arc/graph-visualization/GraphVisualizer/Graph/styled.tsx, src/neo4j-arc/graph-visualization/GraphVisualizer/Graph/visualization/renderers/init.ts, src/neo4j-arc/package.json
The "outline" class name clashed with tailwind, so I renamed it to "b-outline"
=> Fix outline tailwind naming conflict

src/neo4j-arc/graph-visualization/GraphVisualizer/DefaultPanelContent/DefaultOverviewPane.tsx, src/neo4j-arc/graph-visualization/GraphVisualizer/DefaultPanelContent/styled.tsx, src/neo4j-arc/graph-visualization/GraphVisualizer/Graph/styled.tsx, src/neo4j-arc/graph-visualization/GraphVisualizer/GraphVisualizer.tsx, src/neo4j-arc/graph-visualization/GraphVisualizer/NodeInspectorDrawer.tsx, src/neo4j-arc/graph-visualization/GraphVisualizer/NodeInspectorPanel.tsx, src/neo4j-arc/graph-visualization/GraphVisualizer/styled.tsx, src/neo4j-arc/package.json
* Fixes an overflow issue (visible in NX Query)
* Adjusts pane and zoom controls positions to be more cohesive in all states
* Cleans up some duplicated styles.
Before:
After:
=> Fix graph pane overflow issue.

src/browser/modules/Stream/Auth/ConnectForm.tsx, src/browser/modules/Stream/Auth/ConnectionForm.tsx
Adds param `preselectAuthMethod` to preselect auth method in the connection form
=> Add url param to preselect in connect frame

e2e_tests/integration/saved-scripts.spec.ts
=> Make sure cypher frame is cleared for retry to work

package.json, src/browser/modules/Stream/CypherFrame/VisualizationView/VisualizationView.tsx, src/neo4j-arc/graph-visualization/GraphVisualizer/GraphVisualizer.tsx, src/neo4j-arc/graph-visualization/models/GraphStyle.ts, src/neo4j-arc/package.json, src/neo4j-arc/yarn.lock, yarn.lock
=> Use new graph viz color generation by default in arc

.npmrc, .yarnrc, src/neo4j-arc/yarn.lock, yarn.lock
We're looking to stop using the jfrog service over the default yarn registry as we no longer need it :+1:
=> Get rid of jfrog

src/browser/modules/Stream/Extras/index.ts, src/browser/modules/Stream/FrameContainer.tsx
The dynamic import led to warnings in the console from styled components
=> Remove dynamic import

src/browser/modules/Main/Main.tsx
=> Fix bug that cauases consent message not to show properly

.github/workflows/pr-e2e-tests.yml, .github/workflows/pr-unit-tests.yml, .github/workflows/release-arc.yml, .github/workflows/test-arc.yml, e2e_tests/integration/multi-db.spec.ts
=> Github actions migration

src/neo4j-arc/cypher-language-support/index.ts, src/neo4j-arc/package.json
=> Export parse functions from cypher editor support library in arc

e2e_tests/integration/sysinfo-command.spec.ts
=> Remove one e2e test for sysinfo for 4.0 since not working in that version

src/browser/modules/DBMSInfo/DatabaseSelector.tsx, src/shared/services/exceptions.ts
and disable the selection while it is starting up.
https://user-images.githubusercontent.com/11065688/192777565-db15ecf0-87c3-45c8-96d1-2b80ed1b9abd.mov
and fixed wrong code type in DatabaseUnavailableError.
=> Added better feedback for when newly created db is online

src/browser/documentation/help/load-csv.tsx, src/browser/documentation/play-guides/northwind-graph.tsx, src/browser/documentation/sidebar-guides/northwind-graph.tsx
Prevents incorrect data from the https redirect
=> fix urls for loading northwind data

src/browser/modules/DBMSInfo/__snapshots__/MetaItems.test.tsx.snap, src/browser/modules/Stream/CypherFrame/VisualizationView/PropertiesPanelContent/DetailsPane.tsx, src/browser/modules/Stream/CypherFrame/VisualizationView/PropertiesPanelContent/OverviewPane.tsx, src/browser/modules/Stream/CypherFrame/VisualizationView/PropertiesPanelContent/styled.tsx, src/neo4j-arc/graph-visualization/GraphVisualizer/DefaultPanelContent/DefaultDetailsPane.tsx, src/neo4j-arc/graph-visualization/GraphVisualizer/DefaultPanelContent/DefaultOverviewPane.tsx, src/neo4j-arc/graph-visualization/GraphVisualizer/DefaultPanelContent/styled.tsx, src/neo4j-arc/graph-visualization/GraphVisualizer/styled.tsx, src/neo4j-arc/package.json
To allow custom padding when overriding content.
Removed PaneContainer since not used.
=> Remove padding in viz details pane in arc

src/browser/modules/Stream/CypherFrame/VisualizationView/PropertiesPanelContent/styled.tsx, src/neo4j-arc/graph-visualization/GraphVisualizer/DefaultPanelContent/styled.tsx
Fix scroll that was broken in this #1835.
=> Fixed broken auto scroll of properties pane

src/neo4j-arc/cypher-language-support/cypher-editor/CypherEditor.tsx, src/neo4j-arc/package.json
if using it in a context where the editor is just used for text input, for example editing a cypher query in a form.
=> Add optional isExecutable prop to editor

e2e_tests/integration/viz.spec.ts, src/neo4j-arc/common/components/PropertiesTable/PropertiesTable.tsx, src/neo4j-arc/common/components/ShowMoreOrAll/ShowMoreOrAll.tsx
=> Add e2e for node details with lots of props

src/browser/modules/Stream/CypherFrame/VisualizationView/VisualizationView.tsx, src/neo4j-arc/graph-visualization/GraphVisualizer/Graph/Graph.tsx, src/neo4j-arc/graph-visualization/GraphVisualizer/Graph/visualization/Visualization.ts, src/neo4j-arc/graph-visualization/GraphVisualizer/GraphVisualizer.tsx
=> fix issue where zooming when expanding node

src/neo4j-arc/common/components/ClipboardCopier.tsx, src/neo4j-arc/package.json
also adjusted messages to be closer to copy icon to save space if there is shortage of space
=> possible to change message text in copier

e2e_tests/integration/viz.spec.ts
=> fix flaky test

e2e_tests/integration/bolt.spec.ts, e2e_tests/integration/editor.spec.ts, e2e_tests/integration/user.spec.ts
=> fix: use longer passwords in tests

src/shared/modules/commands/helpers/params.test.ts, src/shared/modules/commands/helpers/params.ts, src/shared/modules/dbMeta/dbMetaDuck.ts, src/shared/modules/dbMeta/dbMetaEpics.ts, src/shared/services/commandInterpreterHelper.ts, src/shared/utils/selectors.ts
To make sure we don't run commands against composite dbs that don't work.
=> Treat composite dbs as system database

src/shared/services/utils.ts
Closes #1258. 
Before: 
After:
=> Fix indent formatting in nested objects

.github/workflows/pr-e2e-tests.yml, e2e_tests/integration/bolt.spec.ts
=> Update missed password change

src/browser/modules/DBMSInfo/DatabaseSelector.tsx, src/browser/modules/Stream/CypherFrame/helpers.ts, tsconfig.json
Adds database alias names to the database selector in the sidebar
=> show alias name in database selector

e2e_tests/integration/multi-db.spec.ts, src/shared/services/commandInterpreterHelper.ts
=> Show aliases in prompt & clear metadata on switching database

src/browser/modules/DBMSInfo/DBMSInfo.tsx, src/browser/modules/DBMSInfo/DatabaseSelector.test.tsx, src/browser/modules/DBMSInfo/DatabaseSelector.tsx
=> Prevent development console error if disconnecting with sidebar open

package.json, src/neo4j-arc/package.json, src/neo4j-arc/yarn.lock, yarn.lock
=> Update driver to 5.3.0

src/shared/modules/cypher/cypherDuck.ts, src/shared/modules/dbMeta/dbMetaEpics.ts
=> Ensure lost connection doesn't break browser

src/browser/modules/Main/Main.test.tsx, src/browser/modules/Main/Main.tsx
=> Updated licensing text after request from sales team

src/neo4j-arc/graph-visualization/GraphVisualizer/NodeInspectorPanel.tsx, src/neo4j-arc/graph-visualization/GraphVisualizer/styled.tsx, src/neo4j-arc/package.json
=> Use button instead of div and correct styling in dark mode for properties panel

src/shared/services/exporting/imageUtils.ts
=> fix bug where plan view downloads got very low resolution

docs/modules/ROOT/pages/reference-commands.adoc
=> added note about auto-committing transactions

src/browser/modules/Sidebar/__snapshots__/GuideDrawer.test.tsx.snap, src/browser/modules/Stream/CypherFrame/RelatableView/__snapshots__/relatable-view.test.tsx.snap, src/browser/modules/Stream/CypherFrame/WarningsView.tsx, src/browser/modules/Stream/CypherFrame/__snapshots__/AsciiView.test.tsx.snap, src/browser/modules/Stream/CypherFrame/__snapshots__/CodeView.test.tsx.snap, src/browser/modules/Stream/CypherFrame/__snapshots__/WarningsView.test.tsx.snap, src/browser/modules/Stream/styled.tsx
Warnings and notifications should display their respective code with the notification. Also adds the notification label as a blue chip.
=> Add codes to frame notifications

src/browser/modules/App/App.tsx, src/browser/modules/Main/Main.test.tsx, src/browser/modules/Main/Main.tsx, src/shared/modules/dbMeta/__snapshots__/dbMetaDuck.test.ts.snap, src/shared/modules/dbMeta/dbMetaDuck.ts, src/shared/modules/dbMeta/dbMetaEpics.ts, src/shared/modules/dbMeta/utils.ts
The new procedure is CALL dbms.licenseAgreementDetails()
=> update trial status check to use new procedure

src/browser/modules/Stream/DebugConnectivityFrame.tsx
Changes:
- Nicer handling of missing URL
- Properly reset state on reruns 
- Make sure alert text is readable in darkmode
=> Debug connectivity touch ups 

src/browser/modules/Stream/Auth/ConnectionFormController.tsx, src/shared/modules/dbMeta/dbMetaDuck.ts
=> prevent briefly storing credentials before reading setting

docs/preview.yml, docs/publish.yml
Some links were broken because this attributed wasn't set before.
=> Updating file with docs-base-uri and neo4j-docs-base-uri attribute

src/shared/modules/dbMeta/dbMetaEpics.ts
=> only call license procedure when it's expected to be available

src/shared/modules/dbMeta/dbMetaDuck.ts, src/shared/modules/dbMeta/dbMetaEpics.ts
=> don't wait for labels to load before reading settings

docs/modules/ROOT/pages/deployment-modes/dedicated-web-server.adoc, docs/modules/ROOT/pages/deployment-modes/neo4j-server.adoc, docs/modules/ROOT/pages/operations/credentials-handling.adoc, docs/modules/ROOT/pages/operations/product-analytics.adoc, src/browser/modules/Stream/SysInfoFrame/sysinfoHelpers.tsx
=> Update all links to configs

src/browser/modules/DBMSInfo/DBMSInfo.tsx, src/browser/modules/DBMSInfo/DatabaseSelector.test.tsx, src/browser/modules/DBMSInfo/DatabaseSelector.tsx, src/shared/modules/dbMeta/dbMetaDuck.ts
Each cluster member can have it's own copy of a database, if we have multiples we prefer the online one.
=> handle stopped cluster members

docs/preview.yml, docs/publish.yml
=> remove numbered sections

src/browser/modules/Frame/FrameEditor.tsx
=> Fix giving a custom name when adding a favorite script

src/shared/services/bolt/bolt.ts
=> fix bug where metadata was incorrectly formated

docs/preview.yml, docs/publish.yml
=> update ui bundle url

package.json, src/browser/modules/Stream/Auth/ConnectForm.tsx, src/shared/modules/connections/connectionsDuck.ts, src/shared/modules/discovery/discoveryHelpers.ts, yarn.lock
=> Respect `visible` field in SSO provider configuration

docs/modules/ROOT/pages/index.adoc
The copy for this promo comes from https://github.com/neo4j-graphacademy/courses/blob/main/asciidoc/courses/cypher-fundamentals/promo.adoc
=> added promo to home page

docs/modules/ROOT/pages/operations/browser-sso.adoc, docs/modules/ROOT/pages/operations/browser-url-parameters.adoc
A first shot at documenting the `sso_redirect`. I had a quick look to see if it's also implemented in upx/workspace and it doens't look like it. I'd confirm with @nglgzz who wrote the SSO for that project
=> document sso_redirect

src/browser/modules/Stream/PlayFrame.tsx
=> hide preview in desktop
