app/scripts/services/RequestInterceptor.coffee, test/spec/other/RequestHeaders.coffee
- To tell server that we want to be treated
with special response headers.
=> Send 'X-Ajax-Browser-Auth' header on requests

app/scripts/services/Bolt.coffee, app/scripts/services/UtilityBolt.coffee
This would be the ideal query:
```
CALL db.indexes() YIELD description, state, type
WITH COLLECT({description: description, state: state, type: type}) AS indexes
CALL db.constraints() YIELD description
WITH indexes, COLLECT({description: description}) AS constraints
RETURN indexes, constraints
```
but in the case of 0 constraints the indexes aren't returned either.  
So we had to do it with a `UNION` and have two rows returned instead.
=> Reduce number of queries to a single one for :schema

app/scripts/controllers/D3Graph.coffee, app/scripts/controllers/Inspector.coffee
This is so the user can make multiple changes to the style without reselecting the label
=> Keep viz style editor open

app/scripts/controllers/Main.coffee
Read `browser.post_connect_cmd` from server and
execute if it exists.
When picking first frame we still don't have access to this server config so that can't be a candidate on `pickFirstFrame()` but this will come after.
=> On connect, exec command from server config

app/scripts/controllers/Main.coffee, lib/helpers.coffee, test/spec/other/utils.coffee
This change exposes an API though URL params making it easier to publish links to prepopulate the editor.
The URL param API looks like this:
`cmd` - the command to use. Could be `play` or `help` or anything we decide to support.
`arg` - Zero or more of these args. 
Current implementation:   
- `cmd` - This command will be prefixed by the current users config `cmdchar` (which defaults
to `:`). The special case here being `cmd=cypher`. In that case, the command is stripped and not prefixed by anything.  
- `arg` - They will be inserted in the order they appear in the URI and separated by a space.
This does **NOT** execute the command automatically. It adds content to the editor, the user must execute the command manually.
Examples:
Link to external guide: …
=> Expose URL param API to populate editor

app/scripts/services/CurrentUser.coffee, app/scripts/services/NTN.coffee
when logging in a second time with different service
=> Call destroy in sync object to avoid getting error message

app/scripts/services/Bolt.coffee, lib/visualization/components/queryPlan.coffee
To test:
Prepare:
```
CREATE INDEX ON :Person(name)
CREATE (n:Person {name:"John", age: 25})
```
Try below query in current master. NodeIndexSeek used, but no index shown.
```
EXPLAIN MATCH (n:Person) WHERE n.name = 'John' RETURN n
```
Try in this branch, now shows the index used.
=> Display index used in query plan

app/views/frame-qs.jade, app/views/partials/frame-list-users.jade
It's confusing to have the same icon for different actions.
Old:  
New:
=> Change delete icon to minus (-), and keep (x) as cancel

app/views/partials/user-roles.jade
Removes the misstake of adding no roles when adding users that keeps happening.
=> Add roles onselect without confirmation step

app/scripts/filters/neo4jdoc.coffee, test/spec/filters/neo4jdoc.coffee
changelog: Update links to docs on pre-releases to 'beta'
=> Return 'beta' urls for doc's when server returns a non ga release

app/scripts/controllers/CypherResult.coffee, app/scripts/init/commandInterpreters.coffee, app/scripts/services/CypherTransactionBolt.coffee, app/views/frame-cypher.jade, lib/helpers.coffee
REST don't have access to this information so the old timer is kept there.
Read query:  
> Started streaming 25 records after 0 ms and completed after 1 ms.
Read query, no hits:  
> Completed after 0 ms.
Query without returns:  
> Completed after 0 ms.
Write query:  
> Set 250 properties, started streaming 250 records after 7 ms and completed after 19 ms.
Profile query (just showing the resultAvailableAfter timing):  
> Cypher version: CYPHER 3.1, planner: COST, runtime: INTERPRETED. 2 total db hits in 18 ms.
Raw / Code view:  
> Started streaming 25 records after 0 ms and completed after 1 ms.
Updates, no returns:  
> Set 250 properties, statement completed in 4 ms.
No updates, no returns:  
> (no changes, no records)
=> Read and present query timings from result when using Bolt

app/index.jade, app/scripts/controllers/Parameter.coffee, app/scripts/init/commandInterpreters.coffee, app/scripts/services/Frame.coffee, app/views/frame-parameter.jade
- Add a frame statusbar to give users feedback when defining parameters.
- Make sure that object litterals gets parsed correctly
- Fixes #333
=> Change `:param` workflow to give user better feedback on errors

app/scripts/init/statusCheck.coffee, app/scripts/services/Auth.coffee, app/scripts/services/Bolt.coffee, app/scripts/services/CypherTransactionBolt.coffee, app/scripts/services/Server.coffee, app/scripts/services/UtilityBolt.coffee
Use same driver for testing connections as well as for running queries.
=> Avoid multiple 'logged in' logs in security log when using Bolt

app/scripts/controllers/CypherResult.coffee
The stats have different names in Bolt vs. REST
- Bolt: `relationships_deleted`
- REST: `relationship_deleted`
=> Fix reported stats when deleting relationships

app/content/guides/sysinfo.jade
No other store-related entries in that column have "Size" as suffix.
This commit simply makes naming of the String Store entry consistent with other store entries.
=> renames 'String Store Size' to 'String Store', in sysinfo - Store Sizes table

src/browser/modules/App/App.jsx, src/browser/modules/ClickToCode/index.jsx, src/browser/modules/ClickToCode/styled.jsx, src/browser/modules/Main/Main.jsx, src/browser/modules/Main/styled.jsx, src/browser/modules/Sidebar/Sidebar.jsx, src/browser/styles/themes.js, src/shared/modules/connections/connectionsDuck.js, src/shared/modules/settings/settingsDuck.js
Add connection feedback banners below editor.
* Removed badge over DB icon in sidebar.
* Blue banner - Not connected to a database. Click on part of banner to populate editor with `:server connect`
* Orange banner - Connection lost, trying to reconnect.
=> Connection feedback banners

package.json, yarn.lock
We are not affected by any of the breaking changes: https://gist.github.com/developit/89e0e6decb8fb5eb00def024b6fb7bd7
This should be a win for us:
- https://github.com/developit/preact/releases/tag/8.0.0
- https://github.com/developit/preact/releases/tag/8.1.0
=> Upgrade to Preact 8

src/browser/modules/ClickToCode/index.jsx, src/browser/modules/NevadaVisualization/NevadaWrapper.jsx
Instead of:
```
Database access not available. Please use `:`  to establish connection. There's a graph waiting for you.
```
It now shows:
```
Database access not available. Please use `:server connect`  to establish connection. There's a graph waiting for you.
```
=> [Bugfix] Show full children content in click to code

src/browser/components/Tables.jsx, src/browser/modules/Stream/SysInfoFrame.jsx
Fixes:
- Mapping objects without `attributes`
- Optional values throwing errors (In a clean Neo4j instance we don't have access to 'PageCache' or 'Transactions')
- Displaying `-` rather than empty values
=> Handle responses in :sysinfo frame where some attributes are unavailable

src/browser/modules/App/App.jsx, src/browser/modules/Help/html/commands.html, src/browser/modules/Help/html/index.js, src/browser/modules/Main/Main.jsx, src/browser/modules/Main/styled.jsx, src/shared/modules/commands/commandsDuck.js, src/shared/modules/commands/commandsDuck.test.js, src/shared/rootReducer.js, src/shared/services/commandInterpreterHelper.js, src/shared/services/commandInterpreterHelper.test.js, src/shared/services/commandUtils.js, src/shared/services/commandUtils.test.js
- Dispatch action of type UNKNOWN_COMMAND on unkown commands.
- Don't add it to history.
- Send action of type KNOWN_COMMAND on found commands.
- Show unknown command banner
- Add help doc `:help commands`, `:help server` and `:help server-user`.
- Animate all banners.
=> Handle unknown commands

package.json, src/browser/modules/ClickToCode/__snapshots__/index.test.js.snap, src/browser/modules/ClickToCode/index.jsx, src/browser/modules/ClickToCode/index.test.js
The main issue is that react bevaiour changed when interpolating strings in JSX.
In Preact 7.2.1 these are the same (`:server connect` in `children[0]`)
```
<div>
{props.cmdchar}server connect
</div>
// and
<div>
{props.cmdchar + 'server connect'}
</div>
```
where in Preact 8 the first example actually created an array of two children.
In this PR I also introduce our first component render tests using `preact-render-to-string` and Jest snapshots.
=> Add tests for ClickToCode

src/browser/modules/Stream/Views/ErrorsView.jsx, src/browser/modules/Stream/styled.jsx, src/shared/modules/cypher/procedureFactory.js, src/shared/services/cypherErrorsHelper.js
Displays a helpful link in the cypher result frame whenever `Neo.ClientError.Propcedure.ProcedureNotFound` is returned
=> Display link to show available procedures when a user executes an unknown procedure

src/browser/modules/Stream/CypherFrame.jsx, src/browser/modules/Stream/Views/AsciiView.jsx, src/browser/modules/Stream/Views/TableView.jsx, src/browser/modules/Stream/styled.jsx, src/shared/services/bolt/bolt.js, src/shared/services/bolt/boltMappings.js, src/shared/services/bolt/updateStatisticsFields.js
- Retrieve query update statistics from bolt result (from summary.counters)
- Prepend update stats to streaming stats in Status Bar
- Present update stats in Body in Table & Ascii View if there are no rows
=> Retrieve and present update statistics from bolt result

src/browser/modules/Stream/Views/AsciiView.jsx, src/shared/services/bolt/boltMappings.js, src/shared/services/bolt/boltMappings.test.js
The mapping that is required for the ascii view to display results correctly is extracted out to the service layer in `boltMappings`.
I've attached screenshot to show the difference in the ascii view rendering.
Bug:
Fix:
=> Fix issue where ascii view doesn't display properties correctly

src/browser/modules/Stream/HelpFrame.jsx
Small fix.
Now all variations will work properly:
```
:help match
:help MATCH
:help Match
```
=> Help: case-insensitive guide lookup

src/browser/components/Directives.jsx
Currently the browser _incorrectly_ executes the code snippet in a guide. This PR fixes this to only populate the editor. The user can then choose to execute the code snippet or not.
=> Update editor content on code snippet click

src/browser/components/form/formKeyHandler.js, src/browser/modules/Main/styled.jsx, src/browser/modules/Stream/Auth/ConnectForm.jsx, src/browser/modules/Stream/Auth/ConnectionForm.jsx
Solves the problem of focusing on the bottom connection frame when disconnected and there are more than one connection frames in the stream. The solution is to avoid connection form request focus if it is used once or created in connected state.
=> Focus on the connection form only if it is used for the first time

src/shared/modules/dbMeta/__snapshots__/dbMetaDuck.test.js.snap, src/shared/modules/dbMeta/dbMetaDuck.js, src/shared/modules/dbMeta/dbMetaDuck.test.js, src/shared/services/bolt/bolt.js, src/shared/services/bolt/boltHelpers.js
Store in `meta` reducer and update on every meta data update, since server con be restarted with new settings without the browser being reloaded.
The data stored is not used for anything with this PR, but will in future features.
=> Fetch and store server config and info in redux

src/browser/modules/DatabaseInfo/UserDetails.jsx
Handles mapping user details in the sidebar where 'roles' key is not available (usually in the community edition of the neo4j server)
=> Fix mapping of procedure results in the sidebar (user details)

src/browser/modules/Stream/SysInfoFrame.jsx
Fixes a bug when executing `:sysinfo` against a causal cluster (tags -> groups)
=> Fix cc mapping issue in :sysinfo

src/browser/modules/Editor/Codemirror.jsx, src/shared/services/commandUtils.js, src/shared/services/commandUtils.test.js
Unmount now is doing nothing. Basically when React component unmounts it removes element from DOM. When CM instance removed from DOM, it's no longer in use and will be GC'ed.
I took an memory snapshot while switching between fullscreen editor and usual one, and no leaks found.
Regexp that clean cypher query where incorrect. It also removed normal newlines.
Switched from pure regexp to mix of split/join + regexp, in order to solve issues with last newline.
Also removed one test case because it's incorrect. If user have for some reason placed `1` on next line, it should stay there.
=> Editor fixes - escape and newlines

src/browser/components/icons/Icons.jsx, src/browser/components/icons/style.css, src/browser/modules/Sidebar/Sidebar.jsx
Colors are now used to indicate status. They're brighter again, but not quite as neon as in prior releases. Oh, except that the Neo4j icon has a pulsing green blue which only indicates that we are awesome.
=> tweaked sidebar icon colors and state changes

src/browser/components/Directives.jsx
Defines the behaviour (populate editor/exec command) of a 'click' for each element selector
=> Introduce the autoExec flag to Directives

src/shared/services/bolt/boltMappings.js
Avoid ascii table throwing exception when return values are null, like RETURN NULL
=> Avoid exceptions with null return values

src/browser/modules/Editor/Editor.jsx, src/browser/modules/Editor/editorSchemaConverter.js, src/browser/modules/Editor/editorSchemaConverter.test.js, src/browser/modules/Editor/language/consoleCommands.js
PR should provide extensive list of all commands and their subcommands support by browser.
Picture:
=> Cypher Editor - define list of commands with subcommands

src/browser/components/TabNavigation/styled.jsx
=> Add z-index to drawer so that content is hidden in safari

src/browser/modules/Stream/PlayFrame.jsx
Fallback on `start` guide if user doesn't specify one.
=> Empty play => :play start

src/shared/services/remote.js
`'Content-Type': 'application/json;charset=UTF-8'` is not a valid header.
Also add more headers that should be there.
=> Fix headers for HTTP commands

src/browser/modules/Stream/styled.jsx
Also add `$` in the beginning.
Before:
After:
=> Align command in frame titlebar

src/browser/modules/App/App.jsx, src/browser/modules/UserInteraction/index.jsx, src/shared/modules/credentialsPolicy/credentialsPolicyDuck.js, src/shared/modules/dbMeta/dbMetaDuck.js, src/shared/modules/userInteraction/userInteractionDuck.js, src/shared/rootEpic.js, src/shared/services/utils.js, src/shared/services/utils.test.js
The goal of this PR is to let the server control for how long a client using Neo4j Browser can be inactive until a automatic disconnect happens.
When server config `browser.credential_timeout` is set, a timer is started. When this times runs out, user gets disconnected.
Timer is reset on every user interaction (keyup || mouse click).
=> Adapt to server config browser.credential_timeout

src/browser/modules/Stream/Views/TableView.jsx
Now returns `false` value rather than `(empty)`
Issue: 
Fixed:
=> Fix issue where table view was showing 'empty' for a valid 'false' value

src/browser/components/EditionView.jsx, src/browser/modules/Stream/Queries/QueriesFrame.jsx
When running `:queries` in community edition we now get <img width="1156" alt="screen shot 2017-05-02 at 09 04 50" src="https://cloud.githubusercontent.com/assets/849508/25609525/77f85f38-2f17-11e7-9e14-1a37907dca5e.png">
=> Render enterprise frame for :queries when procedures are unavailable

src/browser/modules/Editor/Editor.jsx
Matchbrackets have this behaviour by default to move ending bracket to a separate line.
We do not want it to be that smart.
What's more important - it screws autocompletion when you hit 'enter'.
=> Cypher Editor - Disable explode of matching brackets

src/browser/modules/Stream/CypherFrame.jsx, src/browser/modules/Stream/Views/AsciiView.jsx, src/browser/modules/Stream/Views/TableView.jsx, src/shared/services/bolt/bolt.js, src/shared/services/utils.js, src/shared/services/utils.test.js
To not have precision loss we did `val.toString()` on `neo4j.integers` when displaying the response.
This did have the implication that integers got quoted, just as any string, which is very misleading.
The changes in this PR changes that.
The change is made that we now implement our own version of `JSON.stringify` that should be compatible, but with one important change: our version takes a modifier function that have first access to all values passing through and can choose to modify the value, or just skip and let other handle it.
Before:
After:
=> Display integers as integers in response

src/browser/modules/Editor/Editor.jsx
- [UP] will cycle back through history commands
- [Down] will cycle forward through history commands
Note: These will only work when the command is a single line. A modifier key is required to cycle through multiline commands
=> Add additional key bindings to go through history

src/browser/modules/Editor/Editor.jsx, src/browser/modules/Editor/styled.jsx
Seemed to be caused by the switching of wrapper components that were a parent to <CodeMirror />. This fix is to switch styling within the same styled component
=> Fixes issue where editor in fullscreen was thowing a 'style' error

src/shared/modules/dbMeta/dbMetaDuck.js
It allows us to parse the version with/without the version being at the end of the returned string
=> Fix parsing of kernel version

src/browser/components/TabNavigation/styled.jsx, src/browser/components/drawer/Drawer.jsx
Downside being that the content of the drawer get's relayed out during grow time.
Could potentially be slow when having a large amount of meta data items.
But this PR fixes the imminent issue of unclosable sidebar in IE.
=> Don't add a default width to drawer

src/browser/modules/Stream/Stream.jsx
Only scrolls to the top of the stream when a new frame is added
=> Fix issue where stream would scroll to top on frame rerun

src/browser/modules/D3Visualization/components/Explorer.jsx, src/browser/modules/D3Visualization/components/Graph.jsx, src/browser/modules/Sidebar/Settings.jsx, src/browser/modules/Stream/Visualization.jsx, src/shared/modules/settings/settingsDuck.js
A setting has been added, 'Connect result nodes', replacing 'Auto complete' of the previous version.
If this setting is checked, after a cypher query result is retrieved, a second query is executed to fetch relationships between result nodes.
Movie dataset query response before:
and after:
=> Fetch internal relationships between displayed nodes (Auto complete)

src/browser/modules/Sidebar/Settings.jsx, src/browser/modules/Stream/Stream.jsx, src/shared/modules/settings/settingsDuck.js
The scroll to top will only kick in once a frame is added (this handles rerun/frame removal issues we've had)
Added toggle to the sidebar
=> Only scroll to top of stream when frame is added and toggle is on

src/browser/components/TabNavigation/Navigation.jsx
Drawers never went into non-selected mode when closed before this fix.
Before:
After:
=> Reset open drawer in state when closing drawer

src/browser/modules/D3Visualization/components/Explorer.jsx, src/browser/modules/D3Visualization/components/Graph.jsx, src/browser/modules/Stream/Visualization.jsx
This bug happens when graph object cuts the nodes off when Initial Node Display limit is exceed. Visualisation component is unaware of the final displayed nodes and tries to find relations between all retrieved nodes. Fixed by passing graph object to Visualisation component thus it request relations between only displayed nodes.
=> Fix the error occurs on auto-complete when initial Node Display threshold is exceeded

src/browser/modules/Guides/html/start.html
Currently we don't add variables in `:play` guides. This removes this usage from the start guide.
=> Remove untemplated version variable from start guide

src/browser/modules/Help/html/help.html
Commented out broken link as it seems to be what we have done everywhere else. I assume this is so we don't have to cross reference with the 2.0 code base as to what they should be
=> Remove untemplated help url

src/browser/index.jsx, src/shared/modules/discovery/discoveryDuck.js, src/shared/modules/discovery/discoveryDuck.test.js, src/shared/modules/editor/editorDuck.js
When Neo4j Browser is served from Neo4j Server the bolt url is auto discovered through a request to Neo4j Server `GET /`.
In the case of a externally hosted Neo4j Browser it can make connecting to Neo4j easier if a connect url can be passed along with the link to Neo4j Browser.
Example: `http://browser.neo4j.com/?connectURL=neo4jdb.xxyyzz.com:26000`.
If a hosted Neo4j Browser was available on `http://browser.neo4j.com` it would set the bolt url to `neo4jdb.xxyyzz.com:26000` and try to connect.
If no protocol is prepended the host, `bolt://` is assumed. If protocol is `bolt+routing://`, user settings `useBoltRouting` is set to `true` to enable routing when it's available.
A refactor of how to get the current url is in this as well.
To make the epics testable the action `APP_START` passes …
=> Define URL to connect to with URL param 'connectURL'

src/browser/modules/DatabaseInfo/MetaItems.jsx
Noticed a typo that exists if there are no property keys
=> Corrects typo in PropertyItems

package.json, pom.xml, scripts/set-pom-version.js, src/browser/modules/Sidebar/About.jsx, webpack.config.js, yarn.lock
Actions required on release is now to:
```
npm version 3.0.0-RC2
```
That command changes version in `package.json` and creates and tags a new commit with the new version.
Pushing to git repo is not part of this npm script.
This also updates `pom.xml` so we can remove a build step.
=> Set and read version from package.json and pom.xml

src/browser/modules/Editor/Editor.jsx
`notification.position` can be an empty object. If it is, show error on line 1.
Fixes the `chunkSize` error.
=> Don't assume `notification.position.line` being there

src/browser/modules/Stream/SysInfoFrame.jsx
This is a very simple typo-change (hopefully I didn't break any contribution protocol 😃 )
I changed "Propery ID" to "Property ID":
=> Fix typo in SysInfoFrame.jsx

package.json, src/browser/modules/Stream/Auth/ConnectedView.jsx, src/browser/modules/Stream/Auth/ConnectionForm.jsx, src/shared/modules/connections/connectionsDuck.js, src/shared/modules/connections/connectionsDuck.test.js, src/shared/modules/dbMeta/dbMetaDuck.js, src/shared/rootEpic.js, src/shared/services/bolt/boltHelpers.js, yarn.lock
On connect (and at the regular interval) read server config `browser.retain_connection_credentials`.
If set to a falsy value, remove persisted connection credentials from web browsers localstorage. 
Keep in memory to be able to use in a Causal clustered environment where new connections might be opened to run a query on every cluster member (`:queries` for example).
Show persist status on the `:server connect` frame.
Connect when set to false:
and true (default):
=> Read and act on server config retain_connection_credentials

src/shared/services/commandInterpreterHelper.js
Missed this when refactored the `getServerConfig` function.
With this fix the server whitelist is parsed and respected correctly.
=> Fix failure to parse server config browser.remote_content_hostname_whitelist

src/browser/modules/Stream/HelpFrame.jsx, src/browser/modules/Stream/PlayFrame.jsx, src/shared/services/commandInterpreterHelper.js, src/shared/services/commandInterpreterHelper.test.js
The commands are now case insensitive `:play` -> `:PlAy` and the parameters for `play` and `help` topics are case insensitive `:play cypher` -> `:PlAy CyPhEr`
=> Make the Browser commands case insensitive

src/browser/modules/App/styled.jsx
Fixes #512 
Can you tell the different browsers apart? 😸 
Firefox in Mac OS and MS Edge also had this behavior.
Scrollbar visible on all screenshots below.
=> Fix missing scrollbars in left drawer in some web browsers

src/browser/components/DataTables.jsx, src/browser/modules/Stream/CypherFrame.jsx, src/browser/modules/Stream/Views/TableView.jsx, src/browser/modules/Stream/styled.jsx, src/shared/services/bolt/bolt.js, src/shared/services/bolt/boltMappings.js, src/shared/services/bolt/boltMappings.test.js
Table view lacked the styling and also exposed all properties of all objects. With this PR it is styled considering array and Neo4j graph objects; Node, Relationship and Path. Below are before / after screenshots.
=> Style table view and just show relevant information

src/browser/modules/Stream/FrameTitlebar.jsx, src/shared/modules/commands/commandsDuck.js, src/shared/modules/commands/commandsDuck.test.js
This could be seen as a short term fix to bring back the desired behavior.
The real fix would be to not strip anything from any command and leave that responability to every interpreter.
This also populates the editor with the original query (incl. empty lines and comments) when clicking the frame titlebar. Only for Cypher queries though.
Before this fix, 
```
WITH 1 as One
//Comment
RETURN One
```
would yield and error.
=> Only strip comments and empty lines from `:`-commands

src/browser/modules/DatabaseInfo/MetaItems.jsx, src/shared/services/utils.js, src/shared/services/utils.test.js
To properly execute Cypher queries with special characters in them, backtick them.
Before: 
MATCH (n:HELLO THERE) RETURN n LIMIT 25
After:
MATCH (n:`HELLO THERE`) RETURN n LIMIT 25
Prior art: https://github.com/neo4j/neo4j-browser/blob/2.0/app/scripts/controllers/Sidebar.coffee#L146-L151
=> Backtick meta items in auto generated queries from drawer

src/shared/services/bolt/bolt.js
All users have access to `CALL dbms.procedures()` and if they're in "must change pw" mode, the "Update pw" fields shows.
Related server change: https://github.com/neo4j/neo4j/pull/9302
=> Fix login for restricted users

src/browser/modules/Stream/Queries/QueriesFrame.jsx
Property name have changed from `query.elapsedTime ` -> `query.elapsedTimeMillis` and the type have changed to be neo4j integers.
=> Fix broken elapsed time in :queries frame

src/browser/modules/Stream/CypherFrame.jsx, src/shared/services/bolt/bolt.js, src/shared/services/bolt/boltMappings.js
Accumulate **db hits** in a query plan when profiling and present them in PROFILE View as below.
=> Present total db hits and time stats in PROFILE View

src/browser/modules/Stream/Auth/ConnectedView.jsx, src/browser/modules/Stream/Auth/ServerStatusFrame.jsx, src/browser/modules/Stream/Stream.jsx, src/shared/modules/commands/helpers/server.js, src/shared/modules/connections/connectionsDuck.js, src/shared/modules/dbMeta/dbMetaDuck.js
The frame showing server status which is called by ':server status'
It presents information about connected user (only if authentication enabled), either authentication is enabled (dbms.security.auth_enabled) and connection credentials are stored in the local storage (browser.retain_connection_credentials=false)
=> Server status frame implementation

src/shared/services/utils.js, src/shared/services/utils.test.js
MATCH(:`Label`Backtick`)
// to
MATCH(:`Label``Backtick`)
=> Escape backticks in meta item queries

src/browser/modules/Stream/FrameTitlebar.jsx, src/browser/modules/Stream/styled.jsx
Don't go `<li><li>xxx</li></li>`. Inner `<li>` should be wrapped by an `<ul>`.
=> Fix for sensitive dropdown menu closing too easy

src/browser/modules/Stream/FrameTitlebar.jsx
Actually makes the guides (carousel) look worse. But there's a card for that.
=> Add fullscreen ability to guide frames

src/browser/modules/Stream/styled.jsx
But do keep the line wrapping of long messages.
Before:
After:
=> Fix indicator being at start of line in error messages

src/browser/modules/Sidebar/Settings.jsx, src/shared/modules/settings/settingsDuck.js, src/shared/modules/stream/__snapshots__/streamDuck.test.js.snap, src/shared/modules/stream/epics.test.js, src/shared/modules/stream/streamDuck.js, src/shared/modules/stream/streamDuck.test.js, src/shared/rootEpic.js
Will not affect pinned frames.
I separated the epic tests from reducer tests because I think it gets messy with both of them in the same file.
=> Listen for config maxFrames and enforce that limit in stream

src/shared/modules/commands/commandsDuck.js, src/shared/modules/commands/postConnectCmdEpic.test.js, src/shared/services/commandUtils.js, src/shared/services/commandUtils.test.js
They are assumed to be splitted by semicolon.
I had to refactor some in the tests files to have the tests running as expected. There seems to be a bug in either `configureMockStore` or `createEpicMiddleware`.
=> Add support for handling multiple commands from browser.post_connect_cmd

src/browser/modules/DatabaseInfo/DatabaseInfo.jsx, src/browser/modules/DatabaseInfo/MetaItems.jsx, src/browser/modules/DatabaseInfo/styled.jsx
Feature ported from `2.0` to not slow down the opening of drawer when connected to databases with a large amount of meta items.
Let the parent feed item listing component what to show to keep the listing components lightweight.
=> Limit number of meta items shown in db drawer

package.json, src/browser/modules/Stream/PlayFrame.jsx, src/shared/modules/commands/commandsDuck.js, src/shared/modules/commands/helpers/play.js, src/shared/modules/dbMeta/__snapshots__/dbMetaDuck.test.js.snap, src/shared/modules/dbMeta/dbMetaDuck.js, src/shared/rootEpic.js, src/shared/services/commandInterpreterHelper.js, src/shared/services/remote.js, src/shared/services/utils.js, src/shared/services/utils.test.js
When trying to play a local guide: `:play reco` and it isn't found, an attempt to find it on the url `browser.remote_content_hostname_whitelist + name` is made.
`browser.remote_content_hostname_whitelist` is a server configuration list of hosts (or urls:s) that the browser can fetch remote content from.
The default value for `browser.remote_content_hostname_whitelist` is `localhost,guides.neo4j.com`, so the above play command would resolve and display the reco guide hosted on https://localhost/reco, then on http://localhost/reco, then on https://guides.neo4j.com/reco and finally on http://guides.neo4j.com/reco.
It stops after the first successful fetch.
The steps followed are:
- Try locally. If found, display it
- Try remotely, by appending the guide name to each of server config list of …
=> Try to fetch guide remotely if not found locally

src/browser/modules/Stream/HelpFrame.jsx, src/shared/services/commandUtils.js, src/shared/services/commandUtils.test.js
Fixes topics with space i.e. `:help rest get` error
changelog: Fix :help input with space
=> Transform :help topic input correctly

src/browser/components/Directives.jsx
Replicate the old functionality where an `<input/>.value()` can be bound to part of a guide.
E.g (`<input value-for="foo"/>`) -[:BINDS_TO]-> (`<span value-key="foo"></span>`)
The feature in action:
=> Add 'Directive' to bind input field values to the guide content

__mocks__/neo4j.js, src/shared/services/bolt/boltMappings.js, src/shared/services/bolt/boltMappings.test.js
When extracting graph items from result only the first level was checked. This fixes that so we recursively check the complete response and extract all items.
Consider the query (on the movie dataset):
```
MATCH (p:Person{name:'Keanu Reeves'})-[:ACTED_IN]->(m:Movie)
RETURN p, collect(m)
```
Before:
After:
Fixes #528
=> Fix for collected graph items now showing up in viz

src/shared/modules/app/appDuck.test.js, src/shared/rootReducer.js, src/shared/services/commandInterpreterHelper.js, src/shared/services/remote.js, src/shared/services/remoteUtils.js, src/shared/services/remoteUtils.test.js
If a requested url matches any of these criterias, the `Authorization` header will be added to requests from the commands `:GET`, `:POST` etc.
1. is local url (no host defined, i.e. `:GET /db/data`)
1. has same host (protocol, hostname, port) as from where the browser is hosted ( i.e. `:GET http://localhost:7474/db/data/` from a browser host on `http://localhost:7474`)
1. has the same hostname as the active database connection (i.e. `:GET http://localhost:7474/db/data/` from a browser which is connected to Neo4j on `bolt://localhost:7687`)
(the reason we need (2) above is because the bolt host can be different from the host where the browser is served from even though it's the same machine)
Open the web browsers dev tools, network tab.
- `:GET /hello` - Should include authorization …
=> Add http auth header on :GET, :POST etc requests when appropriate

src/browser/modules/Editor/Editor.jsx, src/browser/modules/Sidebar/Settings.jsx, src/shared/modules/settings/settingsDuck.js
Simple checkbox in settings drawer to toggle the status for editor autocompletion/suggestions.
=> Add config to disable automatic editor autocomplete (default on)

package.json, src/browser/components/buttons/index.jsx, src/browser/modules/ClickToCode/__snapshots__/index.test.js.snap, src/browser/modules/D3Visualization/components/styled.jsx, src/browser/modules/Editor/styled.jsx, src/browser/modules/Main/styled.jsx, src/browser/modules/Stream/styled.jsx, yarn.lock
Reverts neo4j/neo4j-browser#558
=> Revert "Upgrade styled-components to v2"

src/shared/modules/credentialsPolicy/credentialsPolicyDuck.js, src/shared/services/utils.js, src/shared/services/utils.test.js
Applies to server config `browser.credential_timeout`
When receiving values from JMX, the units default is `s`. 
So entering `browser.credential_timeout=60` in the server config will give `browser.credential_timeout=60` when fetching from JMX.
When parsing JMX values:
No unit => x * 1000 (seconds assumed)
ms => x
s => x * 1000
m => x * 60 * 1000
=> Parse server config duration strings correctly

src/browser/modules/DatabaseInfo/DatabaseKernelInfo.jsx, src/shared/modules/dbMeta/__snapshots__/dbMetaDuck.test.js.snap, src/shared/modules/dbMeta/dbMetaDuck.js, src/shared/modules/dbMeta/dbMetaDuck.test.js
Bring back valuable info to the db drawer.
OBS: The role query cannot be part of the regular dbmeta query because if the db isn't in a cluster the whole query fails, making the sidebar empty.
Connected:
Disconnected:
In a cluster:
=> Add cluster role, db filename and total store size to sidebar

src/shared/modules/commands/commandsDuck.test.js, src/shared/modules/commands/helpers/config.js, src/shared/modules/settings/__snapshots__/settingsDuck.test.js.snap, src/shared/modules/settings/settingsDuck.js, src/shared/modules/settings/settingsDuck.test.js, src/shared/services/commandInterpreterHelper.js, src/shared/services/remote.js
This introduces the ability for a client to be configured by passing an URL to the `:config` command, like: `:config https://oskarhane-dropshare-eu.s3-eu-central-1.amazonaws.com/conf-GHrEFakccy/conf.json`
If successfully found config params, the `:config` frame shows up with the new config in it (just as before).
If any error occurs, an error banner shows up below the editor (new feature introduced with styling support).
Two questions that comes up are:
1. Should we restrict fetching hosts to only those in the whitelist? The `:style` command has no restriction on this.
1. Should we replace the current config, or merge as we do in the current state of this PR? We replace the `:style` when fetching a new one. We also replace all params when `:params {x:2}`.
@akollegger @pe4cey ^^
User input …
=> Introduce fetching client configuration from a remote JSON file

src/browser/modules/App/App.jsx, src/browser/modules/DocTitle/titleStringBuilder.js, src/browser/modules/DocTitle/titleStringBuilder.test.js
Fixes issue where undefined is being displayed in the browsers title bar when authentication is disabled in Neo4j
=> Only display truthy connection data in the browser title

src/shared/modules/dbMeta/dbMetaDuck.js
Limited to 1000 per meta type (labels/propertyKeys/relationshipTypes)
Fixes issue of storing large amounts of meta items in state
changelog: Fix sluggish experience when having hundreds of thousands meta items
=> Limit meta data items returned by the cypher query

package.json, src/shared/modules/commands/commandsDuck.test.js, src/shared/modules/commands/helpers/config.js, src/shared/modules/commands/helpers/config.test.js, yarn.lock
Add ability to accept setting browser configs with a JSON string, like: `:config {"maxFrames":50, "theme": "outline"}` or the more related format like: `:config {maxFrames: 50, theme: "outline"}`
When setting config with an JSON object string, the current config is being **replaced** (merged with the default values) **not updated** as the case when setting single config values.
Helpful hints are displayed below the editor to enlighten users if something goes wrong.
=> Add support for setting browser `:config` with objects

src/shared/modules/commands/commandsDuck.test.js, src/shared/services/commandInterpreterHelper.js
In it's simplest form, outputting the style data into a `<pre>` frame.
To "edit", users can copy the json, edit it locally och upload a file with the new styling (or upload it somewhere and use `:style http://myurl.com/grass.json`.
Fixes #562
=> Bring back `:style` command

src/shared/modules/commands/helpers/grass.js, src/shared/modules/commands/helpers/grass.test.js, src/shared/services/commandInterpreterHelper.js
The url param when loading remote grass using `:style` needs to be present in the whitelist returned by the neo4j server
=> Honor url whitelist when fetching remote grass files

src/shared/modules/history/historyDuck.js, src/shared/modules/history/historyDuck.test.js
Fix regression where repeated commands were added to history multiple times.
=> Don't add repeated executed commands to history

__mocks__/neo4j.js, src/shared/services/bolt/boltMappings.js, src/shared/services/bolt/boltMappings.test.js
In the code a path assumed to have segments. That assumption is wrong, a path can be of zero length and just be a node.
To illustrate, load movie dataset and run this query before and after this fix:
```
MATCH path=(n:Person)-[*0]-()
WHERE n.name='Keanu Reeves' 
RETURN path
```
Nothing is displayed in viz or table view. When viewing the response in the code view it's clear that we get a node back.
**For the reviewer**: I have tested this manually many times for different kinds of path queries and found no regressions. Please do so you as well. 
There were no existing tests covering object extraction from paths.
Fixes #351
=> Fix display of zero length paths

src/browser/modules/Stream/CypherFrame/PlanView.jsx
This is so each plan view will have access to it's own plan class (as opposed to a global singleton)
=> Instantiate NeoConstructor in plan view

__mocks__/neo4j.js, src/browser/modules/Stream/CypherFrame/AsciiView.jsx, src/browser/modules/Stream/CypherFrame/TableView.jsx, src/browser/modules/Stream/CypherFrame/helpers.js, src/browser/modules/Stream/CypherFrame/helpers.test.js, src/browser/modules/Stream/CypherFrame/index.jsx, src/shared/services/bolt/bolt.js, src/shared/services/utils.js, src/shared/services/utils.test.js
This regression was introduced with the cypher frame refactoring.
Rather than filling up `boltMappings` with more functions I decided to place the mappings and transforms close to where they are used.
Opens for code duplication, but makes the code more safe to make changes to.
Fixes #618
=> Fix display of Neo4j integers in Cypher result frames

src/browser/modules/Stream/CypherFrame/index.jsx, src/browser/modules/Stream/FrameTitlebar.jsx
Changes to Cypher results frame:
- Only show download png in titlebar when in visualization view
- Hide download csv in titlebar when in visualization view
=> Fix png download

src/browser/modules/Stream/styled.jsx
=> Fix x overflow in frames with %-width in IE 11

src/browser/modules/Stream/CypherFrame/PlanView.jsx, src/browser/modules/Stream/CypherFrame/index.jsx, src/browser/modules/Stream/FrameTitlebar.jsx, src/shared/services/exporting/pngUtils.js, src/shared/services/exporting/svgUtils.js
In the cypher result frame for `EXPLAN||PROFILE` query we display the `plan` view that has an interactive query plan element. 
This PR adds a button in the titlebar to download the query plan as a png file.
=> Add ability to download a query plan as png

src/browser/modules/Guides/html/movie-graph.html
The example query to select movies from the nineties excludes any movies release in 1990, causing it to miss `Joe Versus the Volcano` in the results.
=> Correct query to select movies from the nineties

src/browser/modules/D3Visualization/components/Inspector.jsx
I have to hunt down where my properties are in the inspector a lot. I assume others do, too. Cmd-F isn't the most friendly tool in this view, so this should help improve that experience. :-)
Since there are usually very few properties shown in the inspector (a few dozen?) the performance impact should be negligible.
=> Sort keys when inspecting nodes

src/browser/modules/DatabaseInfo/MetaItems.jsx, src/browser/modules/DatabaseInfo/MetaItems.test.js
Only give first items special query (match any)
=> Fix wrong query generated for user graph items named ‘*’

.babelrc, .eslintignore, .eslintrc.json, package.json, src/browser/modules/App/App.jsx, webpack.config.js, yarn.lock
We keep the standard config. 
Nothing will change style wise, we just use `eslint` directly rather than going through `standard`.
Move to `prettier-eslint` as well.
The point of this is to being able to configure the linting rules and plugins in a simpler way.
With this commit we also bring in babel support for `stage-2` proposals so we don’t explicitly need to bring in `"transform-object-rest-spread"` and `”babel-plugin-transform-class-properties”` which is why I started this in the first place.
It's very common in the React community to use class properties and I like the patter so I think we should start using it (no need to change what we already have though, but for anything new).
When (if) this goes in, you probably need to configure your IDE:s to use eslint instead go standard. …
=> Remove standard and bring in eslint

package.json, src/shared/services/bolt/boltConnection.js, yarn.lock
No need to close an errored driver (this removes a js error message).
=> Update neo4j-driver to 1.4.0

package.json, src/browser/modules/Editor/Editor.jsx, yarn.lock
Changes:
Errors in console commands are suppressed. Therefore autocompletion & syntax highlight is enabled now for console commands
Add schema-based parameter autocompletion
Fixed various Cypher parser bugs
This replaces https://github.com/neo4j/neo4j-browser/pull/615
changelog: Fix various bugs in editor Cypher parsing
=> Upgrade cypher-codemirror to 1.0.5

src/shared/modules/cypher/cypherDuck.js
This fixes an issue when using officially signed certificates on a newly installed Neo4j when setting up initial password.
For some reason browsers are ok with opening an unsecure websocket on a "secure" website if it's a manually trusted self signed certificate. But I won't open an unsecure websocket from a website on a officially signed cert.
That made this quite hard to find, but https://github.com/neo4j/neo4j-browser/issues/522#issuecomment-332502755 pointed me in the right direction.
This can be verified (that an unsecure websocket is opened) by looking in the network tab in chrome on a newly installed neo4j when setting the initial password.
With these changes, all opened websockets are secure.
Changelog: Fix setting initial password over officially trusted TLS certificates
=> Pass encryption mode when force changing password

src/shared/services/bolt/boltMappings.js, src/shared/services/bolt/boltMappings.test.js
- Re-enable skipped boltMapping tests
Before:
After:
=> Remap query plan arguments to the root object

src/browser/modules/Editor/Editor.jsx, src/shared/modules/favorites/favoritesDuck.js, src/shared/modules/favorites/favoritesDuck.test.js
This pr puts the editor in 'update favorite' mode. Subsequent changes will reference the favorite that has been created. Clicking on the 'pen' icon will update the newly added favorite.  
In action: ![add-fav-feedback](https://user-images.githubusercontent.com/849508/31545532-be60be62-b017-11e7-8f26-5b75a95c1fdc.gif)
=> Set editor to update mode after adding a new favorite

src/browser/modules/Stream/FrameTitlebar.jsx, src/shared/services/exporting/imageUtils.js, src/shared/services/exporting/svgUtils.js
The download button is visible in cypher results frame titlebar when the visualization tab is selected
=> Add button to download vis as svg

src/browser/components/buttons/ConfirmationButton.jsx, src/browser/components/buttons/style.css, src/browser/components/icons/Icons.jsx, src/browser/modules/Sidebar/Favorite.jsx, src/browser/modules/Sidebar/Folder.jsx, src/browser/modules/Sidebar/styled.jsx
Reuses existing `<ConfirmationButton />` component
=> Add button to confirm the deletion of favorites and folders

package.json, src/browser/components/DesktopIntegration/helpers.js, src/browser/components/DesktopIntegration/helpers.test.js, src/browser/components/DesktopIntegration/index.jsx, src/browser/components/DesktopIntegration/index.test.js, src/browser/index.jsx, src/browser/modules/App/App.jsx, src/browser/modules/Stream/Auth/ConnectedView.jsx, src/browser/modules/Stream/Auth/ConnectionForm.jsx, src/browser/modules/Stream/Auth/ServerSwitchFrame.jsx, src/browser/modules/Stream/Stream.jsx, src/shared/modules/app/appDuck.js, src/shared/modules/commands/helpers/server.js, src/shared/modules/connections/connectionsDuck.js, src/shared/modules/connections/connectionsDuck.test.js, src/shared/modules/discovery/discoveryDuck.js, src/shared/modules/discovery/discoveryDuck.test.js, src/shared/rootEpic.js, src/shared/services/bolt/boltHelpers.js, src/shared/services/testUtils.js
We added the `DesktopIntegration` component which reads initial context and sets up a listener for events that the desktop att emits.
To react on events happening you attach props to the component in the form of `EVENT_NAME` -> `onEventName`.   
Example on react on `DATABASE_STARTED` -> 
```javascript
<DesktopIntegration 
integrationPoint={window.neo4jDesktopApi} 
onDatabaseStarted={(event, newContext, oldConext) => alert(event.type)}  
/>
```
To get the initial context on app load, you attach the 
```javascript
onMount={(activeGraph, boltCredentials, fullContext) => alert(activeGraph.id)}
```
In web env, no changes are expected.
In desktop env, this should be the behaviour:
**When browser is opened when a graph already is running:**
- Get host + port from desktop api and populate the …
=> Integrate with desktop API

src/browser/modules/App/App.jsx, src/browser/modules/Main/Main.jsx, src/browser/modules/Main/SyncConsentBanner.jsx, src/browser/modules/Sidebar/Sidebar.jsx, src/shared/modules/features/featuresDuck.js, src/shared/modules/features/featuresDuck.test.js, src/shared/modules/sync/syncDuck.js
Show new banner with a button to toggle sidebar for easy and visible access for new users.
This will only be shown if users not yet have accepted terms and not opted out (closed banner).
Feature toggle for Sync added as well for better code branching.
Still disabled in desktop env.
=> Show new sync banner when not accepted terms yet

src/browser/modules/D3Visualization/components/Explorer.jsx
This removes a conditional statement in the Explorer that tries to access an `undefined` part of the component state.
Resolves https://github.com/neo4j/neo4j-browser/issues/646
=> Fix issue where mapping cypher result to vis would break the app

README.md, package.json
Fix for https://github.com/neo4j/neo4j-browser/issues/514
This gives a Windows start option "startnodash" which bypasses an issue where spawning webpack-dev-server via webpack-dashboard fails. It simply starts webpack-dev-server directly. There is also a small update to the readme to indicate to Windows users how to start via Yarn.
This is should not have any impact on existing code as it is only adding a new start option.
=> Yarn startnodash

src/browser/modules/Sync/BrowserSync.jsx, src/shared/modules/grass/grassDuck.js, src/shared/modules/sync/syncDuck.js, src/shared/rootEpic.js
Fixes a known regression where users' grass files are no longer syncs with the neo4j browser sync service.
=> Persist grass to neo4j sync

src/browser/components/DesktopIntegration/helpers.js, src/browser/components/DesktopIntegration/helpers.test.js, src/browser/modules/App/App.jsx, src/shared/modules/discovery/discoveryDuck.js, src/shared/services/commandInterpreterHelper.js
Populates the `restApi` property of the connection obj when using Neo4j Desktop. 
The value is consumed when the user passes a path to one of the http verb Browser commands. E.g. `:get /foobar` will call `${restApi}/foobar`
=> Fix http request issue when using Desktop

src/browser/modules/Editor/Editor.jsx, src/browser/modules/Sidebar/Settings.jsx
=> Disable cypher syntax highlighting based on editorAutocomplete setting

src/browser/modules/Main/SyncConsentBanner.jsx, src/browser/modules/Main/SyncReminderBanner.jsx
A small update to the Neo4j Browser Sync banner.
- Update message
- Move drawer open button in to the main text area
From:
To:
=> Update content for Neo4j Browser Sync banner

src/browser/modules/Stream/CypherFrame/ErrorsView.jsx, src/browser/modules/Stream/Errors/IESecurityErrors.jsx, src/browser/modules/Stream/errorMessageFormater.js, src/browser/modules/Stream/errorMessageFormater.test.js
This adds a new error mapping layer to the ui so we are able to return jsx with more information about known Web Browser + Neo4j Browser issues.
E.g Internet Explorer 11 can cause a generic looking `Security Error: 18` message when using Bolt. With this change the error now advises a user how to fix the issue
=> Add more detailed error messages for known Browser/OS issues

src/shared/modules/dbMeta/dbMetaDuck.js, src/shared/modules/jmx/jmxDuck.js, src/shared/modules/jmx/jmxDuck.test.js, src/shared/rootEpic.js, src/shared/rootReducer.js, src/shared/services/bolt/boltHelpers.js
Populates state with the latest jmx values so that we don't have to hit the server every time jmx attributes are read.
_JMX values are refreshed at the same interval as metadata requests_
Before:
After:
=> Optimise fetching/reading jmx information

src/browser/modules/Stream/SysInfoFrame/sysinfo.js
This updates `:sysinfo` to display `Store sizes` from jmx rather than `Store file sizes` (deprecated).
To maintain backwards compatibility we first map `Store files sizes` and the then override those values with `Store sizes` (also retains `Logical Log` value as it is not available in `Store sizes`)
=> Update :sysinfo to display 'Store sizes' jmx values

src/browser/modules/Editor/Codemirror.jsx, src/browser/modules/Editor/Editor.jsx, src/browser/modules/Editor/styled.jsx, src/browser/styles/constants.js
What’s done here are basically two things:
1. Don’t re-render for state changes that has no UI effect (through `shouldComponentUpdate `)
2. Instead of measuring the height and adjust on `componentDidUpdate`, change CM event listener from `change` to `changes` which is triggered after DOM has been updated. State will update and trigger a re-render only on height changes.
This should have a positive performance impact on the editor.
=> Less re-renders for editor

src/shared/modules/commands/commandsDuck.js
This change replaces `zip` from the `postConnectCmdEpic` with `concat`.
The usage of _`zip` (in this epic) was storing the complete history of the action stream and causing a memory leak._
=> Fix issue where action stream was being stored in memory

src/browser/modules/Stream/SysInfoFrame/index.jsx
Add page cache hit ratio to :sysinfo frame.
_Restricts the value returned from `queryJmx` to two decimal places_
=> Add page cache hit ratio to :sysinfo frame

src/shared/modules/commands/helpers/cypher.js, src/shared/modules/cypher/cypherDuck.js, src/shared/modules/dbMeta/dbMetaDuck.js, src/shared/modules/features/featuresDuck.js, src/shared/modules/jmx/jmxDuck.js, src/shared/services/bolt/bolt.js, src/shared/services/bolt/boltConnection.js, src/shared/services/bolt/boltWorker.js, src/shared/services/bolt/boltWorkerMessages.js
Refactor the worker initialisation to not be bound to (routed) write transactions, but to accept (routed) read transactions as we as (non routed read) direct transactions.
All cypher queries get's sent through this with this change except the `bolt.directConnect` which is used to create a persistent driver.
The benefit is that no background queries will have any effect on UI fps.
=> Make every type of Bolt transactions use web workers

src/browser/components/icons/Icons.jsx, src/browser/modules/Stream/SysInfoFrame/index.jsx
=> Add more info icon when running `:sysinfo` on a cc member

src/browser/modules/Stream/CypherFrame/CodeView.jsx, src/browser/modules/Stream/CypherFrame/CodeView.test.js, src/browser/modules/Stream/styled.jsx
- Displays `summary` from driver response in the cypher frame code view.
- Adds expand/collapse functionality to the `response` and `summary` properties
=> Display driver result summary in code view

e2e_tests/integration/index.spec.js, e2e_tests/support/commands.js, e2e_tests/support/index.js, package.json, src/browser/modules/Stream/FrameTemplate.jsx
Added helper functions as well.
This was actually part of https://github.com/neo4j/neo4j-browser/pull/722 but I don't want that PR to block this part since I want to add more tests.
It's easier to run e2e tests on your local machine now. Have a db with the password `newpassword` and run:
```
yarn e2e-local
```
To open `cypress` UI (useful when adding tests) you can run:
```
yarn e2e-local-open
```
**Warning, your db will be emptied when running these tests**
=> Refactor and make e2e test more isolated

src/browser/modules/Stream/SysInfoFrame/index.jsx
We forgot four sizes when we added these last time.
When they don't exist (< neo4j 3.2)
When they exist:
=> Display more store sizes if they exist (> neo4j 3.2)

src/browser/modules/Stream/CypherFrame/WarningsView.jsx, src/browser/modules/Stream/CypherFrame/WarningsView.test.js
Don’t strip ‘EXPLAIN’ and use 'offset' instead of 'column'.
=> Fix Cypher warning position in Warnings View

e2e_tests/integration/index.spec.js, src/browser/modules/Stream/CypherFrame/ErrorsView.jsx, src/browser/modules/Stream/FrameTemplate.jsx, src/shared/modules/connections/connectionsDuck.js, src/shared/modules/dbMeta/dbMetaDuck.js, src/shared/services/bolt/bolt.js, src/shared/services/bolt/boltConnection.js, src/shared/services/bolt/boltWorker.js, src/shared/services/bolt/boltWorkerMessages.js
E2E test added for the error message.
This PR also fixes the ugly error message in server log when we try to connect without a scheme when checking if auth is off.
Empty username + pw ensures the same thing, but without the error message.
And one more thing in this pr: when using web workers, a connection loss wasn't showing the 'Connection to server lost, reconnecting...' banner.
=> Detect connection loss and display error message + show retry banner

README.md, e2e_tests/integration/params.spec.js, e2e_tests/integration/types.spec.js, e2e_tests/support/defaults.js
This pr reads in the `server` arg passed to `yarn e2e*` to only run test associated with that server version.
E.g. Neo4j server 3.3 does not support `data()` cypher function. By running `yarn e2e --env server=3.3` the test that exec these statements will be skipped
_If no version is set it falls back to the default 3.4 value_
=> Server version specific e2e tests

package.json, src/browser/modules/Sidebar/Documents.jsx, src/browser/modules/Sidebar/docsUtils.test.js
Default to ‘current’ if not db version is available or invalid.
=> Fix docs links in sidebar to point to the connected version

e2e_tests/integration/plan.spec.js, src/browser/external/neoPlanner.js
Fixes bug where 'Expressions' parameter was not being mapped correctly from cypher response
_Note: See 'projection'_
---
Before:
---
After:
=> Map 'Expressions' arguments from profile/explain

src/shared/services/utils.js, yarn.lock
All available except codemirror and cypher-codemirror.
```
babel-core@6.26.3
css-loader@0.28.11
eslint@4.19.1
eslint-plugin-import@2.12.0
eslint-plugin-react@7.8.2
eslint-plugin-standard@3.1.0
nock@9.2.6
postcss@6.0.22
postcss-loader@2.1.5
webpack@3.12.0
webpack-bundle-analyzer@2.13.0
dnd-core@2.6.0
file-saver@1.3.8
firebase@4.13.1
preact@8.2.9
react-dnd@2.6.0
react-dnd-html5-backend@2.6.0
react-dropzone@4.2.10
react-icons@2.2.7
rxjs@5.5.11
styled-components@3.2.6
url-parse@1.4.0
```
=> Dependencies update

src/browser/modules/DatabaseInfo/styled.jsx
=> Word break long values in db info drawer

e2e_tests/integration/types.spec.js, src/shared/services/bolt/applyGraphTypes.test.js, src/shared/services/bolt/boltMappings.js, src/shared/services/utils.js
Due to `Path`'s start / end nodes being references to the `PathsSegment`'s first and last node they was encoded twice and weird happened.
Since this is an implementation detail in the driver and might change in the future, I secured it by checking before adding types.
changelog: Fix [object Object] output when returning paths with new types
=> Make sure path start / end nodes aren’t "type stamped" twice

src/browser/modules/Stream/AutoRefresh/styled.jsx, src/browser/modules/Stream/AutoRefresh/toggleStyles.css, src/browser/modules/Stream/Queries/QueriesFrame.jsx, src/browser/modules/Stream/Queries/styled.jsx, src/browser/modules/Stream/SysInfoFrame/index.jsx
- Adds manual refresh button to re-fetch data
- Adds auto refresh button to status bar (20 seconds refresh rate)
_Capture notes: Auto refresh interval set to 2 seconds for demo purposes. Background cypher is being executed to increase 'Node ID' value_
=> Add auto refresh to sysinfo frame

package.json, yarn.lock
Release notes: https://github.com/FormidableLabs/webpack-dashboard/releases/tag/v2.0.0
Should be faster and have broader OS support.
=> Update webpack-dashboard to 2.0.0

src/browser/modules/D3Visualization/components/Inspector.jsx, src/browser/modules/D3Visualization/mapper.js, src/shared/services/utils.js, src/shared/services/utils.test.js
Previously the visualisation would throw an error that would cause the render to break
=> Visualization: Avoid calling 'toString' on empty objects

src/browser/modules/D3Visualization/components/Graph.jsx, src/browser/modules/D3Visualization/components/styled.jsx, src/browser/modules/Stream/CypherFrame/VisualizationView.styled.jsx
Fixes issue where expanding inspector would force the status bar content out of the viewport.
See #682 
Before:
After:
=> Fix missing inspector items when spread over more than one line

src/browser/modules/Stream/CypherFrame/AsciiView.jsx, src/browser/modules/Stream/CypherFrame/helpers.js, src/browser/modules/Stream/CypherFrame/helpers.test.js, src/browser/modules/Stream/CypherFrame/index.jsx, src/shared/services/bolt/cypherTypesFormatting.js
The reformatting of results display mistakenly followed along to the CSV export. This fixes that.
The extra quotes in the CSV file headers comes from the drivers `keys` field and are not added by us and is not part of this regression.
Test query: `RETURN "string, yo", "yo", 1, 1.0, true`
```
"""""string, yo""""","""""yo""""","""1""","""1.0""","""true"""
"""string, yo""","""yo""",1,1.0,true
```
```
"""string, yo""","""yo""",1,1.0,true
"string, yo",yo,1,1.0,true
```
=> Don’t add type hinting quotes on strings in CSV export

package.json, src/browser/modules/Stream/CypherFrame/index.jsx, src/browser/modules/Stream/FrameTemplate.jsx, src/browser/modules/Stream/FrameTitlebar.jsx, yarn.lock
With this PR we skip constructing and passing a complete copy of the returned data from every query to the children of `CypherFrame`. Not everyone exports so it's often an unnecessary operation and also slows down rendering of CypherFrame's other view.
This is now done on demand.
We need to pass down something (`numRecords`) to indicate that we have a result so the export button will show at all when query state goes from 'pending' -> 'completed' so the children of CypherFrame re-renders.
Not sure about the real performance impact since it depends on the amount of data the queries return.
But is has no downside. 
Tested and verified in Chrome, FF, Safari on macOS and IE11, Edge on Windows 10.
=> Refactor CSV export data contruction

e2e_tests/integration/style.spec.js, src/browser/components/icons/Icons.jsx, src/browser/modules/Sidebar/FileDrop.jsx, src/browser/modules/Stream/FrameTitlebar.jsx, src/browser/modules/Stream/InfoView.jsx, src/browser/modules/Stream/Stream.jsx, src/browser/modules/Stream/StyleFrame.jsx, src/browser/modules/Stream/styled.jsx, src/browser/styles/themes.js, src/shared/modules/commands/commandsDuck.test.js, src/shared/modules/commands/helpers/grass.test.js, src/shared/services/commandInterpreterHelper.js, src/shared/services/grassUtils.js, src/shared/services/grassUtils.test.js
- Output `:style` in the form of GraSS and not JSON
- Download / Export GraSS from `:style` frame
- Reset style from `:style` frame in bottom right corner
```css
node {
diameter: 50px;
color: #A5ABB6;
border-color: #9AA1AC;
border-width: 2px;
text-color-internal: #FFFFFF;
font-size: 10px;
}
relationship {
color: #A5ABB6;
shaft-width: 1px;
font-size: 8px;
padding: 3px;
text-color-external: #000000;
text-color-internal: #FFFFFF;
caption: "<type>";
}
node.Movie {
color: #68BDF6;
border-color: #5CA8DB;
text-color-internal: #FFFFFF;
caption: "{title}";
}
```
=> Fix :style / GraSS regressions

src/shared/modules/dbMeta/dbMetaDuck.js, src/shared/rootEpic.js
Let all dbMeta data mapping items that rely on data from JMX wait for the JMX data before they run.
Since the JMX values update every 20 secs, the epic is straight forward.
Hard to test / validate the race condition, so I'll skip that.
=> Fix race condition with data from jmx

README.md, e2e_tests/integration/0.index.spec.js, e2e_tests/integration/bolt.spec.js, e2e_tests/support/commands.js, e2e_tests/support/index.js, src/browser/modules/Main/Main.jsx, src/shared/modules/connections/connectionsDuck.js, src/shared/services/bolt/boltConnection.js
We only want to show the 'reconnect' banner when an active connection breaks.
The current behavior is that the banner show when you're trying to connect to something that doesn't exists. 
I also did some e2e test refactoring as part of this PR to simplify writing tests. Also added more e2e info to README.
=> Don't show reconnect banner when connecting, only when an active connection breaks

src/browser/modules/DatabaseInfo/DatabaseInfo.jsx, src/browser/modules/DatabaseInfo/MetaItems.jsx, src/shared/modules/dbMeta/__snapshots__/dbMetaDuck.test.js.snap, src/shared/modules/dbMeta/dbMetaDuck.js, src/shared/modules/dbMeta/dbMetaDuck.test.js
Count the number of nodes and relationships on every db-meta update.
Display like we do in the viz legend.
=> Show number of nodes and relationships in db sidebar

src/browser/modules/Sidebar/About.jsx
Fixes issue where app would crash when opening `About` drawer whilst disconnected from neo4j
=> Handle changelog url building in disconnected state

package.json, src/browser/components/ErrorBoundary.jsx, src/browser/components/buttons/index.jsx, src/browser/init.js, src/browser/modules/App/App.jsx, src/browser/modules/Main/Main.jsx, src/browser/modules/Stream/CypherFrame/__snapshots__/PlanView.test.js.snap, src/browser/modules/Stream/StyleFrame.jsx, yarn.lock
using componentDidCatch in strategic places to stop the application from a total unmount (white blank screen).
- Top level App
- Editor
- Stream
- Sidebar
Added a reload button with the error message. Colors come from console errors in Chrome.
=> Add React error boundaries

e2e_tests/integration/multistatements.spec.js, src/browser/modules/Sidebar/Settings.jsx, src/shared/modules/commands/commandsDuck.js, src/shared/modules/commands/multiCommands.test.js, src/shared/modules/settings/__snapshots__/settingsDuck.test.js.snap, src/shared/modules/settings/settingsDuck.js
Adds new toggle `Enable multi statement query editor` (in settings drawer) for enabling/disable multi statement query handling in the cypher editor
=> Add toggle for multi statement cypher editor

src/browser/modules/Stream/SysInfoFrame/index.jsx
- Updates cc member url displayed on the `:sysinfo` frame
- If served up from `file://` then default to `http`
=> Honour current protocol when building url for cc member

e2e_tests/integration/plan.spec.js, src/browser/external/neoPlanner.js, src/shared/services/bolt/boltMappings.js
Show page cache stats right next to hits / estimated row stats.
I also added a E2E test for it.
_(Sorry for the formatting changes, I guess prettier got updated.)_
=> Add pagecache hits and misses to plan output

pom.xml
Previous: 
```
Manifest-Version: 1.0
Package: org/neo4j/client
Archiver-Version: Plexus Archiver
Created-By: Apache Maven x.x.x
Built-By: foobar
Build-Jdk: 10.0.1
```
Now:
```
Manifest-Version: 1.0
Package: org/neo4j/client
Archiver-Version: Plexus Archiver
Created-By: Apache Maven x.x.x
Built-By: foobar
Build-Jdk: 1.8.0_162
```
=> Force jar to be packaged using java 1.8

src/browser/modules/Sidebar/About.jsx
Discussed recently with @jexp, @ryguyrg.   We're soon launching a new community site, and deprecating use of user slack and google group.  This is a tiny PR to reflect that in the about section of Neo4j Browser, and to give the community site first billing above SO.
=> neo4j community forum first support option in "About"

src/browser/modules/Stream/CypherFrame/AsciiView.jsx, src/browser/modules/Stream/CypherFrame/AsciiView.test.js, src/browser/modules/Stream/CypherFrame/PlanView.jsx, src/browser/modules/Stream/CypherFrame/TableView.jsx, src/browser/modules/Stream/CypherFrame/VisualizationView.jsx, src/browser/modules/Stream/CypherFrame/index.jsx, src/shared/modules/requests/requestsDuck.js
Add an `updated` property to the request object and set that every time it’s updated with new data.
This avoids potential expensive `deepEquals` checks on every `shouldComponentUpdate` check.
Seems to speed up rendering of heavy queries by about 20%.
=> Enable cheap updated checks for cypher frame

Dockerfile, now.json, src/shared/modules/commands/helpers/play.js, src/shared/services/remote.js
To make sure content updated remotely always are shown.
These headers should be respected by remote servers.
Before:
After:
changelog: Fetch fresh version of remote guides on every request
=> Send cache busting headers with remote guides requests

src/browser/modules/Editor/styled.jsx
=> Fix issue where editor buttons would overflow the viewport

src/browser/modules/Stream/CypherFrame/WarningsView.jsx
Checks if warning position info exists.
Before:
After:
fixes: #831 
changelog: Fix rare neo4j-browser crash when clicking on yellow Cypher warning triangle
=> Don't assume all Cypher warnings to have position info

e2e_tests/integration/desktop-env-url.spec.js, e2e_tests/support/utils.js, src/browser/modules/App/App.jsx
New addition to Neo4j Desktop API (will be out in 1.1.11).
Keeps backwards compatibility.
Note that these URL:s can have the `bolt+routing` protocol.
changelog: Future proof Neo4j Desktop integration by using the `url` field in connection info.
=> Use `url` field from Neo4j Desktop context if it exists

src/browser/modules/Stream/Queries/QueriesFrame.jsx, src/browser/modules/Stream/Stream.jsx, src/shared/modules/cypher/cypherDuck.js
Issue:
In a causal clustered setup when executing the `:queries` command, the resulting frame displays the records returned from running `call dbms.listQueries` on all cluster members. If the `username` and `password` used on the current session are invalid with any of the other cluster members, the frame would throw an error and cause Neo4j Browser to become unresponsive.
Fix:
Gracefully handle errors from the individual members and display the error to the user. A more detailed error message is displayed as an error row tooltip.
changelog: Fix crashing `:queries` frame in clustered environments when all members couldn't be reached
=> Fix `:queries` frame so that connection errors are displayed

src/browser/index.jsx, src/browser/modules/App/App.jsx, src/browser/modules/FeatureToggle/FeatureToggle.jsx, src/browser/modules/FeatureToggle/FeatureToggle.test.js, src/browser/modules/FeatureToggle/FeatureToggleProvider.jsx, src/browser/modules/FeatureToggle/FeatureToggleProvider.test.js, src/browser/modules/Sidebar/Settings.jsx, src/browser/modules/Sidebar/__snapshots__/Settings.test.js.snap, src/shared/modules/experimentalFeatures/experimentalFeaturesDuck.js, src/shared/modules/experimentalFeatures/experimentalFeaturesDuck.test.js, src/shared/rootReducer.js
This gives us a tool to rollout features that we want to get feedback on before releasing them.
At the same time as it gives users a list of available experimental features to chose from, users understand that they're experimental and can break at any time.
Users toggle the experimental features from the Settings sidebar, at the bottom.
With this PR it's hidden because there are no features to toggle.
Also note that to be able to persist the users settings we store this in the users local storage. However, men we move a feature off of the experimental list, it will still show up in users Settings sidebar if we don't check what should be there. 
That's the reason for the `cherrypickAndMerge` function in the experimental feature duck file.
This is what it looks like with a feature added:
To …
=> Introduce experimental features section in Settings

src/browser/modules/Stream/SysInfoFrame/index.jsx
if `props.label` isn’t there, choose something else as the key
=> Fix React key error

e2e_tests/integration/viz.zpec.js, src/browser/modules/D3Visualization/components/Explorer.jsx, src/browser/modules/D3Visualization/components/Graph.jsx, src/browser/modules/D3Visualization/components/Legend.jsx
Also remove unnecessary and expensive comparisons.
This component unmounts on a frame re-un, so no need to have node checks in cwrp.
We also checked the styling twice. I moved that to a versioning instead.
I also added e2e tests for it.
Before:
After:
=> Fix auto-completed relationships not showing in viz legend on first render

src/browser/modules/Stream/CypherFrame/index.jsx
Reset element and state in pending state.
The export previously referred to a non existing DOM element which resulted in broken images.
=> Fix graph viz image export on re-runned frames

.babelrc, build_scripts/webpack.config.js, src/browser/init.js, src/browser/modules/ClickToCode/__snapshots__/index.test.js.snap, src/browser/modules/Sidebar/__snapshots__/Settings.test.js.snap, src/browser/modules/Stream/CypherFrame/__snapshots__/AsciiView.test.js.snap, src/browser/modules/Stream/CypherFrame/__snapshots__/CodeView.test.js.snap, src/browser/modules/Stream/CypherFrame/__snapshots__/ErrorsView.test.js.snap, src/browser/modules/Stream/CypherFrame/__snapshots__/PlanView.test.js.snap, src/browser/modules/Stream/CypherFrame/__snapshots__/TableView.test.js.snap, src/browser/modules/Stream/CypherFrame/__snapshots__/WarningsView.test.js.snap, src/browser/modules/Stream/__snapshots__/HistoryRow.test.js.snap
This PR fixes an regression that came with the webpack 4 upgrade. 
neo4j-browser rendered completely blank due to a late load of babel-runtime.
What's awesome is that recent changes with dependencies and tooling upgrades also fixes the long stand bug of IE 11 re-rendering / flickering the stream.
Gif for proof.
=> Fix render in IE11

src/browser/index.html
Using the `<noscript>` tag.
fixes: https://github.com/neo4j/neo4j-browser/issues/699
=> Show a helpful message for non js clients

src/browser/modules/Sidebar/Settings.jsx, src/shared/modules/commands/commandsDuck.js, src/shared/modules/commands/commandsDuck.test.js, src/shared/modules/settings/settingsDuck.js, src/shared/modules/settings/settingsDuck.test.js
Also add it to the settings sidebar.
fixes: https://github.com/neo4j/neo4j-browser/issues/780
=> Let the configuration initCmd be empty

src/browser/components/DesktopIntegration/helpers.js, src/browser/components/DesktopIntegration/index.jsx, src/browser/modules/App/App.jsx, src/browser/modules/Stream/Auth/ServerSwitchFrame.jsx, src/browser/modules/Stream/Auth/ServerSwitchFrame.test.js
Only for desktop env.
If neo4j-browser is launched when no graph in neo4j desktop is active the user was left with a blank stream.
This PR shows a connection failed frame.
=> Show message if neo4j-browser is opened without an active graph in a Neo4j Desktop environment

src/browser/modules/D3Visualization/graphStyle.js, src/browser/modules/D3Visualization/graphStyle.test.js, src/shared/services/grassUtils.js, src/shared/services/grassUtils.test.js
Both support for changing the styling through the UI and uploading of grass files.
```
:style reset
CREATE (n:`foo.bar`) RETURN n
// Edit style in the UI through the legend
```
It's aligned with how CSS does it:
```
node {
color: #ffffff;
}
node.foo\.bar {
caption: '{name}';
}
```
fixes: https://github.com/neo4j/neo4j-browser/issues/809
=> Add support for GraSS selectors (node labels and rel types) containing a `.`

README.md, cypress.json, e2e_tests/support/defaults.js, src/shared/modules/commands/commandsDuck.js, src/shared/modules/commands/remoteGuides.test.js, src/shared/modules/dbMeta/dbMetaDuck.js, src/shared/services/utils.js, src/shared/services/utils.test.js
With the `browser.remote_content_hostname_whitelist` config set to `*`, neo4j browser now tries to resolve guides on the default hosts (`guides.neo4j.com, localhost`) so they more easily can be played.
Example: `:play reco` now looks for a guide on (in that order)
```
https://guides.neo4j.com/reco
http://guides.neo4j.com/reco
https://localhost/reco
http://localhost/reco
```
The behavior for configurations of `browser.remote_content_hostname_whitelist` set to anything else should be unchanged.
=> Remote guides - resovle config ’*’ to default whitelist

src/shared/modules/commands/cypher.test.js, src/shared/services/bolt/txMetaData.test.js, src/shared/services/commandInterpreterHelper.js
This format is generic and should be used by all neo4j applications.
Added tests so they break if we update format again (because changing log format = breaking change).
=> New format for tx metadata for logs

src/shared/services/bolt/applyGraphTypes.test.js, src/shared/services/bolt/boltMappings.js
Recursive mutation bug.
See the linked issue for details when this occurred.
Now it takes a few seconds.
fixes: https://github.com/neo4j/neo4j-browser/issues/873
=> Fix (extremely) slow data parsing in certain cases

src/browser/components/DesktopIntegration/index.jsx, src/browser/modules/App/App.jsx, src/shared/modules/app/appDuck.js, src/shared/modules/editor/editorDuck.js, src/shared/modules/editor/editorDuck.test.js
Hook into `integrationPoint.onArgumentsChange` and merge a new `URL_ARGUMENTS_CHANGE` type stream with the `APP_START` type stream for the set editor content epic.
Populates the editor though Neo4j Desktop deep links like: 
`neo4j://neo4j-browser/?cmd=play&arg=reco`.
This PR does not expand the number of argument cmd:s neo4j-browser handles, which is currently limited to `play`.
changelog: Support deep links via Neo4j Desktop
=> Register callback for onArgumentsChange from Neo4j Desktop

package.json, src/browser/components/DesktopIntegration/helpers.js, src/browser/components/DesktopIntegration/helpers.test.js, src/browser/components/DesktopIntegration/index.jsx, src/browser/components/DesktopIntegration/index.test.js, src/browser/modules/App/App.jsx, src/browser/modules/App/App.test.js, src/shared/modules/commands/cypher.test.js, src/shared/modules/connections/connectionsDuck.js, src/shared/services/bolt/bolt.js, src/shared/services/bolt/boltConnection.js, src/shared/services/bolt/boltHelpers.js, src/shared/services/utils.js, src/shared/services/utils.test.js
Instead of using username + password, Neo4j Desktop can now pass means for graph applications to ask for a Kerberos ticket and use that to connect to Neo4j instead.
Docs: https://github.com/neo4j-apps/graph-app-starter#reference
=> Support Neo4j Kerberos auth when in a Neo4j Desktop environment

src/browser/components/Display.jsx, src/browser/components/icons/Icons.jsx, src/browser/modules/DatabaseInfo/UserDetails.jsx, src/browser/modules/Stream/CypherFrame/helpers.js, src/browser/modules/Stream/CypherFrame/helpers.test.js, src/browser/modules/Stream/CypherFrame/index.jsx, src/browser/modules/Stream/CypherFrame/index.test.js
The cypher result frame was rendered empty in this case:
1. Connect to a db
1. Run a query. Keep result frame in stream.
1. Disconnect
1. Click re-run on the result frame from past query
This PR fixes that and also adds tests for the behavior.
=> Fix hidden error on re-run when going from success -> error result

src/shared/services/WorkPool.js, src/shared/services/WorkPool.test.js, src/shared/services/bolt/bolt.js, src/shared/services/bolt/boltWorker.js, src/shared/services/bolt/boltWorkerMessages.js
Since we’re pooling web workers we can keep connecitons alive.
Prior to any query we ensure connection is valid anyway.
But we need to open at least one connection per thread since connections can't be shared between threads.
The maximum number of threads is set to 10, but new threads are only created if all existing ones are busy.
Example: Connect and type `RETURN 1` and execute.
`tail -f security.log` gives:
=> Keep bolt connections alive in web workers

src/shared/modules/jmx/jmxDuck.js
Pick only what’s needed for the background fetches.
=> Don’t fetch everything from jmx in background fetches

src/browser/modules/Editor/Editor.jsx, src/browser/modules/Stream/CypherFrame/VisualizationView.jsx, src/browser/modules/Stream/Queries/QueriesFrame.jsx, src/browser/modules/Stream/SchemaFrame.jsx, src/browser/modules/Stream/SysInfoFrame/index.jsx, src/browser/modules/User/UserAdd.jsx, src/browser/modules/User/UserInformation.jsx, src/browser/modules/User/UserList.jsx, src/shared/modules/cypher/cypherDuck.js, src/shared/modules/cypher/cypherRequestEpic.test.js, src/shared/services/bolt/txMetaData.test.js, src/shared/services/bolt/txMetadata.js, src/shared/services/commandInterpreterHelper.js
Added to these
- EXPLAIN query that's called when user types
- Viz actions like auto-connect and explore neighbors 
- `:queries` frame
- `:schema` frame
- `:sysinfo`
- `:server user add` and `:server user list`
=> Add tx metadata to queries that's generated by user actions

src/shared/services/bolt/boltMappings.js
Some results clashed into an old result shape / type guessing check, that safety can be removed now.
Example `CALL apoc.path.subgraphAll(a, {maxLevel:1}) YIELD nodes, relationships`
Fixes: #912
=> Fix subgraphs not displaying correctly under certain circumstances

src/shared/modules/dbMeta/dbMetaDuck.js, src/shared/modules/jmx/jmxDuck.js
To stop them from building up if server is busy.
=> Block background queries until the prev is finished

src/browser/modules/Stream/Auth/ConnectionForm.jsx, src/browser/modules/Stream/Auth/ConnectionForm.test.js
Stale information was presented on connect frame.
Now it updates when configuration is read from dbms.
=> Fix retain credentials info on connect frame

src/browser/hooks/useDerivedTheme.js, src/browser/hooks/useDerivedTheme.test.js, src/browser/modules/App/App.jsx
Only let environment chose theme when the user has ‘AUTO’ selected.
Encapsulate this logic in a hook to make testing easier and less logic in base App component.
=> Fix UI theme resolving logic

src/browser/components/FileDrop/FileDrop.jsx
Only show the global FileDropper when files are dragged.
=> FileDrop fix.

src/browser/modules/Stream/CypherFrame/AsciiView.jsx, src/browser/modules/Stream/SysInfoFrame/legacyHelpers.jsx, src/browser/modules/Stream/SysInfoFrame/sysinfo-utils.js
This PR addresses two bugs discovered during testing:
- Browser dies when looking at "Text" window of new commands
- Browser breaks after running :sysinfo
The return value from sysinfo has changed. Changes had already been made to accommodate this, but there was a mapping util that had yet to be updated. It was simply referencing an old property
The error emanated from an underlying library `ascii-data-table` where the function `R.transpose` was referencing `arr[0]` without a guard. For now simply ensure that data is not undefined. When @oskarhane is back we can look at a more graceful fix.
=> Bugfixes from testing

src/browser/modules/Stream/CypherFrame/AsciiView.jsx, src/browser/modules/Stream/CypherFrame/TableView.jsx, src/browser/modules/Stream/CypherFrame/helpers.js, src/browser/modules/Stream/CypherFrame/helpers.test.js, src/browser/modules/Stream/ParamsFrame.jsx, src/shared/services/bolt/boltMappings.js, src/shared/services/bolt/cypherTypesFormatting.js, src/shared/services/bolt/cypherTypesFormatting.test.js
Example query `RETURN 1.0/0.0`.
- Rename stringFormat -> stringModifier to hint that it may not always do formatting.
- Add tests to verify bug is fixed
=> Handle Infinity and -Infinity results correctly 

package.json, src/browser/components/clickable-urls.jsx, src/browser/components/clickable-urls.test.js, src/browser/modules/D3Visualization/components/Inspector.jsx, src/browser/modules/Stream/CypherFrame/TableView.jsx, src/browser/modules/Stream/CypherFrame/__snapshots__/TableView.test.js.snap, yarn.lock
This PR makes URLs returned in Graph inspector and Table views clickable (opens new tab).
- `CREATE (n:Stuff {stuff: "http://google.com" tots mgoats workds"})`
- `MATCH (n:Stuff) RETURN n`
- click node in graph
- switch to table view
=> Now displaying clickable urls in table and graph views

src/browser/modules/Stream/FrameTitlebar.jsx, src/shared/utils/array-has-items.js
This PR adds support for exporting the result of `:history` as TXT.
- run `:history`
- Select "Export TXT" from export dropdown
=> Export :history

src/browser/components/clickable-urls.jsx, src/browser/modules/Stream/CypherFrame/TableView.jsx
This PR addresses a bug where target=_blank attribute would not be preserved in final HTML
=> Bugfix clickable urls

src/shared/modules/connections/connectionsDuck.js
This PR reverts a temporary dev change to the connections duck that accidentally made it in to master. The reason for the change was to test the app in a specific state, and should have been reverted before https://github.com/neo4j/neo4j-browser/pull/955 was merged to master.
- Launch the app
- Note that slow connection warnings appear despite being connected
=> Remove temporary dev state in connections duck

package.json, src/browser/modules/Sidebar/favorites.utils.js, src/shared/services/export-favorites/export-favorites.utils.js, yarn.lock
This PR addresses some bugs introduced by https://github.com/neo4j/neo4j-browser/pull/964.
- Updating the name of top level favorites would lead to a firebase exception due to property `folder` having a value of `undefined`
- CSS fixes where ellipsis would not show due to a wrapping div used for react-dnd
- Addressed bug where static scripts marked `not_executable` would still show as executable
- Increased font size of headers as per design request
- During testing I noticed that browser-sync will reset favorites when it finally loads. This is not a new behaviour but still a bit unexpected.
=> Bugfix saved favorites

src/browser/modules/Frame/FrameTemplate.jsx
Fixes an issue where the statusbar was positioned inside the frame body, giving it too much padding.
=> Move the frame statusbar outside the frame body.

src/shared/modules/discovery/discoveryDuck.js, src/shared/modules/discovery/discoveryDuck.test.js
This PR adds support for the new `bolt_direct` field in discovery responses, prioritizing it over the old `bolt` field.
=> Prioritize bold_direct over bolt in discovery

src/browser/components/DesktopIntegration/helpers.js, src/browser/modules/App/App.jsx, src/browser/modules/Stream/Auth/ConnectionForm.test.js, src/browser/modules/Stream/Queries/QueriesFrame.jsx, src/browser/modules/Stream/Queries/QueriesFrame.test.js, src/shared/modules/features/versionedFeatures.js, src/shared/services/utils.js, src/shared/services/utils.test.js
"Default scheme" = The scheme added by neo4j-browser if the user didn't enter a scheme themselves.
Cases like when the connect URL is entered as `localhost`, `localhost:7687` etc.
Notes:
This would need to be changed before merging canary into master since it's now hard coded in some places.
We need to figure out what scheme to use when not connected yet before merging canary into master.
For now we'll have to live with a disconnected master / canary.
=> Default scheme `bolt://` -> `neo4j://` in canary

src/browser/components/DataTables.jsx, src/browser/components/Form.jsx, src/browser/components/buttons/index.jsx, src/browser/modules/Frame/styled.jsx, src/browser/modules/Stream/Auth/ConnectionFrame.jsx, src/browser/modules/Stream/Auth/styled.jsx, src/browser/modules/Stream/CypherFrame/__snapshots__/TableView.test.js.snap, src/browser/modules/User/RolesSelector.jsx, src/browser/modules/User/UserAdd.jsx, src/browser/modules/User/UserInformation.jsx, src/browser/modules/User/UserList.jsx, src/browser/modules/User/styled.jsx, src/browser/styles/themes.js
Fixes some style and UX issues with `server user add` and `server user list`.
Before:
After:
=> Server user add UI fixes

src/browser/modules/Frame/FrameSuccess.jsx, src/browser/modules/Frame/styled.jsx, src/browser/modules/Stream/Auth/ChangePasswordForm.jsx, src/browser/modules/Stream/Auth/ChangePasswordFrame.jsx, src/browser/modules/Stream/Auth/ConnectionForm.jsx, src/browser/modules/Stream/Auth/styled.jsx, src/browser/modules/User/UserAdd.jsx, src/shared/modules/connections/connectionsDuck.js, src/shared/rootEpic.js, src/shared/services/bolt/boltConnection.js
If the new password successfully was set when changing password, but it’s not accepted when trying to connect, retry up to 5 times before failing.
Also, when validating old credentials, don’t reconstruct the main driver instance. Create a new one and validate on that one.
=> Retry reconnection on pw-change

src/browser/modules/Carousel/style.less, src/browser/modules/Editor/styled.jsx, src/browser/modules/Frame/styled.jsx, src/browser/modules/Stream/Auth/styled.jsx, src/browser/modules/Stream/AutoRefresh/styled.jsx, src/browser/modules/Stream/CypherFrame/__snapshots__/ErrorsView.test.js.snap, src/browser/modules/Stream/CypherFrame/__snapshots__/WarningsView.test.js.snap, src/browser/modules/Stream/Queries/styled.jsx, src/browser/modules/Stream/__snapshots__/SchemaFrame.test.js.snap, src/browser/modules/Stream/styled.jsx, src/browser/styles/global-styles.js
Fixes:
* Issue with the statusbar on the `:sysinfo` and `:queries` frames.
* Issue where code ligatures in the editor aren't affected by the setting under 'Browser settings'.
* Issue where links are not visible in code-blocks in dark mode.
changelog: Fix various UI glitches
=> Statusbar and Code ligature issues 

src/browser/modules/Stream/Auth/ConnectForm.jsx, src/browser/modules/Stream/Auth/ConnectionForm.jsx, src/browser/modules/Stream/Auth/ConnectionFrame.jsx, src/browser/modules/Stream/Auth/styled.jsx, src/shared/modules/connections/connectionsDuck.js, src/shared/modules/connections/connectionsDuck.test.js, src/shared/services/bolt/boltConnection.js, src/shared/services/bolt/boltHelpers.js
Remove the initial empty auth check when neo4j-browser loads.
This is not no pollute the security log file with false positives for denied connection attempts.
Users will now always have to confirm their connection and authentication method if no credentials are stored.
The auto-connect on startup _with_ credentials is still there.
=> Don’t auto-connect without credentials

src/browser/modules/User/UserAdd.jsx, src/shared/modules/cypher/boltUserHelper.js
Force use password returns an empty string when unchecked but dbms.security.createUser expects a boolean.
changelog: Fix "Force password change" on `:server user add`
=> Fix issue with `:server user add`.

src/browser/modules/Stream/AutoRefresh/styled.jsx, src/browser/modules/Stream/SysInfoFrame/helpers.js, src/browser/modules/Stream/SysInfoFrame/index.jsx, src/browser/modules/Stream/SysInfoFrame/legacyHelpers.jsx, src/browser/modules/Stream/SysInfoFrame/sysinfo-utils.js
This PR addresses three requested improvements for `:sysinfo`:
- Add datetime output to frames to show user when information was last updated
- Show Store Size
- Display changes to dbms.cluster.overview
Cluster
3.x
4.x
=> Various small improvements to sysinfo

src/browser/modules/Stream/SchemaFrame.jsx, src/browser/modules/User/UserAdd.jsx, src/browser/modules/User/UserInformation.jsx, src/browser/modules/User/UserList.jsx, src/shared/modules/cypher/boltUserHelper.js, src/shared/modules/cypher/cypherDuck.js, src/shared/services/bolt/bolt.js, src/shared/services/utils.js
This PR addresses changes to the `:schema` command, handling of depcrecated `bolt+routing` protocol,  as well as changes to user handling in anticipation of 4.0
- Fixed JS exception when calling `:schema` with created indexes
- Aliased `bolt+routing://` to `neo4j://`
- Added feature switch for new RBAC commands when on 4.0
=> User handling, bolt+routing, :schema fixes

e2e_tests/integration/multistatements.spec.js, e2e_tests/support/commands.js, src/browser/modules/Sidebar/Sidebar.jsx, src/browser/modules/Stream/CypherScriptFrame/Summary.jsx, src/shared/modules/commands/commandsDuck.js, src/shared/services/commandInterpreterHelper.js
Added E2E tests
Make sure you enable multi-stament.
Test script:
1. Create databases
`:use system`
2. `CREATE DATABASE test1; CREATE DATABASE test2;`
3. 
```
:use neo4j;
:param x => 1;
:unknown;
:use test1;
CREATE (:Test1);
:use test2;
CREATE (:Test2);
```
Check contents of the different databases. This is what the E2E test does.
=> Enable database switching with `:use xx` in multi-statement command

src/shared/modules/cypher/cypherDuck.js, src/shared/modules/features/versionedFeatures.js
Dynamically figure out how to change pw, even when not connected properly.
The case is when the client don't know the server version and cannot ask the server for it because of forced pw change.
The driver does know, because it can identify the servers bolt version, and exposes a helpful `driver.supportsMultidb()` for us to use.
=> Fake server version depending on multidb support

e2e_tests/integration/bolt.spec.js, e2e_tests/integration/multi-db.spec.js, e2e_tests/support/commands.js, src/browser/modules/DBMSInfo/DBMSInfo.jsx, src/browser/modules/DBMSInfo/DatabaseSelector.jsx, src/browser/modules/DBMSInfo/DatabaseSelector.test.jsx, src/browser/modules/Main/styled.jsx, src/browser/modules/Stream/Auth/DbsFrame.jsx, src/browser/modules/Stream/CypherFrame/ErrorsView.jsx, src/shared/modules/commands/commandsDuck.js, src/shared/modules/commands/commandsDuck.test.js, src/shared/modules/commands/useDb.test.js, src/shared/modules/connections/connectionsDuck.js, src/shared/modules/currentUser/currentUserDuck.js, src/shared/modules/dbMeta/__snapshots__/dbMetaDuck.test.js.snap, src/shared/modules/dbMeta/dbMetaDuck.js, src/shared/modules/features/versionedFeatures.js, src/shared/rootEpic.js, src/shared/services/bolt/bolt.js, src/shared/services/bolt/boltConnection.js, src/shared/services/commandInterpreterHelper.js, src/shared/services/cypherErrorsHelper.js
All users can get a list of all databases (incl. info on which is the default), but not all users can access all databases.
When connecting to the dbms, all users will start out using the system default db.
If they try to run cypher but don't have access, an error message is shown with an addition which a link to list all available databases to help the user find it's way.
The `"List available databases"` links to `:dbs`.
_Prior art: We do this when a users inputs a unknown procedure_
See screenshot.
I also reworked so we don't show error message when a user is trying to `:use xx` a db that doesn't exist but let the system handle that when the user tries to exec a command.
E2E tests added to verify the behavior.
=> Handle initial db selection

src/browser/modules/DBMSInfo/DatabaseSelector.jsx, src/browser/modules/Stream/SysInfoFrame/helpers.js, src/shared/modules/dbMeta/dbMetaDuck.js
This PR fixes breaking changes to SHOW DATABASES:
- Show only unique names in database selector
- Use only SHOW DATABASES output in :sysinfo, as it now also contains the causal clustering state
=> use new output of show databases

src/browser/modules/Stream/Auth/DbsFrame.jsx
=> Only show each database once in :dbs output

src/shared/modules/discovery/discoveryDuck.js, src/shared/modules/discovery/discoveryDuck.test.js
In coming versions of Neo4j, `bolt_routing` is preferred.
=> Prefer `bolt_routing` URL from discovery if it exists

src/browser/modules/Docs/Docs.jsx, src/browser/modules/Stream/HelpFrame.jsx, src/browser/modules/Stream/SchemaFrame.jsx, src/browser/modules/Stream/SchemaFrame.test.js, src/browser/modules/Stream/__snapshots__/SchemaFrame.test.js.snap, src/browser/modules/Stream/styled.jsx, src/shared/modules/cypher/cypherDuck.js
Before:
After:
Also:
- fixed some typos 
- renamed the default export in `browser/modules/Docs/Docs.jsx` to Docs as it's never imported as Guides
=> Update SchemaFrame styling

src/browser/modules/Frame/FrameTitlebar.jsx, src/browser/modules/Stream/SchemaFrame.jsx, src/shared/services/commandInterpreterHelper.js
I'm not entirely sure if this is the best approach to make the re-run button work.
The alternative would be to move the fetching logic to the `commandInterpreterHelper.js` file. This is what the Cypher and Style frames are currently doing (those are the only type of frames that have a re-run button at the moment). 
I decided against it as I think the current way is more readable. You can see right in the SchemaFrame component what kind of data it requires, and if that data needs to be changed, both the request and the rendering for that data are in the same file.
=> Add re-run button to SchemaFrame

e2e_tests/integration/multi-db.spec.js, src/browser/modules/Stream/CypherFrame/helpers.js
Adjust the messaging shown to users with regards to system updates when running system commands
- Displays `1 system update,  no records` when `_systemUpdate` = 1
- Should display `n system update, no records`, when `_systemUpdate` > 1 (not been able to figure out to get this show in practice so suggestions welcome). I can remove this if its just deemed as unnecessary.
- Displays `no changes, no records` when !`_systemUpdate` (as before)
Ive only scoped the e2e tests within the `'serverVersion') >= 4.0`...
=> User feedback running system commands

e2e_tests/integration/plan.spec.js, src/browser/modules/Stream/CypherFrame/PlanView.jsx, src/browser/modules/Stream/CypherFrame/index.jsx
WIP (looking to add a test)
- Have query plans expanded by default as opposed to collapsed now
- I chained the `setParentState` after the `extractPlan` in the `PlanView` `componentDidMount` in order to make sure `this.state.extractedPlan` is set prior to `this.toggleExpanded` is called (as it required it to be set first.). The only other way I could think of doing it was to have `this.ensureToggleExpand` always expand by default when no `_planExpand` is available on the parent component state initially but the pattern of setting parent state is preferred. Any suggestions here are welcome as I couldn't quite determine the best way to do this work.
Some example queries I tested and it seems to work ok:
```
PROFILE 
MATCH p=(n:Movie)--(m:Person)--(o:Movie)
WHERE m.born > 1000
AND length(p) > …
```
=> Query plans view expanded by default

src/browser/components/ManualLink.jsx, src/browser/components/ManualLink.test.js, src/browser/documentation/help/create-database.jsx, src/browser/documentation/help/create-user.jsx, src/browser/documentation/help/drop-database.jsx, src/browser/documentation/help/drop-user.jsx, src/browser/documentation/help/partials/admin-on-systemdb.jsx, src/browser/documentation/help/partials/dbs-on-systemdb.jsx, src/browser/documentation/help/show-databases.jsx, src/browser/documentation/help/show-users.jsx, src/browser/documentation/index.js, src/browser/documentation/templates/DynamicTopics.jsx
In this pull request I'm adding help cards related to databases and users. I will add the rest of the cards (roles and privileges) in a separate pull request in order to keep this one to a reasonable amount of changes. 
One thing to note is the change to the `ManualLink` component. I added a `minVersion` attribute to avoid getting 404s in case browser is connected to an older version of the server that doesn't contain these features.
=> Add help cards for new administration features

src/shared/services/bolt/cypherTypesFormatting.js, src/shared/services/bolt/cypherTypesFormatting.test.js
- Added `NaN` as a 'false positive' so we can display as it is and move on. Plus added an addition to a test.
- Currently, where we display the table output, we call `stringifyMod` with `stringModifier` as the second param (https://github.com/neo4j/neo4j-browser/blob/master/src/browser/modules/Stream/CypherFrame/TableView.jsx#L72). The issue is `stringModifier` doesn't handle `NaN` in any of the existing cases and so `undefined` is returned.
- This means we never return at this point (https://github.com/neo4j/neo4j-browser/blob/master/src/shared/services/utils.js#L371) and instead handled by this line (https://github.com/neo4j/neo4j-browser/blob/master/src/shared/services/utils.js#L375) and return 'null'
- This work is now in line with the output of cypher-shell (using queries shown on …
=> Show NaN in the table output instead of being handled displayed as null

src/browser/modules/D3Visualization/components/Inspector.jsx
Steps to reproduce: 
- Run any query returning a graph
- Click on a node
- Hover the icons around it, or click the dismiss icon
- The icon showing in the footer of the card will be huge and scrollable
**Note:** this issue was happening only on Firefox. 
Before:
After:
=> Fix huge SVG icons in inspector

src/browser/documentation/help/alter-user.jsx, src/browser/documentation/help/create-role.jsx, src/browser/documentation/help/create-user.jsx, src/browser/documentation/help/deny.jsx, src/browser/documentation/help/drop-role.jsx, src/browser/documentation/help/grant-role.jsx, src/browser/documentation/help/grant.jsx, src/browser/documentation/help/revoke-role.jsx, src/browser/documentation/help/revoke.jsx, src/browser/documentation/help/show-privileges.jsx, src/browser/documentation/help/show-roles.jsx, src/browser/documentation/help/show-users.jsx, src/browser/documentation/index.js, src/browser/documentation/templates/DynamicTopics.jsx
Adds help cards for the following commands:
- ALTER USER
- SHOW ROLES
- [CREATE|GRANT|REVOKE|DROP] ROLE
- SHOW PRIVILEGES
- GRANT
- DENY
- REVOKE
Links to the help cards are also added into a new section of the `:help cypher` result card.
=> Add help cards for security commands

e2e_tests/integration/data-export.spec.js, src/browser/modules/Frame/FrameTitlebar.jsx, src/browser/modules/Stream/CypherFrame/index.jsx
- Add e2e tests for the correct export options to appear dependent on the Cypher frame view
- I question the need for alphabetical order mainly for the viz view, as it seems to be logical/better UX to me to have the PNG and SVG options first. It's a trivial change in any case and will be quick to implement once we decide on what to do (edit: after speaking with UX, it was deemed better to put in alphabetical order since in this case CSV/JSON will always be at the top and likely a better UX experience)
=> e2e test added for export options

src/browser/modules/D3Visualization/lib/visualization/components/graph.js
fixes: #905 
- There seems to be an issue where the `expandedNodeMap` contains duplicates, so that as the code recursively loops over the `expandedNodeMap` array to remove nodes when a node is collapsed, it falls into an issue where the node is not found the second time round during the recursion and throws an error.
- I'm not sure of where to place a test for this as there didn't seem to be any e2e tests for expanding/closing nodes unless Im mistaken, so any input on that would be appreciated. The other option would be to open a unit test file but I don't want to start cluttering the code base with unnecessary unit test files if they're not needed.
**Before** - shows the duplicates in the `expandedNodeMap`:
[Before Video](https://drive.google.com/file/d/1veHbQHBpT4GDvxop8McrQC5lk06pd42J/v …
=> Remove duplicates from the expandedNodeMap array

src/browser/modules/Carousel/Carousel.jsx, src/browser/modules/Docs/Docs.jsx, src/browser/modules/Stream/PlayFrame.jsx, src/shared/modules/commands/commandsDuck.js, src/shared/services/commandInterpreterHelper.js, src/shared/services/commandUtils.js, src/shared/services/commandUtils.test.js
This PR adds ability to deeplink to specific slide when playing remote guide.
To deeplink to a remote guide slide, simply add an anchor link to the end of the remote URL
`http://guides.neo4j.com/how-to-guide.html#slide-2`
=> Deeplink to slide in remote guides

src/shared/modules/editor/editorDuck.js, src/shared/modules/editor/editorDuck.test.js
Add newline for each query. 
Semi-colons are up to the user to add.
Example usages:  
`http://localhost:7474/?cmd=edit&arg=RETURN%201;&arg=RETURN%20rand();`  
`http://localhost:7474/?cmd=param&arg=x%20%3d%3E%201;`  
`http://localhost:7474/?cmd=params&arg={x:1.0,%20y:%22hello%22}`  
Since it's not limited to Cypher, but works for populating the editor with anything the command is was decided to be `edit`.
Cypher:  
Param:  
Params:
=> Add URL param support for populating editor with Cypher and parameters

e2e_tests/integration/multistatements.spec.js, package.json, yarn.lock
bumb parser dependency
Upstream change: https://github.com/neo4j-apps/lambda-parser/pull/3
changelog: Fix `:param` when returning an implicit object with newlines
=> Bugfix browser implicit lambda with newlines

e2e_tests/integration/schema-frame.spec.js, e2e_tests/integration/types.spec.js, src/browser/modules/Stream/SchemaFrame.jsx, src/browser/modules/Stream/SchemaFrame.test.js, src/browser/modules/Stream/__snapshots__/SchemaFrame.test.js.snap
Indexes stopped showing up on the schema card on 4.0 due to a change on the data format returned from the driver. With these changes the description for each index is replaced by list of properties.
=> Fix indexes not showing on 4.0 SchemaFrame

e2e_tests/integration/multi-db.spec.js, src/browser/modules/DBMSInfo/DatabaseSelector.jsx, src/browser/modules/DBMSInfo/DatabaseSelector.test.jsx, src/browser/modules/DBMSInfo/MetaItems.jsx, src/browser/modules/Stream/Auth/DbsFrame.jsx, src/shared/services/commandInterpreterHelper.js, src/shared/services/utils.js, src/shared/services/utils.test.js
We add backticks to generated `:use` commands to be consistent with cypher.
Unquoted named are still ok though as seen in the screen shot.
=> Allow database names to be escaped with back ticks with the `:use` command

e2e_tests/integration/loadcsv.spec.js, src/shared/modules/commands/commandsDuck.js, src/shared/modules/commands/cypher.test.js, src/shared/modules/commands/helpers/cypher.js, src/shared/modules/cypher/cypherDuck.js, src/shared/services/bolt/bolt.js, src/shared/services/bolt/boltConnection.js, src/shared/services/bolt/boltHelpers.js, src/shared/services/bolt/boltHelpers.test.js, src/shared/services/bolt/boltWorker.js, src/shared/services/commandInterpreterHelper.js
To get automatic retries in cases of leader switches in clusters we want to move away from auto-committed transactions `session.run()` to transaction functions `session.xxxTransaction(tx => tx.run())`.
However, certain Cypher commands (i.e. `USING PERIODIC COMMIT`) requires an auto-committed transaction to be able function.
That's why we introduce the opt-out of transaction functions command and instead use auto-commited transactions: `:auto`.
Just prepend it to the query:  `:auto RETURN 1` and it'll use an auto-committing transaction.
=> Use best practices driver transaction functions by default

README.md, jsconfig.json, src/browser/components/Display.jsx, src/browser/components/TabNavigation/Navigation.jsx, src/browser/components/TabNavigation/Navigation.test.js, src/browser/components/buttons/ConfirmationButton.jsx, src/browser/modules/D3Visualization/components/Explorer.jsx, src/browser/modules/D3Visualization/components/Graph.jsx, src/browser/modules/D3Visualization/components/GrassEditor.jsx, src/browser/modules/D3Visualization/components/GrassEditor.test.js, src/browser/modules/D3Visualization/components/Inspector.jsx, src/browser/modules/Editor/Codemirror.jsx, src/browser/modules/Editor/Editor.jsx, src/browser/modules/Editor/Editor.test.js, src/browser/modules/Intercom/index.jsx, src/browser/modules/Stream/Auth/ConnectionForm.jsx, src/browser/modules/Stream/CypherFrame/AsciiView.jsx, src/browser/modules/Stream/CypherFrame/PlanView.jsx, src/browser/modules/Stream/CypherFrame/TableView.jsx, src/browser/modules/Stream/CypherFrame/VisualizationView.jsx, src/browser/modules/Sync/BrowserSyncInit.jsx, src/browser/modules/User/UserAdd.jsx, src/browser/modules/User/UserAdd.test.js, src/browser/modules/User/UserList.jsx, src/browser/modules/User/UserList.test.js, src/shared/services/utils.js, src/shared/services/utils.test.js, test_utils/setupTests.js
Rename deprecated lifecycles to current name to clear lint warnings.
Add jsx flag in jsconfig to enable "Go to Definition" and "Find All References" in VS Code.
=> Deprecated lifecycles

src/browser/modules/Stream/Auth/ChangePasswordForm.jsx
Slight quality of life improvement when changing password
Before:
After:
=> skip generate button when tabbing through change password form

src/browser/documentation/dynamic/cypher.jsx, src/browser/documentation/help/auto.jsx, src/browser/documentation/help/load-csv.jsx, src/browser/documentation/index.js, src/browser/modules/Stream/CypherFrame/ErrorsView.jsx, src/browser/modules/Stream/CypherFrame/ErrorsView.test.js, src/shared/services/cypherErrorsHelper.js
A follow-up PR for https://github.com/neo4j/neo4j-browser/pull/1048.
* Add new `auto` help page
* Add link to help page from `USING PERIODIC COMMIT` Cypher error frame
* Add links to auto help page from other relevant help pages
=> Add `:help auto` + link to it from relevant errors and docs

src/browser/modules/Sidebar/static-scripts.js, src/browser/modules/Sidebar/static-scripts.test.js, src/shared/modules/favorites/staticScripts.js
Fixes #1033  by adding a version range on the example queries and filtering the list by if the currently connected database is in the range.
Also added a Connect to database example for when there is no database version (when disconnected).
=> filter example scripts by database version

e2e_tests/integration/desktop-env-url.spec.js, e2e_tests/support/commands.js, src/browser/components/desktop-api/desktop-api.js, src/browser/components/desktop-api/desktop-api.test.js, src/browser/modules/App/App.jsx
Fixes a regression and reacts to Desktops `onArgumentsChange` again.
Both component tests + E2E tests added.
See it in action:
=> Fix reacting to deep links when in Neo4j Desktop environment

e2e_tests/integration/multi-db.spec.js, src/browser/modules/DecoratedText/TextCommand.jsx, src/browser/modules/Frame/FrameTitlebar.jsx, src/browser/modules/Stream/StyleFrame.jsx, src/shared/modules/commands/commandsDuck.js, src/shared/modules/commands/commandsDuck.test.js, src/shared/modules/commands/cypher.test.js, src/shared/modules/commands/helpers/cypher.js, src/shared/modules/commands/multiCommands.test.js, src/shared/modules/commands/use-db-no-ww.test.js, src/shared/modules/commands/use-db-ww.test.js, src/shared/services/bolt/bolt.js, src/shared/services/bolt/boltConnection.js, src/shared/services/bolt/boltWorker.js, src/shared/services/bolt/setup-bolt-worker.js, src/shared/services/commandInterpreterHelper.js, src/shared/services/commandUtils.js
Wrongfully we assumed that the target DB always should be the globally selected one. This was not a valid assumption and this PR fixes that.
Now a command action object can target a specific DB.
I refactored the arguments to our `readTransaction`, `writeTransaction`, and `directTransaction` to take an options object instead of just adding more args.
Unit tests for when using web workers and not + e2e tests included.
1. Run cypher query (q1) on db1 `RETURN rand()`
1. Switch to a different db, db2: `:use system`
1. Click "Re-run" on result frame for q1 from step 1.
1. See it being executed on db2 rather than db1, which is unexpected behaviour.
=> Fix re-run for Cypher queries to target original DB

e2e_tests/integration/desktop-env-url.spec.js, src/shared/modules/editor/editorDuck.js
Desktop uses the `URL().searchParams.toString()` which encodes spaces to `+` signs when sending arguments, and browser didn't handle that correctly.
This fixes it and includes it in an E2E test to verify it works.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURIComponent has an example on how to use `decodeURIComponent` (which we already use) to do this. 
One small addition to it was all that was needed.
=> Parse query parameters correctly

src/browser/modules/Stream/Stream.jsx
Before: Browser scrolled to top when a frame was deleted in the stream.
Now: Only scroll to top when a frame is added to the stream.
Not sure how to easily test this though.
=> Fix scroll to top bug when a frame was deleted

e2e_tests/integration/multi-db.spec.js
New versions of neo4j only lists dbs current user can access, one of Browser's e2e test is no longer valid.
=> remove list dbs e2e test

src/browser/modules/App/App.jsx, src/browser/modules/Main/Main.jsx, src/browser/modules/Main/Main.test.jsx, src/shared/modules/dbMeta/dbMetaDuck.js, src/shared/services/commandInterpreterHelper.js
Display an error banner when current database is not online
I reused an existing error banner in the main component that was unused.
Also, if user tries to `:use` an unavailable database, display an error fram in same way as when trying to use a non-existing database
If the current database is not responding, queries time out after 30 seconds. This makes the dbMetaEpic slow as it has four queries running in sequence. I remove the chained mergeMaps and wrapped the queries in a forkJoin instead to run the queries in parallel.
=> Display warning in UI when database is unavailable

src/browser/modules/App/App.jsx, src/browser/modules/Stream/Auth/ConnectionForm.jsx, src/shared/modules/commands/commandsDuck.js, src/shared/modules/commands/postConnectCmdEpic.test.js, src/shared/modules/connections/connectionsDuck.js, src/shared/modules/editor/editorDuck.js, src/shared/modules/editor/editorDuck.test.js, src/shared/modules/settings/__snapshots__/settingsDuck.test.js.snap, src/shared/modules/settings/settingsDuck.js, src/shared/modules/settings/settingsDuck.test.js, src/shared/services/localstorage.js, src/shared/services/localstorage.test.js
Autorun play commands in url parameters. The play url command is considered an explicit init command and will disable all the implicit init commands that are normally run (server status/connect frame, settings sample script and post connect command).
changelog: Auto-run `:play` commands when sent with URL params (deep-link)
=> Autorun deeplinked play commands

e2e_tests/integration/help-command.spec.js, e2e_tests/integration/play-command.spec.js, e2e_tests/support/commands.js, src/browser/components/Directives.jsx, src/browser/components/Directives.test.js, src/browser/components/buttons/index.jsx, src/browser/components/icons/Icons.jsx, src/browser/documentation/guides/concepts.jsx, src/browser/documentation/guides/cypher.jsx, src/browser/documentation/guides/intro.jsx, src/browser/documentation/guides/learn.jsx, src/browser/documentation/guides/movie-graph.jsx, src/browser/documentation/guides/northwind-graph.jsx, src/browser/icons/skip-prev.svg, src/browser/modules/Carousel/Carousel.jsx, src/browser/modules/Docs/Docs.jsx, src/browser/modules/Frame/styled.jsx, src/browser/modules/Stream/CypherScriptFrame/CypherScriptFrame.jsx, src/browser/modules/Stream/HelpFrame.jsx, src/browser/modules/Stream/PlayFrame.jsx, src/browser/modules/Stream/Stream.jsx, src/browser/modules/Stream/stream.utils.js, src/shared/modules/stream/__snapshots__/streamDuck.test.js.snap, src/shared/modules/stream/streamDuck.js, src/shared/modules/stream/streamDuck.test.js, src/shared/services/commandInterpreterHelper.js
The stream becomes cluttered quite quickly when clicking on help topics from within help topics.
This PR enables frame stacks, so if a user clicks a help topic from within a help topic, the same frame is reused and the user can navigate back and forth through out the stack.
The same goes for guides.
Frames are only reused within their own category, so clicking a guide topic from within a help topic will generate a new frame in the stream.
Demo guides:  
Demo help:
=> Reuse `:help` and `:play` frames by building frame stacks from internal link clicks

src/browser/modules/Carousel/style.less, src/browser/modules/Carousel/styled.jsx, src/browser/modules/Frame/styled.jsx, src/browser/modules/Stream/__snapshots__/SchemaFrame.test.js.snap
Some style fixes.
Sorry about the prettier formatting change in the .less file.
Before:  
After:  
Before:  
After:  
Might not be perfect, but it doesn't look broken.
=> Style start frame to look better in different resolutions

e2e_tests/integration/desktop-env.spec.js, e2e_tests/support/utils.js, src/shared/rootEpic.js
In the [autorun play commands PR](https://github.com/neo4j/neo4j-browser/pull/1072) I added the initialSwitchConnectionFailEpic epic, but forgot to combine it in the root epic so it was never active. This created the bug that the server switch fail frame was not displayed when starting browser from neo4j desktop without a started database. This PR adds the epic to rootEpic to fix this bug and adds an E2E test to verify that the server switch fail frame is displayed as intended.
=> Add initalSwitchConnectionFailEpic to rootEpic

src/browser/modules/D3Visualization/lib/visualization/components/queryPlan.js
If `operator.Details` exists in plan object, use that (exists in 4.1).
This fixes the E2E test in 4.1.
Before  
After
=> Use new plan field ‘Details’ to plan visualization

src/browser/components/Tables.jsx
See console, throws error before this fix.
=> Fix row key issue on :sysinfo table when connected to a cluster

src/shared/modules/dbMeta/dbMetaDuck.js
The `Observable.if` doesn’t execute one or the other path, it only makes the decision on what to subscribe to.
So both paths was actually executed, all the time.
This fixes that.
=> Fix so browser doesn't execute meta query on system db

e2e_tests/integration/commands.spec.js, e2e_tests/integration/debug-command.spec.js, src/browser/modules/Stream/Auth/ConnectionForm.jsx, src/browser/modules/Stream/Auth/ConnectionForm.test.js, src/browser/modules/Stream/Auth/ServerStatusFrame.jsx, src/browser/modules/Stream/Auth/ServerStatusFrame.test.js, src/shared/modules/dbMeta/__snapshots__/dbMetaDuck.test.js.snap, src/shared/modules/dbMeta/dbMetaDuck.js, src/shared/modules/features/featuresDuck.js, src/shared/modules/features/featuresDuck.test.js, src/shared/services/commandInterpreterHelper.js
Main driver for this PR is the existing bug that can be reproduced like this:
1. Open Desktop (don't start a dbms)
1. Open Neo4j Browser and see the `:server switch fail` frame.
1. Type `:server connect` or `:server status` in Neo4j Browser. It say's you're connected.
The fix: Use the `isConnected` that we have in state and don't infer it from other state props.
New look of unconnected `:server status`:  
This PR also does some user capabilities checks (can user read server config + can user list server procedures).
I've also added a `:debug` command that might be helpful when coding.
This command will get more useful in the future, but this is the introduction to it. At this point only targeted at Noe4j Browser developers.
Also, target system db (if we have multi-db support) for the …
=> More reliable connection status check

src/shared/modules/connections/connectionsDuck.js, src/shared/modules/connections/connectionsDuck.test.js, src/shared/modules/discovery/discoveryDuck.js
`http://localhost:7474/?connectURL=bolt://user@host.com` should populate connection field with the username as well as the bolt url.
=> Fix reading `username` from connectURL param

src/browser/modules/Frame/FrameTitlebar.jsx, src/browser/modules/Stream/Queries/QueriesFrame.jsx, src/browser/modules/Stream/SysInfoFrame/index.jsx, src/browser/modules/Stream/auto-exec-button.test.jsx, src/browser/modules/User/UserList.jsx, src/shared/modules/commands/commandsDuck.js, src/shared/modules/stream/streamDuck.js
Some frames that only updated on cdm needed to be adapted.
A few frames (`:sysinfo` and `:queries`) already had a re-run button in the lower status bar. These were removed to be consistent.
=> Add re-run button to all frame types

src/browser/modules/Stream/Auth/ConnectionForm.jsx, src/browser/modules/Stream/Auth/ConnectionForm.test.js, src/shared/modules/connections/connectionsDuck.js, src/shared/services/bolt/bolt.js, src/shared/services/bolt/globalDrivers.js
+ also fix issue where usernames didn't clear when server switch auth mode during browser session (without reload)
=> Fix auth scheme error from driver when auth is disabled + reflect auth status on `:server connect` frame`

e2e_tests/integration/bolt.spec.js, src/shared/services/bolt/transactions.js
=> Fix sending tx metadata with each query

src/shared/modules/connections/connectionsDuck.js, src/shared/modules/currentUser/currentUserDuck.js, src/shared/modules/dbMeta/dbMetaDuck.js
Skip requesting for current user when auth is disabled.
Skip checking cluster role when not in a cluster.
Gotta keep them logs clean!
=> Fix only executing relevant background queries (auth, cluster)

e2e_tests/integration/schema-frame.spec.js
Make assertion more loose as well, for the future.
The new assertion matches only the Constraints parts of the output, and it also matches both output versions (details and description)
=> Fix :schema E2E tests for 4.1

src/shared/modules/connections/connectionsDuck.js
(not at initial connection attempt)
This fixes browser crashing in a specific scenario.
=> Only trigger reconnect attempts when we’re supposed to be connected

e2e_tests/integration/plan.spec.js, src/browser/modules/D3Visualization/lib/visualization/components/queryPlan.js
Add output for `GlobalMemory` and `Memory` where it exists.
`GlobalMemory` should normally only be available on the last `Produce Result` and `Memory` can be on some of the other operators.
The query `PROFILE MATCH(n) RETURN 1` should have operators that displays both variants.
See screenshot below for how it's rendered.
I also widened the operator boxes a little bit to make it fit and in general make the plan less tall.
And added E2E tests to make sure they don't disappear.
=> Add memory allocation to plan output if provided by Neo4j

e2e_tests/integration/types.spec.js, src/browser/modules/Stream/CypherFrame/relatable-view.jsx
=> Fix: Display large integers in new table correctly

e2e_tests/integration/0.index.spec.js, e2e_tests/integration/connect-form.spec.js, e2e_tests/support/utils.js, src/shared/modules/dbMeta/dbMetaDuck.js, src/shared/modules/features/featuresDuck.js, src/shared/modules/features/featuresDuck.test.js
Don't rely on internal client config procedure to be listed in `dbms.procedures` output.
Make e2e tests work over HTTPS.
Add timeout for username to be populated in sidebar.
=> Call config procedure and store state of its availability + fix E2E when run tests over HTTPS

src/browser/modules/Stream/CypherFrame/__snapshots__/relatable-view.test.js.snap, src/browser/modules/Stream/CypherFrame/relatable-view.styled.js
Makes it easier to see all values in a row.
Before:
After:
=> Vertical align cell values at row top

src/browser/components/DataTables.jsx, src/browser/components/TabNavigation/styled.jsx, src/browser/components/buttons/index.jsx, src/browser/modules/Carousel/style.less, src/browser/modules/Carousel/styled.jsx, src/browser/modules/D3Visualization/components/styled.jsx, src/browser/modules/D3Visualization/graphStyle.js, src/browser/modules/Editor/styled.jsx, src/browser/modules/Frame/styled.jsx, src/browser/modules/Sidebar/styled.jsx, src/browser/modules/Stream/Auth/styled.jsx, src/browser/modules/Stream/AutoRefresh/styled.jsx, src/browser/modules/Stream/CypherFrame/__snapshots__/CodeView.test.js.snap, src/browser/modules/Stream/CypherFrame/__snapshots__/VisualizationView.test.js.snap, src/browser/modules/Stream/Queries/styled.jsx, src/browser/modules/Stream/__snapshots__/SchemaFrame.test.js.snap, src/browser/modules/Stream/auto-exec-button.jsx, src/browser/modules/Stream/styled.jsx, src/browser/styles/themes.js
changelog: Update the UI color schemes (dark, light, contrast)
Example:
=> CSS theme changes

e2e_tests/integration/types.spec.js, src/browser/modules/Frame/FrameTitlebar.jsx, src/browser/modules/Stream/CypherFrame/AsciiView.jsx, src/browser/modules/Stream/CypherFrame/__snapshots__/relatable-view.test.js.snap, src/browser/modules/Stream/CypherFrame/helpers.js, src/browser/modules/Stream/CypherFrame/helpers.test.js, src/browser/modules/Stream/CypherFrame/relatable-view.jsx, src/shared/services/utils.js
Use the existing `stringifyMod` function to create fake numbers out of Neo4j integers (strings witout quotes).
Add tests to lock this functionality.
Can be verified with this query:
```
RETURN 9907199254740991, 1416268800000, {int: 9907199254740991, ont: 1416268800000}, [9907199254740991, 1416268800000]
```
Before:
After:
=> Fix integer rendering in table recursively + JSON export

e2e_tests/support/commands.js, src/browser/modules/App/App.jsx
Only subscribe to metrics once, on app mount.
`unsub` can be false and `useEffect` expects a function to be returned.
=> Fix unsubscribe bug

src/browser/modules/Carousel/Carousel.jsx, src/browser/modules/Carousel/styled.jsx
Found two issues when testing Edge support
1. Carousel Button Container caused horizontal scroll
Before:
After:
2. Scroll position was not reset when switching guide slides
Before:
After:
=> Two Edge fixes

src/browser/modules/Editor/styled.jsx
The transparent background looks broken when the editor is in full-screen:
With primary background color:
=> Set background color on editor container

src/browser/modules/Stream/Auth/ChangePasswordForm.jsx, src/browser/modules/Stream/Auth/styled.jsx
If you have a password manager that adds an icon inside password input fields, the eye icon that reveals password will be covered by the password manager icon:
This change moves the reveal icons out of the inputs to make room for any password manager icon:
Alignment was adjusted slightly as well.
=> Update change password form to avoid overlap with password manager icons

src/browser/documentation/guides/movie-graph.jsx, src/browser/documentation/help/create.jsx
The create query was not runnable without quotes. Also changed some characters to close #1079.
=> Update example and use normal dots in example data

src/browser/components/Form.jsx
Gets rid of console error, react wants htmlFor since for is keyworded.
https://reactjs.org/docs/dom-elements.html
=> Use correct labeling

src/browser/components/TabNavigation/Navigation.jsx, src/browser/modules/Sidebar/DocumentItems.jsx, src/browser/modules/Sidebar/Documents.jsx, src/browser/modules/Sidebar/DragItemTypes.js, src/shared/modules/commands/commandsDuck.js, src/shared/services/commandUtils.js, src/shared/services/commandUtils.test.js
Replaced the comment regex with a filter that easier to understand and doesn't have this issue:
However. This is an edge-case but could happen:
It seems to me from https://neo4j.com/docs/2.2.2/cypher-comments.html that cypher supports comments, any reason why we need to "clean the command"? Could it not simply be removed (perhaps some version stuff with cypher?).
From some initial looks this
Doesn't work if we let cypher handle the comments because then the second statement is evaluated as cypher instead of a command. So perhaps leaving the cleaning as it is is preferable? The current implementation has that awkward edgecase but at least the syntax highlighting indicates the something might be wrong.
=> Fix comment filtering on command

src/shared/modules/commands/commandsDuck.js, src/shared/services/commandInterpreterHelper.js, src/shared/services/exceptionMessages.js, src/shared/services/exceptions.js, src/shared/services/grassUtils.js
Fixes this problem where semicolons break style when using multiline.
There's some behaviour changes, they are outlined as comments.
=> Update UX on :style usage

README.md
Hi,
I use e2e to test my work with `yarn e2e --env server=4.0` but it's failed at first then I check readme and see it's said fresh installation of neo4j, I create new docker and first test pass but some other test failed again I checked and found that I use docker latest image and it's version 4.1.1 and when use `yarn e2e --env server=4.1` it's worked good.
I think maybe this helps others
=> Fix readme e2e test

src/browser/modules/Editor/Editor.jsx
When the editor checks the current query with `explain`, the potential mistake of sending multiple statements in one query is not caught. Frontend has the info to flag this issue so this PR adds an extra check on editor update, and displays the warning as a warning triangle in the editor gutter.
When clicking other warnings in the editor, an explain query is sent and the result displayed in a warning frame. Since this warning is caught in frontend, that query is skipped and a simple error frame with a message is displayed.
=> Add multi statement query warning when multi statement is disabled

yarn.lock
`elliptic` 6.5.2 has a security warning that is fixed in 6.5.3.
We depend on elliptic through the chain of dependencies `webpack@4` --> `node-libs-browser` --> `crypto-browserify` --> `browserify-sign` and `create-ecdh`. Of these only browserify-sign have bumped ellipic to 6.5.3, so bumping our resolved dependency in our lock file is the practical way of solving the security warning short-term. Next patch version of webpack should have elliptic 6.5.3 and next major version of webpack will drop node-libs-browser completely.
=> Bump elliptic dependency

src/browser/modules/App/styled.jsx
On safari fullscreen looked like this:
Now it looks like it should:
In my testing, it seems the z-index: 1 causing this was unneeded, but please do take a look and see if anything looks off.
=> Fix fullscreen issue in safari

src/browser/modules/Editor/Editor.jsx, src/shared/modules/commands/commandsDuck.js
Leaves the comments in place when there's only one comment.
Properly resizes editor when moving through history and setting from clicking a frame header.
=> Show comment in frame header

build_scripts/webpack.config.js
The app size has increased quite a bit since the introduction of mdx. 
The `faker` lib is **HUGE** considering what we use it for. 
Maybe we should consider dropping that and rewriting the parts we need manually.
Try to avoid one large file, even them out a bit.
Before:
After:
=> Move new large deps from app bundle to vendor bundle

build_scripts/webpack-plugins.js, package.json, yarn.lock
Due to vulnerabilities warnings.
Adapt build scripts to breaking changes in `copy-webpack-plugin`.
=> Bump dependencies minor versions + ‘copy-webpack-plugin’ major version

src/shared/modules/commands/helpers/http.js, src/shared/modules/commands/helpers/http.test.js
Current implementation of isValidURL is very slow for some values, which was noticed when a user set `EnableMultiStatement:true` which takes around 2 minutes(!) on my machine. I don't know what part of the regex is slow, but with all web browser we support now supporting the URL constructor we can remove the regex to fix the issue.
=> reimplement isValidURL to fix performance bug

src/browser/modules/App/keyboardShortcuts.ts
We want to avoid users who used 'esc' for years having to relearn keyboard shortcuts.
@akollegger  @shkirando I let the hover text and documentation be only the "new" shortcut. This way experienced users can still use them, but new ones see the tooltip for the shortcut we think makes more sense. Do you guys think this is a good approach? Leaving the stats for which one is more used for next week
=> Re-add esc as shortcut

src/browser/modules/DBMSInfo/DBMSInfo.jsx, src/browser/modules/DBMSInfo/MetaItems.jsx, src/browser/modules/Editor/styled.tsx
The full screen was a few pixels off:
Fix:
Since we have the colours of node labels readily available I thought it'd be neat if we used them when showing labels in the sidebar!
=> Colorize node labels in sidebar

src/browser/modules/Stream/SysInfoFrame/helpers.js, src/browser/modules/Stream/SysInfoFrame/index.jsx, src/browser/modules/Stream/SysInfoFrame/index.test.js, src/browser/modules/Stream/SysInfoFrame/sysinfo-utils.js
**What:**
Change introduces a message for non-legacy community version on sysinfo component which informs user that complete data is available only in enterprise version of Neo4j.
**Why:**
Fixes #1100 
Few months ago I was wandering why - after installing 4.0.3 CE Neo4j on my VPS - sysinfo component does not contain all info available on my other 3.5+ server. I thought that i had something misconfigured, but then i found #1100 issue opened on github.
**Details:**
1. I've decided not to hide all columns - I left the 'Databases' untouched. Other tables without data are hidden if there is no data.
2. Legacy sysinfo behaves as before.
3. Please find the screenshots I've made (after change):
**Change:** 
_(v4.0.3-CE)_ - Displays info that some data is missing - and why:
_4.0.3 Enterprise_ - …
=> Info about lack of some data in sysinfo for non-legacy community version

src/browser/modules/Editor/EditorFrame.tsx, src/browser/modules/Editor/ProjectFilesButton.tsx
Adds in the ability to clear Editor heading and Project File context from the ProjectFilesButton, when the execute command button is clicked. This is currently incorrect in master and doesn't lose project file context or remove the heading (leading to the save button still being in edit mode and looks confusing).
[Video](https://drive.google.com/file/d/1EK75nX-SqOy1IUpLgYOlue2DfdicO-49/view)
=> clear editor heading and active project file context on execute command

src/browser/modules/Editor/Editor.jsx, src/browser/modules/Editor/EditorFrame.tsx, src/browser/modules/Editor/ProjectFilesButton.tsx, src/browser/modules/Sidebar/ProjectsFilesScripts.tsx, src/browser/modules/Sidebar/project-files.constants.ts
- While a project file is selected and is in the EditorFrame, executing a command via the sidebar will not clear the editor context - project file remains as it is. However then executing the command via the editor will clear the context. This brings it more in line with how Browser operates now and what makes more sense as an interim step.
- Small fix to logic previously whereby clicking a local script would enable edit pencil icon which would not clear when clicking onto a project file.
[Video showing changes](https://drive.google.com/file/d/1zuj84H9qFXFttPqb7VJZ2T-d2mr_dvAY/view)
=> execute commands from sidebar and editor logic

src/shared/modules/dbMeta/__snapshots__/dbMetaDuck.test.js.snap, src/shared/modules/dbMeta/dbMetaDuck.js, src/shared/modules/stream/streamDuck.ts, src/shared/services/localstorage.test.ts, src/shared/services/localstorage.ts
Passwords are temporarily stored in local storage between connecting and receiving the config even if the `browser.retain_connection_credentials` neo4j config flag is false. To avoid storing passwords in localstorage unless the config flag is true, this PR changes three things:
- The default value for the flag in redux store is now false
- The store selector returns false if the flag is null or undefined
- The local storage middleware checks the flag before saving to storage and replaces all passwords with an empty string unless the flag is true.
=> Do not store connection passwords in local storage before receiving neo4j config

src/browser/modules/Editor/EditorFrame.tsx
Toggle fullscreen was running with out of date state when not provided with the relevant state in the dep array.
=> Couldn't leave fullscreen

src/browser/modules/Stream/CypherFrame/VisualizationView.jsx, src/shared/modules/commands/cypher.test.js, src/shared/services/commandInterpreterHelper.js
Previously ":auto" would be removed from the middle of queries such as "match (n) where n.key = "test:auto". 
Resolves #1149
=> Only remove :auto if it is a prefix

package.json, src/browser/AppInit.jsx, yarn.lock
I've tested that no events get sent if the production env is not set and that it respects the allowOutGoingConnections setting. Would be good if someone else tested as well, just to be sure. To get the prod flag set correctly run `NODE_ENV=production yarn cross-env webpack-dev-server --colors --config ./build_scripts/webpack.config.js`. 20% of events get sent to the sentry dashboard. If you're a neo4j employee and don't have access ping me
=> Setup sentry

e2e_tests/integration/connect-form.spec.ts
Aura doesn't support an arbitrary amount of databases, so we've disabled the choose database in connect form in aura but forgot to add a check in the tests.
=> Disable test for feature not in aura

src/browser/modules/Sidebar/ProjectFiles.tsx, src/browser/modules/Sidebar/project-files.constants.ts, src/browser/modules/Sidebar/project-files.utils.ts
- added a project file name input error util
- [Video](https://drive.google.com/file/d/1ezdkSOZyDTIVmweewlCRLyLLEq5x06y6/view)
- cleans it up for now and can add to the chars list as they show up. Or we could be better off with existing filename module 🤷
=> add project file name input error check util

src/browser/documentation/help/create-index-on.jsx, src/shared/modules/favorites/staticScripts.js
Example in :help create index-on and static script now includes modern syntax.
=> Update "create index" examples to use new syntax

src/browser/modules/Stream/Auth/ConnectForm.tsx, src/browser/modules/Stream/Auth/ConnectionForm.jsx, src/browser/modules/Stream/Auth/ConnectionForm.test.js, src/browser/modules/Stream/Auth/ConnectionFrame.jsx, src/shared/modules/app/appDuck.js, src/shared/modules/discovery/discoveryDuck.test.js
To test add "localhost" to the NEO4J_CLOUD_DOMAINS in settings duck. I'm unsure how to properly mock the discovery though. I've also tested connecting with the form against a proper aura db.
Form is simplified to show the following:
Unsure if we want to keep the dropdown when we only have one option. I've also considered adding a pattern to the form to require the connection url match the format of the required scheme. Thoughts? 
Also. Aura calls it "Connection URI" and we call it a "Connect URL". Should either change to be more consistent?
=> Update connection form to better reflect aura usage

src/browser/AppInit.tsx, src/browser/modules/Editor/ProjectFilesButton.tsx, src/browser/modules/Sidebar/ProjectsFilesScripts.tsx, src/shared/modules/app/appDuck.ts
Everything mentioned here only affects the saved files feature.
Due to a change in how Desktop is retrieving projects, using the Desktop ID to get a project through Relate will no longer work. To avoid breaking this feature, and to be more semantically correct, Desktop will be passing the Relate ID instead when launching graph apps. 
This PR makes Browser aware of the new URL parameter if it exists and falls back to the old one if it doesn't, making the change backward compatible.
More information about the Desktop changes can be found here: https://github.com/neo-technology/neo4j-desktop/pull/927
=> Use Relate ID instead of Desktop ID for projects

src/browser/documentation/guides/movie-graph.tsx
Because multi-db is not supported in all Browser use cases (Aura, 3.5.X)
=> Removed information about creating a new db in :play movies

src/browser/modules/App/App.test.tsx, src/browser/modules/App/App.tsx, src/browser/modules/App/PerformanceOverlay.tsx, src/shared/modules/settings/__snapshots__/settingsDuck.test.ts.snap, src/shared/modules/settings/settingsDuck.ts
First step with performance instrument, more metrics and refinement to come. To turn the overlay on run `:config "showPerformanceOverlay": true`
Keep in mind memory usage is only available in chrome sadly
=> Basic performance overlay

README.md, src/browser/documentation/guides/cypher.tsx
What:
1. Fixed `:play cypher` documentation at slide 2 - curly brackets were missing due to nature of jsx. In order to display them, it is necessary to put a string with curly brackets inside jsx brackets.
2. Fixed minor typo in README.md file.
Before:
After:
=> Fix cypher docs

package.json, src/browser/AppInit.tsx, src/browser/components/ErrorBoundary.tsx, src/browser/index.tsx, src/shared/modules/udc/udcDuck.ts, src/shared/services/commandInterpreterHelper.ts, tsconfig.json, yarn.lock
Changes:
- Reuse mixpanel id to track how many users unique users run into issues
- Sends console.errors to sentry, not just uncaught errors
- Use sentry's errorboundry so see errors caught by errorboundries as well
- Seperates prod/canary env properly
- Sets up a sentry "transaction", to track how slow cypher queries generally are
=> Sentry updates

src/browser/AppInit.tsx, src/shared/modules/commands/commandsDuck.test.ts, src/shared/modules/commands/commandsDuck.ts, src/shared/modules/udc/udcDuck.ts, src/shared/modules/udc/udcEpics.test.ts, src/shared/services/commandInterpreterHelper.ts
When switching plans from monthly active users to number of events. Since we have cypher succeeded and failed, we don't need a separate event for totals.
=> Remove unneeded mixpanel events

LICENSES.txt, NOTICE.txt, package.json, src/browser/components/SavedScripts/SavedScripts.tsx, src/browser/components/SavedScripts/icons.tsx, src/browser/components/SavedScripts/index.ts, src/browser/components/SavedScripts/saved-scripts-edit-button.tsx, src/browser/components/SavedScripts/saved-scripts-exec-button.tsx, src/browser/components/SavedScripts/saved-scripts-export-button.tsx, src/browser/components/SavedScripts/saved-scripts-folder.tsx, src/browser/components/SavedScripts/saved-scripts-list-item.tsx, src/browser/components/SavedScripts/saved-scripts-new-folder-button.tsx, src/browser/components/SavedScripts/saved-scripts-remove-button.tsx, src/browser/components/SavedScripts/saved-scripts.constants.ts, src/browser/components/SavedScripts/saved-scripts.hooks.ts, src/browser/components/SavedScripts/saved-scripts.styled.ts, src/browser/components/SavedScripts/saved-scripts.tsx, src/browser/components/SavedScripts/saved-scripts.utils.test.ts, src/browser/components/SavedScripts/saved-scripts.utils.ts, src/browser/components/SavedScripts/types.ts, src/browser/modules/Sidebar/ProjectsFilesScripts.tsx, src/browser/modules/Sidebar/favorites.ts, src/browser/modules/Sidebar/favorites.utils.ts, src/browser/modules/Sidebar/static-scripts.ts, src/shared/services/export-favorites/export-favorites.utils.ts, yarn.lock
From our work on project files it's clear we need to make changes to the saved-scripts component. As the relate-by-ui repo is pretty much dead and we're the only users of this component, I'm moving it into the main repo. 
Changes:
- Move files here from relate-by-ui repo
- Remove dependency from package.json/licenses
Will follow up with a PR with tests to show that the original behaviour is preserved and then a PR with refactorings to make the code match our code standards, and finally a PR to implement the needed changes.
Preview: http://remove_saved_scripts_dep.surge.sh
=> Inline @relate-by-ui/saved-scripts

src/browser/AppInit.tsx, src/browser/custom.d.ts, src/browser/modules/Stream/CypherFrame/VisualizationView.test.tsx, src/browser/modules/Stream/CypherFrame/helpers.test.ts, src/browser/modules/Stream/CypherFrame/helpers.ts, src/shared/modules/connections/connectionsDuck.ts, src/shared/modules/cypher/cypherDuck.ts, src/shared/services/bolt/applyGraphTypes.test.ts, src/shared/services/bolt/bolt.ts, src/shared/services/bolt/boltConnection.ts, src/shared/services/bolt/boltHelpers.test.ts, src/shared/services/bolt/boltHelpers.ts, src/shared/services/bolt/boltMappings.test.ts, src/shared/services/bolt/boltMappings.ts, src/shared/services/bolt/boltWorker.ts, src/shared/services/bolt/boltWorkerMessages.ts, src/shared/services/bolt/driverFactory.ts, src/shared/services/bolt/globalDrivers.ts, src/shared/services/bolt/setup-bolt-worker.ts, src/shared/services/bolt/transactions.ts, src/shared/services/boltscheme.utils.ts, src/shared/services/utils.test.ts, src/shared/services/utils.ts
After reading [Dan Flavin's post on waiting for large query results in browser](https://medium.com/neo4j/wheres-my-neo4j-cypher-query-results-%EF%B8%8F-%EF%B8%8F-9c3b150e6e19), I did some performance testing of browser. I found the loop that builds the graph visualisation to be unoptimised and reworked it which lead to a noticeable performance improvement. The first two commits in the branch are the performance improvements.
While testing large query results in a dev build, redux devtools crashed a few times due to out of memory errors. The third commit is a change that omits query results from redux devtools.
The 4th, 5th and 6th commits are code cleanups. They touch many lines so I recommend reviewing commit by commit to not miss other changes. Note that the typing commit does contain …
=> Improve performance when receiving large query results

docs/antora/antora.yml, docs/antora/content-nav.adoc, docs/asciidoc/index.adoc, docs/docbook/content-map.xml
Hi @oskarhane & @linuslundahl
This PR adds the basic docs infrastructure for us to start building a draft manual. New content can go into the /asciidoc folder when we have some source material, and linked up in the content maps in the /antora folder and /docbook folder.
FYI @AlexicaWright & @recrwplay
=> Add skeleton docs folders and maps

src/browser/components/TabNavigation/Navigation.tsx, src/browser/modules/Sidebar/Documents.tsx, src/shared/globalState.ts, src/shared/modules/sidebar/sidebarDuck.ts, src/shared/modules/udc/udcDuck.ts
This PR adds two tracking events, one for the canny change log button and one for the canny feature requests button.
I also fixed a react warning about missing key attribute in `Navigation.tsx` and some typescript warnings and a spelling mistake in `udcDuck.ts`.
=> Track canny usage

src/browser/modules/Frame/styled.tsx
This is a pure css change that collapses the editor when it doesn't have focus to preserve space in the stream.
Preview @ http://autocollapse.surge.sh
=> Autocollapse reusable editor when not in use

src/browser/modules/Frame/FrameTitlebar.tsx
http://frame_history.surge.sh/
=> Avoid double up arrow for going back in history re-usable frame

src/browser/modules/Editor/Monaco.tsx
Fixes cursor moving outside visible area when moving it with arrow keys. Demo available at: http://scroll-to-cursor.surge.sh/
=> scroll to cursor when setting cursor position in monaco

src/browser/components/SavedScripts/SavedScripts.tsx, src/browser/components/SavedScripts/SavedScriptsListItem.tsx
This change is to avoid the surprising behaviour shown below:
http://select_on_mouse_down.surge.sh/
=> Change selection to on mouse down

src/browser/modules/Editor/Monaco.tsx
Two small fixes, demo: http://peek-problem.surge.sh/
=> Hide Peek Problem status bar, disable escape key toggling fullscreen when autocompleting

src/browser/components/FileDrop/styled.tsx, src/browser/components/SavedScripts/styled.ts, src/browser/modules/App/PerformanceOverlay.tsx, src/browser/modules/Carousel/styled.tsx, src/browser/modules/Editor/styled.tsx, src/browser/modules/Frame/styled.tsx, src/browser/modules/Stream/styled.tsx
Previously fullscreen couldn't be closed after doing the following:
Steps to reproduce
1. Write a query (eg RETURN 1) and execute
2. Update the query in reusable frame (eg make it RETURN 2) and execute
3. Go fullscreen in reusable frame
4. Try to delete the reusable frame with X
This was due to the built in modal going underneath the fullscreen. I decreased all our z-indexes so the modal is now on top.
Preview at http://fullscreen_close.surge.sh
=> Fix issue where fullscreen couldn't be closed

src/browser/modules/Editor/EditorFrame.tsx, src/browser/modules/Editor/styled.tsx
The click handler was causing the search and replace input fields to immediately lose focus when clicking them. The click handler was not necessary since the monaco component fills almost the whole container in any case.
demo: http://search-input-click.surge.sh/
GIFs recorded of opening search and clicking the input fields, before:
After:
=> remove click handler on editor container

src/browser/modules/Stream/CypherFrame/index.tsx
Sometimes reusable frame switches away from the graph visualisation. Steps to reproduce, with the movie db:
Run:
MATCH (n) RETURN n;
Edit and run:
MATCH (n :Movie) RETURN n; 
should stay as on the viz with these changes.
=> Stay in viz when loading new results

src/browser/components/SavedScripts/SavedScripts.tsx
Old localstorage state contains duplicated folders, we will want to remove the duplicated folders from there, but for now let's just hide them.
demo: http://fix_duplicate_folders.surge.sh
=> Hide empty duplicate folders

src/browser/components/SavedScripts/SavedScripts.tsx
Bug is caused by drag and drop putting incorrect folderIds to favorites in a previous version of browser
demo @ http://fix_drag_outside_bug.surge.sh
=> Show favorites with malformed folderId

src/browser/custom.d.ts, src/browser/modules/Editor/Monaco.tsx
Fix for squashed command palette. Demo: http://command-palette-height.surge.sh/
Before:
After:
=> add workaround to squashed command palette in small cypher editors

src/browser/modules/Editor/Monaco.tsx
Adjust the font weight in the cypher editor and add fallbacks fonts in case Fira Code doesn't load.
Before:
After:
Demo: http://cypher-editor-font-weight.surge.sh/
=> Cypher editor font weight

src/browser/custom.d.ts, src/browser/modules/Editor/Monaco.tsx
Before:
After:
Demo: http://warning-column-position.surge.sh/
=> Display Cypher warnings on correct positions

src/browser/modules/Editor/Monaco.tsx
This fixes an issue where if you have navigated back in query history, then run a query with the run button instead of `Ctrl+Return`, your position in history remained and the next `Ctrl+arrow key` would put you in an unexpected position in the history. A similar issue happened when navigating history and then updating the editor content by editing a favorite/project file or copying a code example from a guide.
Demo: http://query-history-fix.surge.sh/
=> reset editor history position on set content

e2e_tests/integration/commands.spec.ts
As discussed, this will hopefully help the e2e tests to pass against Aura Pro where the `:param x => 1` command test seems to take especially long.
=> bump param lambda command timeout to 3000ms

src/browser/modules/Editor/Monaco.tsx
http://monaco-search-fixes.surge.sh/
=> ignore enter/escape key from Monaco when find widget visible

src/shared/modules/connections/connectionsDuck.ts, src/shared/modules/dbMeta/dbMetaDuck.ts
http://remember-last-used-db.surge.sh
=> Use last db instead of default db where possible

src/browser/modules/Segment/index.tsx
This PR adds a temporary ID to our segment calls that's better than nothing.
Link to the docs on how identify works: https://segment.com/docs/connections/spec/identify/
=> Add call to segment identify

e2e_tests/integration/bolt.spec.ts
With 4.3 enterprise users will be able to call dbms.cluster.overview, this in turn causes a bug in our codebase where some transaction metadata is not present in the :queries table. We'll want to fix this, but not before the 4.2.6 release.
=> Change test failing on 4.3

build_scripts/webpack-plugins.js
This will make logs easier to read and faster, the warnings still show up in vscode, so we can act on them when able.
=> Filter out warnings when building

docs/preview.yml
Updates the Antora playbook to use the new versionless UI bundle.
This change means that when future updates are made to the docs UI we won't have to raise a PR to update the playbook, and we will get the latest UI the next time we rebuild and publish.
=> Update playbook to use versionless bundle

docs/modules/ROOT/pages/operations.adoc
Fixed a typo.
Changed example name to alice.
Changed the syntax url to the bundled neo4j browser url.
=> Docs fix typo and url example

NOTICE.txt, package.json, yarn.lock
This will add new keywords from 4.3, not fully support it. Se the cypher editor repo for more details.
Preview at http://bump_cypher_support.surge.sh
=> Bump cypher-editor-support and update licenses

e2e_tests/integration/commands.spec.ts, src/browser/components/TabNavigation/Navigation.tsx, src/browser/modules/App/App.tsx, src/browser/modules/Frame/FrameTitlebar.tsx, src/browser/modules/Stream/__snapshots__/SchemaFrame.test.tsx.snap
When introducing the re-usable frame we removed to ability to populate the main editor easily. This PR adds it back as a CMD/CTRL click. I've opted to have both ctrl and cmd work. Tested to work in a windows VM.
Preview at: http://bring_to_editor.surge.sh
=> Re-add populating main editor

src/browser/modules/Main/Main.tsx, src/browser/modules/Main/main.hooks.tsx
This is a small PR to prevent the waiting banner from showing even though you're already connected in sandbox. I've added some types and some minor refactoring as well. The problem was not clearing setTimeout properly.
=> Make sure timeout is cleared properly

e2e_tests/integration/saved-scripts.spec.ts
Can't reproduce the flakiness locally, but looking at the recorded video it seems the favorite is not created properly. If nothing else this change will give more information if the test is still flaky.
=> Attempt to fix flaky test where favorite is not created

docs/modules/ROOT/pages/operations.adoc, src/browser/AppInit.tsx, src/browser/modules/App/App.tsx, src/browser/modules/Sync/BrowserSync.tsx, src/shared/modules/dbMeta/__snapshots__/dbMetaDuck.test.ts.snap, src/shared/modules/dbMeta/dbMetaDuck.ts, src/shared/services/localstorage.test.ts, src/shared/services/localstorage.ts
also change local defaults for community edition
=> add support for browser.retain_editor_history setting

src/browser/modules/D3Visualization/lib/visualization/components/graphGeometry.ts
=> truncate node captions to 100 chars in viz to fix crash

src/browser/modules/Editor/Monaco.tsx
A few settings were for hiding the "overviewruler" on the right of the editor. As a side effect they remove the highlighting occurrences and matching brackets in the editor as well. To explain what the settings were there to disable, see video
https://user-images.githubusercontent.com/10564538/122176166-9a9e4280-ce84-11eb-852d-315feada9da1.mp4
With these changes we still get the highlight in the editor, but not by the scrollbar.
https://user-images.githubusercontent.com/10564538/122176444-e2bd6500-ce84-11eb-883d-4bb2f81b912a.mp4
To find the relevant setting I dug through the monaco code and found it here:
https://github.com/microsoft/vscode/blob/3f363797cf5bde6965c5150dde1a8a93a88babf4/src/vs/editor/browser/viewParts/overviewRuler/decorationsOverviewRuler.ts#L317
Preview @ …
=> Update monaco settings

src/browser/modules/Frame/FrameEditor.tsx
Preview: http://focus_editor_on_click.surge.sh
Focuses editor and sets focus to the end of the statement.
https://user-images.githubusercontent.com/10564538/122192901-5a46c080-ce94-11eb-8dd7-556e2c1614bd.mp4
=> Focus reusable editor on mounting it

docs/preview.yml
The `page-disabletracking` attribute should be removed when docs are no longer preview, so that the Google Tag Manager script is added, and  Google Analytics tracking is enabled.
=> Enable google analytics tracking meta

src/shared/modules/stream/streamDuck.test.ts, src/shared/modules/stream/streamDuck.ts
This PR makes sure we don't pollute history with identical entries. 
Before:
https://user-images.githubusercontent.com/10564538/122230499-00f18800-ceba-11eb-86d2-296f3002faee.mp4
After:
https://user-images.githubusercontent.com/10564538/122230636-1d8dc000-ceba-11eb-8112-4dc35fddb119.mp4
Preview @ https://history_frame.surge.sh
=> Don't add identical cmds to history

src/browser/components/ClickableUrls.tsx, src/browser/modules/Stream/CypherFrame/__snapshots__/relatable-view.test.tsx.snap, src/browser/modules/Stream/CypherFrame/relatable-view.styled.ts, src/browser/modules/Stream/CypherFrame/relatable-view.tsx, src/browser/modules/Stream/__snapshots__/SchemaFrame.test.tsx.snap
Preview @ http://tablebug.surge.sh
Before:
After:
=> Fix bug where whitespace was not preserved in result

src/browser/components/buttons/index.tsx
Min item width is not respected by default in safari.
Preview @ http://safari_button_shrink_bug.surge.sh
Before:
After:
=> Fix bug where button shrunk in safari

src/browser/modules/Editor/Monaco.tsx
After a lot of digging through the VSCode/monaco source code I finally found what command the DownArrow fires here: 
https://github.com/microsoft/vscode/blob/94c9ea46838a9a619aeafb7e8afd1170c967bb55/src/vs/editor/browser/controller/coreCommands.ts#L749
Before:
https://user-images.githubusercontent.com/10564538/122933152-a8653380-d36e-11eb-89e2-8ac3dab95276.mp4
After: 
https://user-images.githubusercontent.com/10564538/122933106-9edbcb80-d36e-11eb-9363-10d111b8eb48.mp4
Preview @ http://improve_monaco_navigation.surge.sh
Solves #1418
=> Improve movement in wrapped lines

docs/publish.yml
Creates a new Antora playbook that builds from the github url rather than local content.
Advantages of this are
- VCS checkout no longer required as part of build
- this repo is public, so we can add an 'Edit this page' link by setting `page-origin-private: false` or removing the attribute.
To test, use `$(npm bin)/antora publish.yml --stacktrace --fetch`
=> add new playbook to demo edit this page link

build_scripts/webpack-plugins.js, build_scripts/webpack-rules.js, build_scripts/webpack.config.js, src/browser/custom.d.ts, src/shared/services/bolt/bolt.ts
=> Add hash to filenames of webpack split/chunk bundles

package.json, src/browser/modules/Stream/CypherFrame/PlanView.tsx, yarn.lock
Problem has been explained here -> https://github.com/neo4j/neo4j-browser/issues/1454
The issue is to refresh the state of the react component that display the plan stats at the bottom of the window
Here is a little video of the fix, sorry for the bad quality, you can see the stats are updating at the bottom of the query window
=> Refresh plan statistics after re-run the query

src/shared/modules/commands/helpers/server.ts
Solves error not being created properly. 
Before:
After: ![image](https://user-images.githubusercontent.com/10564538/124785365-156bf200-df47-11eb-9cea-fe2ed52aaa99.png)
Preview at http://name_unknown_command.surge.sh
=> Show what command was unknown

src/shared/modules/udc/udcDuck.ts
Currently UUID is lost when clearing favorites/localstorage through the browser sync tab, which is not the intention of the feature
=> Persist UUID

src/shared/modules/currentUser/currentUserDuck.ts, src/shared/modules/dbMeta/dbMetaDuck.ts, src/shared/modules/features/featuresDuck.ts, src/shared/services/bolt/bolt.ts, src/shared/services/commandInterpreterHelper.ts
If the database was shut off, `bolt.hasMultiDbSupport` will throw which we don't handle properly. This PR catches whenever it could throw. 
Our the metadata check running every 20 seconds is _supposed_ to detect when a database connection is lost but it doesn't work properly (in part because of hasMultiDbSupport throwing). I spent a few hours trying to understand why/how it doesn't work, but didn't get anywhere and I think the whole file requires heavy refactoring. I ended up including a another call to `onConnectionLost` as part of the metadata check instead, so that we don't retry the websocket in eternity. It's somewhat of a scope creep and not a perfect solution, so I'm happy to drop it.
Preview @ http://crash_on_db_switch.surge.sh
=> Prevent crash on database connection lost

src/shared/services/serializer.test.ts, src/shared/services/serializer.ts
PR fixes the following issue.
`return "a\nb" as a,"b\nc" as b`
creates this csv
```csv
a,b
a
b,b
c
```
while it should have been
```csv
a,b
"a
b","b
c"
```
Preview at http://csv_export_fix.surge.sh
=> Update serializer to escape newlines

src/browser/modules/D3Visualization/components/Graph.tsx, src/browser/modules/D3Visualization/lib/visualization/components/visualization.ts, src/browser/modules/Stream/CypherFrame/__snapshots__/VisualizationView.test.tsx.snap
Prompted by #1461, I looked into increasing the max/min zoom. Was an easy fix, worked out zoom increments and max values with PM. 
preview @ http://more_zoom.surge.sh/
=> Increase zoom limits and individual steps

src/browser/modules/Stream/SysInfoFrame/SysInfoFrame.tsx, src/browser/modules/Stream/SysInfoFrame/helpers.tsx, src/browser/modules/Stream/SysInfoFrame/legacyHelpers.tsx, src/browser/modules/Stream/SysInfoFrame/styled.tsx, src/browser/modules/Stream/__snapshots__/SchemaFrame.test.tsx.snap, src/shared/modules/dbMeta/dbMetaDuck.ts
Depends on #1472 
Changelist:
- Fixes :sysinfo running before useDb has been set by rerunning the query when it's set.
- Adds docs on how the :sysinfo frame works
- Respects metrics.prefix
- Respect metrics.namespaces.enabled
- Adds error message on missing metrics to check the settings
- Changes default metrics to use metrics that aren't filtered out by default
This task quickly crept in scope and one of the issues I didn't have time to solve properly was collecting the settings through dbMetaDuck. Got a thumbs on from greg on the newly used metrics.
preview at http://blank_sysinfo_on_boot.surge.sh
=> Fix sysinfo frame

src/browser/modules/Stream/SysInfoFrame/SysInfoFrame.tsx, src/browser/modules/Stream/SysInfoFrame/SysInfoTable.tsx
Changes:
- Fixes bug introduced in the :sysinfo frame refresh were we didn't fetch any metrics for 3.x databases
- No longer shows database table if server lacks multidb support
=> Sysinfo 3.x Fixes

src/browser/components/SavedScripts/SavedScripts.tsx, src/browser/components/SavedScripts/SavedScriptsFolder.tsx, src/browser/modules/Sidebar/favorites.ts, src/shared/services/exporting/favoriteUtils.ts
So that users don't need to select all scripts in a folder manually. Also allows for exporting them as a single cypher file, which has been requested internally.
=> Add exports to individual folder

src/browser/modules/D3Visualization/components/Explorer.tsx, src/browser/modules/D3Visualization/components/Graph.tsx, src/browser/modules/D3Visualization/components/Inspector.tsx, src/browser/modules/D3Visualization/components/styled.tsx, src/browser/modules/Frame/FrameTemplate.tsx, src/browser/modules/Frame/styled.tsx, src/browser/modules/Stream/CypherFrame/CypherFrame.tsx, src/browser/modules/Stream/CypherFrame/VisualizationView.styled.tsx, src/browser/modules/Stream/CypherFrame/__snapshots__/VisualizationView.test.tsx.snap
To solve the problem of the bottom bar moving of the screen when adding lines to a query in fullscreen a new flexbox was added to give the middle content 100% height and scroll on overflow, taking the available space not used for the editor or the bottom bar. For the main viz though, resizing the container seems to change the size of the nodes, so I've opted to use position fixed for the bottom bar and zoom controls there. Worth noting that the viz bottom bar is probably going away soon as part of our work on node properties. I'm sure there's a cleaner way to structure the css and element tree, so far this is the cleanest I've worked out after too many hours of fiddling. 
preview @ http://fullscreen_fix.surge.sh
Fixes #1460
=> Fullscreen fix

e2e_tests/integration/data-export.spec.ts, e2e_tests/integration/style.spec.ts, src/browser/modules/Frame/ExportButton.tsx
Frame refactor in last release seemed to have broken exporting history. This PR fixes it, cleans up the file and adds tests to make sure it keeps working.
Preview @ http://export_history.surge.sh
=> Fix export button for history and add tests

src/browser/components/SavedScripts/styled.ts
Fixes minor paper cut of the three dots in the favorites drawer not having cursor: pointer.
Preview: https://fix_favorite_cursor.surge.sh
=> Add cursor pointer to context menu

src/shared/services/commandInterpreterHelper.ts
Preview @ http://trailing_space.surge.sh
Previously ":history " and ":queries " would result in an error
=> Fix issues with trailing spaces in commands

src/browser/modules/Editor/MainEditor.tsx, src/browser/modules/Editor/Monaco.test.tsx, src/browser/modules/Editor/Monaco.tsx, src/browser/modules/Frame/FrameEditor.tsx
Our background explain query we do to get warnings, was not using the client side params we have. So it'll give warnings even as queries are correct. To reproduce 
1. Run `:param p => 1`
2. Type `RETURN $p`
3. Get warning on $p not being defined, although the query runs fine
I think there's a better way to solve this than passing the params down to the monaco component, but that's a change for when we get rid of the Bus
=> Add params to background explain query

src/browser/modules/App/App.tsx
Adds the current browser version (ex: 4.3.3) to tracking event properties:
```
{
browserVersion: "x.y.z",
...otherProperties
}
```
=> add browserVersion to tracking event properties

src/shared/modules/auth/helpers.js
The SSO-redirect accidentally removes the pathname from the URL as well, breaking SSO on aura. This fixes it, tested locally with browser hosted on /browser
=> Include pathname in redirect

src/browser/modules/Segment/index.tsx
Add support for `ntid` url parameter
=> Only call .identify when we have passed segment id through url param

src/browser/modules/Stream/CypherFrame/__snapshots__/VisualizationView.test.tsx.snap, src/browser/modules/Stream/__snapshots__/SchemaFrame.test.tsx.snap, src/shared/services/boltscheme.utils.ts
Browser during the loggin is creating direct connection to the informed `connect url`, but it's not removing the query string from the url. Because of this, browser is getting a `Parameters are not supported with none route scheme..` error. The routing context params are not support in direct connection by design.
The solution for this issue is removing the routing context (query string) from the url when transalate from `neo4j` to `bolt`.
=> fix: Remove routing context when converts from neo4j to bolt protocol

LICENSES.txt, NOTICE.txt, README.md, package.json, src/browser/components/headers/Headers.tsx, src/browser/modules/App/App.tsx, src/browser/modules/Stream/Auth/ConnectForm.tsx, src/browser/modules/Stream/Auth/ConnectionForm.tsx, src/browser/modules/Stream/Auth/styled.tsx, src/browser/modules/Stream/__snapshots__/SchemaFrame.test.tsx.snap, src/shared/modules/commands/helpers/server.ts, src/shared/modules/connections/connectionsDuck.ts, src/shared/modules/discovery/discoveryDuck.test.ts, src/shared/modules/discovery/discoveryDuck.ts, src/shared/modules/discovery/discoveryHelpers.test.ts, src/shared/modules/discovery/discoveryHelpers.ts, src/shared/modules/discovery/discoveryMocks.ts, src/shared/services/bolt/boltConnection.ts, src/shared/services/bolt/boltConnectionErrors.ts, src/shared/services/bolt/boltHelpers.ts, src/shared/services/bolt/boltWorker.ts, src/shared/services/bolt/globalDrivers.ts, src/shared/services/boltscheme.utils.ts, src/shared/services/utils.ts, test_utils/setupTests.js, yarn.lock
=> Update SSO to use 4.4 discovery and refresh tokens

src/browser/modules/D3Visualization/components/OverviewPane.tsx, src/browser/modules/D3Visualization/components/StyleableNodeLabel.tsx, src/browser/modules/D3Visualization/components/StyleableRelType.tsx, src/browser/modules/D3Visualization/components/__mocks__/StyleableRelType.tsx, src/browser/modules/Stream/CypherFrame/__snapshots__/VisualizationView.test.tsx.snap
=> Add count to labels/relTypes in overview

src/browser/components/ShowMoreOrAll/ShowMoreOrAll.tsx, src/browser/components/ShowMoreOrAll/styled.tsx, src/browser/modules/D3Visualization/components/DetailsPane.test.tsx, src/browser/modules/D3Visualization/components/OverviewPane.test.tsx, src/browser/modules/DBMSInfo/MetaItems.tsx
also since drawer background is always dark no matter theme, then use dark theme on ShowAllOrMore to make sure link color has better visibility.
=> Changed show more links from span to button for accessibility

src/browser/modules/Stream/CypherFrame/VisualizationView.tsx
A performance optimization caused the VisualizationView.tsx not to rerender as the fullscreen prop changed. Causing this issue:
https://user-images.githubusercontent.com/10564538/139863358-d61f4741-6a25-4f9f-aca8-cf91aa44fc5a.mp4
Preview of the fix @ http://zoombuttons_fullscreen_issue.surge.sh
=> Fix issue where fullscreen change didn't cause re-render

docs/modules/ROOT/pages/operations/product-analytics.adoc
New configuration to opt out from product analytics by default.
=> Neo4j 4.4 config_clients.allow_telemetry

src/browser/modules/D3Visualization/components/NodeInspectorDrawer.tsx, src/browser/modules/D3Visualization/components/styled.tsx, src/browser/modules/Stream/CypherFrame/__snapshots__/VisualizationView.test.tsx.snap
Our new animation of the Node properties makes the dragging of the panel look like it's lagging when it's actually just animating, luckily eija and I found a quick fix. 
Preview @ https://animation_lag_fix.surge.sh
=> Prevent animating when dragging

src/browser/modules/D3Visualization/components/DetailsPane.test.tsx, src/browser/modules/D3Visualization/components/DetailsPane.tsx, src/browser/modules/D3Visualization/components/NodeInspectorPanel.tsx, src/browser/modules/D3Visualization/components/styled.tsx, src/browser/modules/Stream/CypherFrame/__snapshots__/VisualizationView.test.tsx.snap, src/browser/modules/Stream/__snapshots__/SchemaFrame.test.tsx.snap
Cut long property values in the Node properties panel and possible to expand by clicking 'Show all'.
=> Cut long property values

src/browser/AppInit.tsx, src/browser/components/ProjectFiles/ProjectsFilesScripts.tsx, src/browser/documentation/sidebar-guides/unfound.tsx, src/browser/modules/Sidebar/GuideDrawer.tsx, src/browser/modules/Sidebar/GuidePicker.tsx, src/browser/modules/Sidebar/ProjectFiles.tsx, src/browser/modules/Stream/CypherFrame/CypherFrame.tsx, src/browser/modules/Stream/__snapshots__/SchemaFrame.test.tsx.snap, src/shared/modules/commands/commandsDuck.ts, src/shared/modules/commands/helpers/grass.ts, src/shared/modules/commands/helpers/play.ts, src/shared/modules/commands/helpers/playAndGuides.ts, src/shared/modules/dbMeta/dbMetaDuck.ts, src/shared/modules/guides/guidesDuck.ts, src/shared/modules/sidebar/sidebarDuck.ts, src/shared/rootEpic.ts, src/shared/services/commandInterpreterHelper.ts, src/shared/services/commandUtils.test.ts, src/shared/services/commandUtils.ts, src/shared/services/guideResolverHelper.test.ts, src/shared/services/guideResolverHelper.tsx, src/shared/services/localstorage.test.ts, src/shared/services/localstorage.ts, src/shared/services/utils.test.ts, src/shared/services/utils.ts
We are able to load remote guides. However, when reloading the Browser, added remote guides are lost. Thus, we need to retain remote guides in `localStorage`. 
Also, to keep the size of cache small, we aim not to store contents of guides. Same with Redux states. Instead, when we click the remote guide, we fetch from remote server.
This PR also involves some code clean up in relevant areas.
Test links:
- https://guides.neo4j.com/got
- https://guides.neo4j.com/restaurant_recommendation
- https://guides.neo4j.com/sandbox/movies/index.html
More guide links:
https://neo4j.com/developer/guide-create-neo4j-browser-guide/
Further code cleanup around the affected area and relevant unit tests and E2E tests will be handled in subsequent PRs.
=> Local Storage for retaining remote guides

src/browser/modules/D3Visualization/components/DetailsPane.tsx
=> Add brackets around array type in details properties view

e2e_tests/integration/multi-db.spec.ts, src/browser/modules/App/App.tsx, src/browser/modules/ClickToCode/__snapshots__/index.test.tsx.snap, src/browser/modules/DBMSInfo/DatabaseSelector.test.tsx, src/browser/modules/DBMSInfo/DatabaseSelector.tsx, src/browser/modules/Main/Main.test.tsx, src/browser/modules/Main/Main.tsx, src/browser/modules/Stream/Auth/DbsFrame.tsx, src/browser/modules/Stream/Auth/UseDbFrame.tsx, src/browser/modules/Stream/CypherFrame/__snapshots__/CodeView.test.tsx.snap, src/browser/modules/Stream/CypherFrame/__snapshots__/ErrorsView.test.tsx.snap, src/browser/modules/Stream/CypherFrame/__snapshots__/VisualizationView.test.tsx.snap, src/browser/modules/Stream/CypherFrame/__snapshots__/relatable-view.test.tsx.snap, src/browser/modules/Stream/__snapshots__/SchemaFrame.test.tsx.snap, src/browser/modules/Stream/styled.tsx, src/shared/modules/connections/connectionsDuck.ts, src/shared/modules/dbMeta/dbMetaDuck.ts, src/shared/modules/discovery/discoveryHelpers.test.ts, src/shared/modules/frames/framesDuck.ts, src/shared/services/commandInterpreterHelper.ts, src/shared/services/exceptions.ts, tsconfig.json
Adds support for the 4.4 concept of aliases. 
To create an alias run `create alias myAlias for database neo4j`. 
You should not be able to run `:use myAlias` and see your aliases when running `:dbs`. The "real" name should still be displaced in editor.
Preview @http://support_aliases.surge.sh
=> Support new alias feature from neo4j 4.4

e2e_tests/integration/0.index.spec.ts, e2e_tests/integration/bolt.spec.ts, e2e_tests/integration/commands.spec.ts, e2e_tests/integration/connect-form.spec.ts, e2e_tests/integration/guide-command.spec.ts, e2e_tests/integration/multi-db.spec.ts, e2e_tests/integration/multistatements.spec.ts, e2e_tests/integration/saved-scripts.spec.ts, e2e_tests/integration/settings.spec.ts, e2e_tests/support/commands.ts, src/browser/components/TabNavigation/Navigation.tsx, src/browser/modules/Sidebar/GuideDrawer.test.tsx, src/browser/modules/Sidebar/GuideDrawer.tsx, src/browser/modules/Sidebar/GuidePicker.tsx, src/browser/modules/Sidebar/__snapshots__/GuideDrawer.test.tsx.snap, src/shared/modules/commands/helpers/config.ts, src/shared/modules/commands/helpers/http.test.ts, src/shared/modules/commands/helpers/http.ts, src/shared/modules/connections/connectionsDuck.ts, src/shared/modules/discovery/discoveryDuck.test.ts, src/shared/modules/discovery/discoveryDuck.ts, src/shared/modules/discovery/discoveryHelpers.test.ts, src/shared/modules/discovery/discoveryHelpers.ts, src/shared/modules/settings/settingsDuck.ts, src/shared/services/commandInterpreterHelper.ts, src/shared/services/exceptions.ts
Followed #1594 , there are some fields still need to be done.
=> Local storage guide retainment follow up

e2e_tests/integration/viz.spec.ts, src/browser/modules/D3Visualization/components/GrassEditor.tsx, src/browser/modules/D3Visualization/components/StyleableNodeLabel.tsx, src/browser/modules/Stream/CypherFrame/__snapshots__/VisualizationView.test.tsx.snap
In property details the color of * are sometimes not updated when changing color, while it updates correctly in the sidebar.
Steps to reproduce bug:
1. Do a style reset with command: ":style reset"
2. fetch not all but one or some nodes, for example: MATCH (n:Person_0) RETURN n LIMIT 25 (then after that first fetch of some, if fetching all after that it still not works, but if fetch all first after a style reset it is working)
3. then try to change color of * in node properties, the color is not updated in the property details view.
=> Color for * nodes sometimes not updated in property details

src/browser/modules/D3Visualization/components/Explorer.tsx
This change should improve the rendering time for query results that contain lots of nodes. I used the following query throughout my tests:
```cypher
WITH range(1,100000) as range 
UNWIND range as item 
CREATE (n:Stuff {iter: item}) 
RETURN n
```
and measured:
1. The time it takes from dispatching the `requests/SENT` to the `requests/UPDATED` actions in Redux. 
2. The time it takes to execute some snippets/functions that could be potential bottlenecks. 
1. **36.42s**
2. - **1ms** - commandInterpreterHelper.ts - exec - handleCypherCommand
- **525ms** - boltWorker.ts - onmessage - cypherResponseMessage
- **636ms** - setup-bolt-worker.ts - setupBoltWorker - addTypesAsField
- **1ms** - boltWorker.ts - onmessage - cypherResponseMessage
- **43790ms** - commandInterpreterHelp.ts - exec - …
=> Improve performance of queries that return lots of nodes

src/browser/modules/D3Visualization/GraphEventHandler.ts, src/browser/modules/D3Visualization/components/DetailsPane.test.tsx, src/browser/modules/D3Visualization/components/DetailsPane.tsx, src/browser/modules/D3Visualization/components/NodeInspectorPanel.tsx, src/browser/modules/D3Visualization/components/types.d.ts, src/browser/modules/D3Visualization/lib/visualization/components/Graph.ts, src/browser/modules/D3Visualization/lib/visualization/components/GraphGeometry.ts, src/browser/modules/D3Visualization/lib/visualization/components/Relationship.ts, src/browser/modules/D3Visualization/lib/visualization/components/Visualization.ts, src/browser/modules/D3Visualization/lib/visualization/components/VizNode.ts, src/browser/modules/D3Visualization/lib/visualization/components/collision.ts, src/browser/modules/D3Visualization/lib/visualization/renders/init.ts, src/browser/modules/D3Visualization/lib/visualization/renders/menu.ts, src/browser/modules/D3Visualization/lib/visualization/utils/circularLayout.ts, src/browser/modules/D3Visualization/lib/visualization/utils/clickHandler.ts, src/browser/modules/D3Visualization/mapper.ts, src/browser/modules/Stream/CypherFrame/__snapshots__/VisualizationView.test.tsx.snap
One of the types that made up the `VizItem` type was not defined, which in turn made the `VizItem` type `any` which is fixed in this pr. 
There was also a bug where some relationships with only one node were not removed, which I've also fixed.
I've also renamed the Node.ts file to match the class it's containing "VizNode"
=> Fix hidden type issues causing crashes

src/browser/modules/D3Visualization/components/Graph.tsx
It looks wierd that when entering and leaving frame fullscreen the nodes jumps to new positions (because the simulation is run and updated), prevent that by only calling resize.
=> Prevent simulation running when entering/leaving frame fullscreen

src/browser/modules/D3Visualization/components/Graph.tsx, src/browser/modules/D3Visualization/lib/visualization/components/Visualization.ts, src/browser/modules/D3Visualization/lib/visualization/components/layout.ts, src/browser/modules/Stream/CypherFrame/__snapshots__/VisualizationView.test.tsx.snap
now both width and height are clearly defined to same as available space, and (0, 0) is in the center of the svg.
=> Cleanup of svg dimensions

.prettierrc
Changing back to default for importOrderParserPlugins since not working on tsx files.
the default for importOrderParserPlugins is [typescript, jsx]. Without the jsx the tsx files are not working,
however for queryPlan.ts it is not working for some strange reason to include jsx so adding an override only for .ts-files without the jsx.
=> Fix issue with prettier and tsx files

src/browser/components/ClipboardCopier.tsx, src/browser/modules/Stream/CypherFrame/__snapshots__/relatable-view.test.tsx.snap, src/browser/modules/Stream/CypherFrame/relatable-view.styled.ts, src/browser/modules/Stream/CypherFrame/relatable-view.tsx
- Fixed so single line object values will not have an unnecessary scroll by shrinking to copy icon
- Also, reduced the spacing around object values in tables
Before:
After:
=> Reduce icon size to avoid scroll on single line values in table

src/browser/modules/D3Visualization/GraphEventHandler.ts, src/browser/modules/D3Visualization/lib/visualization/components/Visualization.ts, src/browser/modules/D3Visualization/lib/visualization/components/layout.ts, src/browser/modules/Stream/CypherFrame/__snapshots__/VisualizationView.test.tsx.snap
- Remove the timeout that stops the simulation and adjust alpha values to make the simulation cool down on its own.
- Clicking on nodes no longer restarts the simulation.
- Reduce the number of precomputed ticks.
- Fixed a bug when dragging nodes, sometimes they would get unlocked when moving the cursor outside of the node.
- Remove re-render when clicking on the visualization background when no items are selected.
Preview available here: http://browser-visualization-tweaks.surge.sh
=> Visualization: tweak duration of the simulation

src/browser/components/Directives.tsx
Prevents the annoying behaviour where the current guide is replaced by a query result. Preview @ http://michael_guide_fix.surge.sh
https://user-images.githubusercontent.com/10564538/150505899-30803f48-f14f-4a58-b89a-52fdf14c8995.mp4
=> Make sure auto exec of play guide gets a new frame

package.json, yarn.lock
`well_known_discovery_uri` was wrongly mandatory in the discovery data, this update fixes that
=> Bump sso lib

e2e_tests/integration/params.spec.ts, src/shared/modules/commands/helpers/params.ts, src/shared/services/commandUtils.test.ts, src/shared/services/commandUtils.ts
Now it is possible to use :params command with multiple lines <img width="1292" alt="Screenshot 2022-01-24 at 15 05 34" src="https://user-images.githubusercontent.com/11065688/150797419-01ba5609-83ac-4725-a355-eef2bc87eb29.png">
=> Fixed so possible to set params using multiline

e2e_tests/integration/auto-prefix.spec.ts, e2e_tests/integration/multistatements.spec.ts, e2e_tests/support/commands.ts, e2e_tests/support/global.d.ts, src/browser/documentation/help/auto.tsx, src/browser/modules/Stream/CypherFrame/ErrorsView.tsx, src/shared/services/cypherErrorsHelper.ts
We do a few regex checks on error messages to see if the error was caused by a missing `:auto` prefix, if so we add a hint to the error message.
This PR adds a check for if the error is the new `CALL IN {} TRANSACTIONS` which needs :auto and updates the check for `PERIODIC COMMIT` (that has the new error message`"A query with 'PERIODIC COMMIT' can only be executed in an implicit transaction but tried to execute in an explicit transaction."`).
I also add a few tests to verify the behaviour, updated the `:help auto` to use the new syntax and added a helper method to cypress for faster tests.
URL for testing: update_warning.surge.sh
Do note that a 4.4 db is needed.
=> Show hint about :auto on CALL {...} IN TRANSACTIONS

src/browser/modules/D3Visualization/lib/visualization/components/Visualization.ts
Graphs that didn't have their midpoint in the centre (when no transforms are applied) didn't get centered when clicking zoom to fit. Now that is fixed by adjusting to have their mid point at the centre of the svg after zoom to fit is applied.
before:
after:
and here is how the graph looks in both cases before any transforms are applied, you can see that there is more space above than below:
=> bugfix center the graph on zoom to fit not always working

src/shared/services/WorkPool.ts, src/shared/services/bolt/bolt.ts, src/shared/services/bolt/boltConnection.ts, src/shared/services/bolt/boltWorker.ts, src/shared/services/bolt/boltWorkerMessages.ts, src/shared/services/bolt/setup-bolt-worker.ts
The code around the bolt worker is not straightforward to read, and it doesn't help that it uses some old patterns (probably) from when Javascript didn't have classes. So here is some cleanup to make this code more readable. 
I didn't change any functionality, just moved things around, updated types, and renamed a few things to have more accurate names.
Preview: http://browser-bolt-worker-cleanup.surge.sh
=> Bolt worker cleanup

src/browser/modules/Sidebar/Documents.tsx
As already discussed with Greg, I have:
- Added GraphAcademy links to Documents sidebar
- Removed Drivers Manual link which redirects to docs
[Trello card](https://trello.com/c/oYwitzZz/1936-fix-broken-drivers-manual-links-in-the-help-learn-pane)
=> Updates to Documentation Links

src/browser/modules/Stream/ParamsFrame.tsx
Now show doc links for both param and params when using either param or params.
=> Show links to documentation for both param and params

src/browser/modules/D3Visualization/lib/visualization/components/mouseEventHandlers.ts, src/browser/modules/D3Visualization/lib/visualization/constants.ts, src/browser/modules/Stream/CypherFrame/__snapshots__/VisualizationView.test.tsx.snap
When dragging a node that has lots of neighbors, the neighboring nodes keep jiggling, making the visualization look worse than it did before. This PR is addressing this by increasing friction to make the nodes stabilize more quickly, and reducing the alpha value we use when dragging to reduce the movement of nodes that aren't being dragged.
The preview of this change is available here: http://browser-visualization-tweaks.surge.sh/
=> Visualization: reduce jiggling of nodes when interacting with graph

src/browser/modules/Stream/CypherFrame/CypherFrame.tsx, src/browser/modules/Stream/CypherFrame/helpers.ts
Now it is possible to select the graph view even if the results contains more than a 1000 record fields. The other limit which truncates the record fields data is still there.
=> Remove viz limit of 1000

e2e_tests/integration/guide-command.spec.ts
What happens is we click to remove a guide and sometimes reload before it's been removed from local storage -> it's still there after refresh.
=> Fix flaky test caused by debouncing saving to localstorage

src/browser/modules/Stream/Queries/QueriesFrame.test.tsx, src/browser/modules/Stream/Queries/QueriesFrame.tsx, src/browser/modules/Stream/SysInfoFrame/SysInfoFrame.test.tsx, src/browser/modules/Stream/SysInfoFrame/SysInfoFrame.tsx, src/shared/modules/dbMeta/epics.ts, src/shared/modules/features/featuresDuck.test.ts, src/shared/modules/features/featuresDuck.ts, src/shared/utils/selectors.ts
From 4.3 we can't use the presence of `dbms.cluster.overview` to know if we're connected to a cluster, but the same version added `SHOW DATABASES` which can.
=> Improve causal cluster detection

src/browser/modules/D3Visualization/components/OverviewPane.tsx, src/browser/modules/Sidebar/UserSettings.tsx
When a single returned "row" is a list we have a hardcoded limit in which we truncate it. This PR changes the setting to be user configureable. This video show it in action.
https://user-images.githubusercontent.com/10564538/153913900-eb69fa56-973e-4b32-9f19-2889833e2f2f.mp4
Also make sure our warning messages are shown on separate lines:
A preview is up at http://expose_record_setting.surge.sh
=> Make max record setting user configurable

src/browser/modules/D3Visualization/mapper.ts, src/shared/services/bolt/boltMappings.ts
We stringify all node property values except `null`, which causes crashes later on. This PR makes we handle null, and that the correct type hint show up as well. Preview at http://handle_null_properties.surge.sh, easiest way to trigger the crash is run `call apoc.create.vNode(['stuff'], {id:5, blah:null})` and hover the created node. 
Here's a screen shot of how it looks now:
=> Handle null values in graph viz

src/browser/modules/Stream/SysInfoFrame/SysInfoFrame.test.tsx, src/browser/modules/Stream/SysInfoFrame/SysInfoFrame.tsx, src/browser/modules/Stream/SysInfoFrame/sysinfoHelpers.tsx, src/shared/modules/dbMeta/__snapshots__/dbMetaDuck.test.ts.snap, src/shared/modules/dbMeta/epics.ts, src/shared/modules/dbMeta/state.ts, src/shared/modules/features/featuresDuck.ts
After the `metrics.prefix` and `metrics.namespaces.enabled` settings were added to `clientConfig`, we no longer need the work-around of calling `listConfig` directly in the sysinfo frame since it's already called when loading the server metadata. 
I've made sure it works even if the settings haven't been read yet as well. Tested on `4.4.0` with settings: 
metrics.prefix=abc
metrics.namespaces.enabled=true
Preview at http://remove_listConfig_call.surge.sh
=> Remove unneeded listConfig call in sys info frame

src/shared/modules/udc/udcDuck.ts
This PR adds DB connections related metrics events to be sent to Segment
- when user submits the connection form
- when the connection is successful
These events will help the Growth do Activation analysis better and be able to see drop off because of any connections related frictions
=> add connection related metrics event

e2e_tests/integration/data-export.spec.ts, src/browser/modules/Stream/CypherFrame/CypherFrame.tsx
In the next version of neo4j there'll be an option to get query plan as a string representation. We're adding the option to download these. Since it's not released yet it's tricky to test, so no preview link.
This PR also makes sure you only see relevant download options for the panel you're currently viewing and makes sure we only allow downloading when there's data to download.
=> Export plan txt and make download dropdown context dependent

src/browser/modules/Stream/styled.tsx, src/graphVisualization/components/styled.tsx
Fixed styles that were set in last release when the css files were reordered hence the root font size was wrong, now when we have changed back the order the styles the root font size is different so the styles needs to be fixed. Set to px for now, until a complete change from px to rem is done all over the app.
PR where the order of the css styles imports was fixed: https://github.com/neo4j/neo4j-browser/pull/1689
=> Fixed styles that were set in last release

docs/package.json, docs/preview.yml, docs/publish.yml
Updates the docs package to the latest packages and versions, particularly upgrading from Antora 2.3 to Antora 3.0.
In the _/docs/_ directory:
1. Remove node_modules
2. npm install
3. npm start
Verify there are no errors or warning from Antora / asciidoctor, and verify the output at localhost:8002 looks as expected
From a docs contributor's perspective little is changed from the previous version of Antora. 
- If there are any errors or warnings in the log from the Antora build, they will be more informative than before, including full paths to relevant files.
- The **sitemap.xml** file is updated by the Antora extension `@neo4j-antora/antora-modify-sitemaps`, and will be output as _build/site/browser-manual/4.4/sitemap.xml after #1684 is merged. This is handled by the change to the …
=> Upgrade docs packages for Antora 3

src/neo4j-arc/cypher-language-support/cypher-editor/editorSupport.ts, src/neo4j-arc/package.json, src/neo4j-arc/rollup.config.js, src/neo4j-arc/tsconfig.json, src/neo4j-arc/yarn.lock
Some of our dependencies didn't have commonjs builds, so we'd have to transpile them if we needed a commonjs build. Fortunately we don't, so now I only build es modules. I've also added some missing types and cleaned up the config.
=> Improve build to work in nx-unit tests

src/neo4j-arc/cypher-language-support/cypher-editor/CypherMonacoThemes.ts, src/neo4j-arc/cypher-language-support/cypher-editor/editorSupport.ts, src/neo4j-arc/package.json
Add parameter to `initalizeCypherSupport` that accepts a custom Monaco syntax highlighting theme.
=> Allow custom Monaco theme

src/browser/modules/DBMSInfo/DatabaseKernelInfo.tsx, src/browser/modules/Stream/Queries/QueriesFrame.tsx, src/browser/modules/Stream/SysInfoFrame/SysInfoFrame.tsx, src/shared/modules/dbMeta/dbMetaDuck.ts, src/shared/modules/dbMeta/dbMetaEpics.ts, src/shared/modules/features/versionedFeatures.ts, src/shared/rootEpic.ts, src/shared/utils/selectors.ts
In modern version of neo4j the cluster role is available through `SHOW DATABASES` so we don't have to run `CALL dbms.cluster.role() YIELD role` to get it.
=> Use cluster role from show databases if available

src/shared/modules/commands/helpers/lambdas.ts, src/shared/modules/cypher/cypherDuck.ts, src/shared/services/bolt/boltConnection.ts, src/shared/services/bolt/boltHelpers.test.ts, src/shared/services/bolt/boltHelpers.ts, src/shared/services/bolt/transactions.ts, src/shared/services/bolt/txMetadata.ts
I've gone through the cypher queries we send in browser and tagged them properly. I've added a default fallback in case something slipped through.
=> Make sure proper metadata is passed along with queries

src/shared/services/exporting/imageUtils.ts, src/shared/services/exporting/svgUtils.ts
I set the correct font for export, increase the resolution of the PNG (less blurry text) and give it a little big extra size (since it's easy for a user to to make it smaller in for example photoshop, but look really bad when you make it bigger). (Code is also used for export of plan view) 
Before:
After:
=> Fix PNG exports font

e2e_tests/integration/auto-prefix.spec.ts, e2e_tests/integration/loadcsv.spec.ts, src/browser/modules/Stream/Queries/LegacyQueriesFrame.test.tsx, src/browser/modules/Stream/Queries/LegacyQueriesFrame.tsx, src/browser/modules/Stream/Queries/QueriesFrame.tsx
Also updates a few e2e tests that were failing on 5.0
=> Separate new & old queries frame, use SHOW TRANSACTIONS instead of dbms.listQueries

src/neo4j-arc/graph-visualization/GraphVisualizer/DefaultPanelContent/DefaultOverviewPane.tsx, src/neo4j-arc/graph-visualization/GraphVisualizer/DefaultPanelContent/NodeLabel.tsx
Same fix as in [https://github.com/neo4j/neo4j-browser/pull/1754](https://github.com/neo4j/neo4j-browser/pull/1754), but for the default Node properties panel.
=> Fixed consistent (*) count in default Overview panel as well

docs/antora.yml, docs/modules/ROOT/pages/operations/browser-url-parameters.adoc
=> Docs url parameter

src/browser/modules/Stream/CypherFrame/VisualizationView/VisualizationView.tsx, src/neo4j-arc/graph-visualization/GraphVisualizer/Graph/Graph.tsx, src/neo4j-arc/graph-visualization/GraphVisualizer/Graph/visualization/Visualization.ts, src/neo4j-arc/graph-visualization/GraphVisualizer/GraphVisualizer.tsx
This PR surfaces a new prop `wheelZoomRequired` prop for graph visualisation to dogfood load preview feature in Data Importer. Then, requiring modifier keys for scrolling to zoom and `isFullscreen` are decoupled.
To maintain the same behaviour with current Browser, you can simply pass `wheelZoomRequired={!isFullscreen}` to make it tie to `isFullscreen` state/prop.
=> feat: surface wheel zoom props and decouple with isFullscreen prop in graph visualisation

src/browser/modules/Stream/CypherFrame/VisualizationView/__snapshots__/VisualizationView.test.tsx.snap, src/neo4j-arc/graph-visualization/GraphVisualizer/Graph/visualization/Visualization.ts, src/neo4j-arc/package.json
Based on #1765 , a bug is identified that no simulation is triggered when the graph is initially rendered until the user's first interaction.
https://user-images.githubusercontent.com/26452483/177783591-ac2cbf1c-e292-4fbb-b4fd-cba9cc0510db.mov
Had dig into the root issue, I found that's due to the `forceSimulation.restart()` is not triggered when initialising the graph so  no simulation ticks and that's why `forceSimulation.endSimulationCallback()` is not triggered.
`forceSimulation.restart()` is only triggered when calling `visualization.update({restartSimulation: true})`. However, `visualization.update()` is not called if no "Connect to result nodes" option is toggled. In the current logic, when initialising the graph, the logic will be conditionally triggered".
```ts
if …
```
=> fix: graph is no simulation in initial rendering

src/browser/modules/Stream/CypherFrame/VisualizationView/__snapshots__/VisualizationView.test.tsx.snap, src/neo4j-arc/graph-visualization/GraphVisualizer/Graph/Graph.tsx, src/neo4j-arc/graph-visualization/GraphVisualizer/Graph/visualization/ForceSimulation.ts, src/neo4j-arc/graph-visualization/GraphVisualizer/Graph/visualization/Visualization.ts, src/neo4j-arc/package.json
Discussed with @OskarDamkjaer :
> We could run pre-compute only is the "connect result nodes" setting isn't on, then we'd get the best of both.
As Browser doesn't toggle zoom to fit by default so the issue I mentioned earlier today won't happen.
So I've moved the "zoom to fit" to run right after the visualisation is initialised, and brought back `precompute` when initialising the graph.
https://user-images.githubusercontent.com/26452483/178708360-b16a314a-10e8-4972-8dd8-06edaa36b3b6.mov
=> chore: move zoom to fit after pre-compute

src/browser/documentation/help/bolt-routing.tsx, src/browser/modules/Stream/Queries/LegacyQueriesFrame.test.tsx, src/browser/modules/Stream/Queries/LegacyQueriesFrame.tsx, src/browser/modules/Stream/Queries/QueriesFrame.tsx, src/browser/modules/Stream/SysInfoFrame/LegacySysInfoFrame/LegacySysInfoFrame.test.tsx, src/browser/modules/Stream/SysInfoFrame/LegacySysInfoFrame/LegacySysInfoFrame.tsx, src/browser/modules/Stream/SysInfoFrame/LegacySysInfoFrame/SysInfoDisplay.test.tsx, src/browser/modules/Stream/SysInfoFrame/LegacySysInfoFrame/SysInfoDisplay.tsx, src/browser/modules/Stream/SysInfoFrame/LegacySysInfoFrame/sysinfoHelpers.tsx, src/browser/modules/Stream/SysInfoFrame/SysInfoFrame.test.tsx, src/browser/modules/Stream/SysInfoFrame/SysInfoFrame.tsx, src/browser/modules/Stream/SysInfoFrame/SysInfoTable.tsx, src/browser/modules/Stream/SysInfoFrame/sysinfoHelpers.tsx, src/shared/modules/cypher/cypherDuck.ts, src/shared/modules/cypher/queriesProcedureHelper.ts, src/shared/modules/dbMeta/dbMetaDuck.ts, src/shared/modules/dbMeta/dbMetaEpics.ts
In the distant there was a distinction between "High Availability clusters" and "Causal clusters" but now we only use "causal cluster"s so the distinction is no longer needed.
=> Rename causal cluster -> cluster 

e2e_tests/integration/connect-form.spec.ts, e2e_tests/integration/multi-db.spec.ts, e2e_tests/integration/multistatements.spec.ts, e2e_tests/support/commands.ts, e2e_tests/support/global.d.ts
In neo4j 5.0 new databases are created asynchronously, so we'll need to wait until they are online before we try to use them.
=> Prevent 5.0 flakyness from async db creation

build_scripts/generate-manifest-helpers.js, build_scripts/webpack-plugins.js, src/browser/AppInit.tsx, src/browser/modules/Sidebar/About.tsx, src/shared/modules/app/appDuck.ts
The `mergeObjects` helper that was used before reversed the order properties were merged, causing the wrong version number to be used. I've also added the git hash to the manifest, to ease testing the stand-alone browser in the aura pipeline in the future.
=> Fix bug with incorrect version number & add git hash to overview

e2e_tests/integration/viz.spec.ts, package.json, src/browser/modules/Stream/CypherFrame/VisualizationView/__snapshots__/VisualizationView.test.tsx.snap, src/neo4j-arc/graph-visualization/GraphVisualizer/Graph/Graph.tsx, src/neo4j-arc/graph-visualization/GraphVisualizer/Graph/styled.tsx, src/neo4j-arc/graph-visualization/GraphVisualizer/Graph/visualization/Visualization.ts
Zoom in and out buttons are now disabled when reach max/min zoom. This fixes and issue when the zoom to fit sets a lower zoom scale than min zoom scale which made the zoom out button zoom in to min zoom scale. Also updates the min zoom scale on zoom to fit.
=> Zoom out behaviour with fit to zoom

src/browser/modules/Editor/styled.tsx
The Monaco editor calculates width of the line number based on the max width of the digits 0-9 and no other characters. This causes the line number to sometime line-break, nowrap fixes this.
=> Fix database name not fully displayed in editor

src/browser/modules/DBMSInfo/MetaItems.tsx, src/browser/modules/DBMSInfo/__snapshots__/MetaItems.test.tsx.snap, src/browser/modules/Stream/CypherFrame/VisualizationView/PropertiesPanelContent/DetailsPane.tsx, src/browser/modules/Stream/CypherFrame/VisualizationView/PropertiesPanelContent/OverviewPane.tsx, src/browser/modules/Stream/CypherFrame/VisualizationView/__snapshots__/VisualizationView.test.tsx.snap, src/neo4j-arc/graph-visualization/GraphVisualizer/DefaultPanelContent/DefaultDetailsPane.tsx, src/neo4j-arc/graph-visualization/GraphVisualizer/DefaultPanelContent/DefaultOverviewPane.tsx, src/neo4j-arc/graph-visualization/GraphVisualizer/NodeInspectorPanel.tsx, src/neo4j-arc/package.json
There are some UI consistencies between title-case and sentence-case. This PR unifies some of them to sentence-case according to what designers agreed with.
=> chore: change some titles to sentence case

src/browser/modules/Stream/Auth/ChangePasswordForm.tsx, src/browser/modules/Stream/Auth/ConnectForm.tsx
The best practice is to use autocomplete="off" for password fields and autocomplete="new-password" for new password fields. As described here: [https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#the_autocomplete_attribute_and_login_fields](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#the_autocomplete_attribute_and_login_fields
)
=> Add autocomplete to password fields

src/neo4j-arc/cypher-language-support/cypher-editor/CypherEditor.tsx, src/neo4j-arc/graph-visualization/GraphVisualizer/Graph/Graph.tsx
Add resize observer to visualizer to make sure zoom to fit works when window/container changes size.
=> Make sure fit to graph always work

src/browser/modules/Stream/Auth/ConnectionForm.tsx
Currently, credentials are only removed from local storage on disconnect but the old frame used to connect still saves them in its state. This PR clears the username and password from the connection form state on a successful connection.
=> Remove credentails from connection form if they should not be stored.

src/shared/services/bolt/boltConnection.ts
db.indexes() was used to check the connection to the database but was deprecated in neo4j 4.2 and will be removed in a future version. SHOW PROCEDURES seems to accomplish the same thing and is not deprecated
=> Replace deprecated procedure for checking connection

src/shared/services/bolt/boltConnection.ts
Limit 1 is not supported on show procedures which results in a different error than expected. Using no limit can return many rows which is unnecessary. Show databases should (hopefully) be better in most cases
=> Change validate connection query

e2e_tests/integration/schema-frame.spec.ts, src/browser/modules/Stream/SchemaFrame.test.tsx, src/browser/modules/Stream/SchemaFrame.tsx, src/browser/modules/Stream/__snapshots__/SchemaFrame.test.tsx.snap
db.indexes() and db.constraints() have been deprecated in Neo4j 4.2 and will be removed in a future release. This pr replaces calls to those procedures with SHOW INDEXES and SHOW CONSTRAINTS.
=> Remove deprecated procedures

src/browser/modules/Carousel/styled.tsx, src/browser/modules/Sidebar/About.tsx, src/browser/modules/Sidebar/__snapshots__/GuideDrawer.test.tsx.snap, src/browser/styles/themes.ts
This PR actually consists of 2 fixes connected to links in the sidebar
* Fix links not being blue in the About page by replacing <a> tags with DrawerExternalLinks. This is in line with how links are created on other sidebar pages.
* Fix links not changing color when being hovered over in the sidebar guides by adding styling to the StyledSidebarSlide component and also a hover color in the dark theme (the hover color of the base theme was very similar to the non-hover color of the dark theme)
=> Fix links not being blue and not being highlighted in the sidebar

src/browser/components/icons/IconContainer.tsx
Tooltip was missing on question icon in sysinfo frame, now it works again.
=> bugfix missing tooltip on fa icons

e2e_tests/integration/sysinfo-command.spec.ts, src/browser/components/Tables.tsx, src/shared/modules/dbMeta/dbMetaDuck.ts, src/shared/modules/dbMeta/dbMetaEpics.test.ts, src/shared/modules/dbMeta/dbMetaEpics.ts
=> Fix sysinfo: in 5.0 settings metrics.namespaces.enabled is removed

src/browser/components/TabNavigation/Navigation.tsx, src/browser/modules/DBMSInfo/DBMSInfo.tsx, src/shared/modules/dbMeta/__snapshots__/dbMetaDuck.test.ts.snap, src/shared/modules/dbMeta/dbMetaDuck.ts, src/shared/modules/dbMeta/dbMetaEpics.ts, src/shared/rootEpic.ts
Suppose the metadata count query takes a long time then switch off the automatic refresh for that data and display a warning in the sidebar.  It also fixes the transitions when opening/closing the sidebar.
=> Separate metadata count query

.github/workflows/pr-e2e-tests.yml, e2e_tests/integration/composite-db.spec.ts, src/browser/modules/Stream/CypherFrame/VisualizationView/VisualizationView.tsx
The query to connect result nodes failed, causing the this.autoCompleteCallback never to be called. These changes improve the error handling and adds an e2e test to make sure composite databases results show
=> Composite db didn't show result graph

src/browser/modules/Editor/MainEditor.tsx, src/browser/modules/Frame/FrameEditor.tsx, src/neo4j-arc/common/utils/objectUtils.ts, src/neo4j-arc/cypher-language-support/cypher-editor/CypherEditor.test.tsx, src/neo4j-arc/cypher-language-support/cypher-editor/CypherEditor.tsx, src/neo4j-arc/package.json
Removes the toggleFullscreen prop on the editor and makes commands from Monaco extendable. This way the escape key can be bound to anything.
=> Make editor commands extendable

src/neo4j-arc/cypher-language-support/cypher-editor/CypherEditor.tsx, src/neo4j-arc/package.json
Exposes the tab index prop for Monaco to the Cypher editor.
=> Add tab index to cypher editor

src/neo4j-arc/graph-visualization/GraphVisualizer/Graph/Graph.tsx, src/neo4j-arc/graph-visualization/GraphVisualizer/Graph/visualization/Visualization.ts
fix for bug where zoom was incorrectly applied when changing style of the graph.
=> bugfix incorrectly zooms when changing style of graph

src/neo4j-arc/graph-visualization/GraphVisualizer/Graph/visualization/Visualization.ts
The graph change handler did not repaint updated shaft widths or captions. The simplest change is to just call another tick on the visualization since the normal render will update with the new width/caption!
=> Fix relationship stylings not getting applied 

src/browser/modules/Editor/MainEditor.tsx, src/browser/modules/Frame/FrameEditor.tsx, src/neo4j-arc/cypher-language-support/cypher-editor/CypherEditor.tsx, src/neo4j-arc/package.json
When previously adding the possibility to add custom commands for keycodes in the editor the ability to close the editor autocomplete broke. This makes sure the standard escape commands (which blurs) is not active while the autocomplete is visible.
=> Fix bug where the editors autocomplete could not be closed with the escape key

e2e_tests/integration/0.index.spec.ts, src/browser/modules/App/App.tsx, src/browser/modules/Main/Main.test.tsx, src/browser/modules/Main/Main.tsx, src/browser/modules/Main/styled.tsx, src/shared/modules/dbMeta/__snapshots__/dbMetaDuck.test.ts.snap, src/shared/modules/dbMeta/dbMetaDuck.ts, src/shared/modules/dbMeta/dbMetaEpics.ts, src/shared/modules/dbMeta/utils.ts
Adds banners for remaining days for database trial and when the trial has expired
=> Add neo4j trial banners

src/browser/modules/DBMSInfo/DatabaseKernelInfo.tsx, src/shared/modules/dbMeta/dbMetaDuck.ts, src/shared/utils/selectors.ts
We get the role from SHOW DATABASES, but it we pick the wrong item in the list since it shows one entry per cluster instance.
Tested on (with both bolt&neo4j schemes):
- 5.0 CORE
- 5.0 Read replica
- 4.4 leader
- 4.4 follower
- 4.4 read replica
- 4.4 Standalone
=> Fix leader incorrectly reporting role cluster role in sidebar 

src/shared/modules/commands/helpers/params.ts, src/shared/services/commandInterpreterHelper.ts
Given that a `RETURN` statement should not do any graph operations, defining your parameters on a composite db is not a problem. So let's not prevent users from doing so.
=> Don't prevent setting parameters on composite databases

src/browser/modules/Stream/Auth/ChangePasswordFrame.tsx, src/browser/modules/Stream/Auth/ConnectionFormController.test.tsx, src/browser/modules/Stream/Auth/ConnectionFormController.tsx, src/browser/modules/Stream/Auth/ConnectionFrame.tsx
ConnectForm & ConnectionForm were very easy to confuse with each other, renamed one of them
=> Small connection form refactorings

e2e_tests/integration/auto-prefix.spec.ts, src/shared/modules/commands/cypher.test.ts, src/shared/services/commandInterpreterHelper.ts
=> Bugfix - :auto didn't handle newlines 

package.json, yarn.lock
postcss-cssnext is deprecated in favor of postcss-preset-env. Postcss-cssnext  uses a version of isnumeric that does not have a license. To stay license compliant we need to replace postcss-cssnext with postcss-preset-env.
=> Update deprecated dep with the new version

src/shared/modules/favorites/staticScripts.ts
so removed from scripts when above 5.
=> CALL dbms.listQueries() is not supported in 5

src/browser/modules/Stream/CypherFrame/helpers.test.ts, src/browser/modules/Stream/CypherFrame/helpers.ts
The ascii table currently shows empty arrays or objects as ''. This PR changes this to [] and {} respectively. This also fixes a crash where ascii-data-table does not work with empty strings.
=> fix ascii table crash on empty array or object

src/browser/modules/Stream/CypherFrame/RelatableView/__snapshots__/relatable-view.test.tsx.snap, src/browser/modules/Stream/CypherFrame/RelatableView/relatable-view.test.tsx, src/browser/modules/Stream/CypherFrame/RelatableView/relatable-view.tsx
This fixes the following issue:
https://github.com/neo4j/neo4j-browser/issues/1761
Does so by checking for empty string and replace it with a string that contains two quotation marks.
The queries in the original issue do not cause a browser crash now.
However, the following query still fails:
```
RETURN 'test' AS ``, 'test2' AS `''`
```
Giving the error:
`Duplicate columns were found with ids: "''" in the columns array above`
Which is caused by `` being mapped to `''` so there is a collision in the column keys.
So the fix is not completely satisfactory since a user can still generate a crash by giving weird input queries.
=> Replace empty string with placeholder string in column header generation

src/browser/modules/Stream/CypherFrame/VisualizationView/PropertiesPanelContent/StyleableNodeLabel.tsx, src/browser/modules/Stream/CypherFrame/VisualizationView/PropertiesPanelContent/StyleableRelType.tsx
When semantic-ui-react was updated the default position for the popup changed to left center. We can't easily make it appear over the element anymore. I think this change might be good enough.
=> fix position of stylers

src/browser/modules/Stream/CypherFrame/ErrorsView/MissingParamsTemplateLink.tsx
=> Add missing space to params help text

docs/preview.yml, docs/publish.yml
For the docs, the value of `sitemap_version` in the playbooks needs to be updated to match the version in `antora.yml` in order to generate and publish a valid sitemap for SEO.
=> Update sitemap version in playbooks

src/neo4j-arc/graph-visualization/models/Graph.ts
When we [reset a Graph](https://github.com/neo4j/neo4j-browser/blob/master/src/neo4j-arc/graph-visualization/models/Graph.ts#L201), we see that the `expandedNodeMap` was not reset. We think we should clear all instance variables while resetting the graph. So this PR adds the reset to the `expandedNodeMap`
=> Reset expandedNodeMap when Graph is reset

src/browser/modules/Stream/SysInfoFrame/SysInfoFrame.test.tsx, src/browser/modules/Stream/SysInfoFrame/SysInfoFrame.tsx, src/browser/modules/Stream/SysInfoFrame/styled.tsx, src/shared/services/commandInterpreterHelper.ts
Sysinfo would always run against the currently active database, leading to confusion on which database the stats came from. This PR makes it clear which database the stats come from, even if sysinfo was run before the database list was loaded
=> improve sysinfo frame consistency

src/shared/services/cypherErrorsHelper.ts, yarn.lock
The error code for transaction was changed, so we we're no longer showing the hint about `:auto`
=> Transaction error new code & update caniuse to get rid of warning

src/neo4j-arc/cypher-language-support/cypher-editor/CypherEditor.tsx
Before the signature of the function could make the method name unreadable:
After we expand the completion by default:
=> Expand completion detail by default

src/browser/modules/DBMSInfo/DatabaseSelector.tsx, src/browser/modules/Sidebar/GuideDrawer.tsx, src/browser/modules/Stream/ErrorFrame.tsx, src/browser/modules/Stream/auto-exec-button.test.tsx, src/browser/modules/Stream/auto-exec-button.tsx, src/shared/services/exceptions.ts
`SHOW DATABASES` has been expanded to contain more statuses in 5.11, add more info on hover and disable button on more statuses.
=> Handle more database states

src/shared/services/bolt/boltMappings.ts
Some of the statistics from the driver are wrong for large numbers. It’s reproducible by calling `PROFILE MATCH (n:Person|Node) return count(*)` on a database where you have over 32 bit signed integer max nodes (about two billion) with these labels. You’ll see that the rows & dbHits numbers will be negative.
This is caused by a four year old dormant bug in the driver code, I've reached out to the drivers team and there was nothing preventing us from using this workaround until it is fixed in the driver.
=> Work around incorrect counts for large numbers in plan view

e2e_tests/integration/data-export.spec.ts, src/browser/modules/Stream/CypherFrame/CypherFrame.tsx
This PR aligns graph export behavior with [what's being documented](https://neo4j.com/docs/browser-manual/current/operations/export-results/), i.e. exporting in JSON and CSV
We like the feature of JSON export very much, because our research needs it a lot. Thanks a lot for developing this option, folks!
PS: I have also signed the CLA (jack20220723@gmail.com, QubitPi). Please let me know if I can help with anything else
=> Align documentation by allowing Graph export in JSON & CSV formats

package.json, src/neo4j-arc/common/types/cypherDataTypes.ts, src/neo4j-arc/package.json, src/neo4j-arc/yarn.lock, src/shared/services/bolt/boltMappings.ts, yarn.lock
=> Bump neo4j-driver to 5.9.2

src/browser/modules/Sidebar/About.tsx, src/browser/modules/Sidebar/Documents.tsx
Some of our sidebar links were outdated, moved or obsolete.
Fixes #1942
=> update outdated links

src/browser/modules/DBMSInfo/DBMSInfo.tsx, src/browser/modules/DBMSInfo/DatabaseSelector.test.tsx, src/browser/modules/DBMSInfo/DatabaseSelector.tsx, src/shared/modules/dbMeta/__snapshots__/dbMetaDuck.test.ts.snap, src/shared/modules/dbMeta/dbMetaDuck.ts, src/shared/modules/dbMeta/dbMetaEpics.ts
As of 5.11 there is a field in `SHOW ALIASES` to distinguish aliases that should not be directly queried, as they are parts of a composite database.
=> show only non-composite aliases in drop down

src/browser/modules/Stream/Auth/ConnectForm.tsx
Using a [protocol relative URL](https://en.wikipedia.org/wiki/URL#prurl), we can ensure that HTTPS is used when appropriate.  Easiest way to test this is to use `yarn starts` to get Browser running with a self signed certificate
=> ensure right protocol is used for http reachablity check

e2e_tests/integration/types.spec.ts, src/browser/modules/Stream/CypherFrame/AsciiView.tsx, src/browser/modules/Stream/CypherFrame/VisualizationView/PropertiesPanelContent/DetailsPane.test.tsx, src/browser/modules/Stream/CypherFrame/VisualizationView/PropertiesPanelContent/DetailsPane.tsx, src/neo4j-arc/common/components/PropertiesTable/PropertiesTable.test.tsx, src/neo4j-arc/common/types/arcTypes.ts, src/neo4j-arc/common/utils/driverUtils.ts, src/neo4j-arc/graph-visualization/GraphVisualizer/DefaultPanelContent/DefaultDetailsPane.test.tsx, src/neo4j-arc/graph-visualization/GraphVisualizer/DefaultPanelContent/DefaultDetailsPane.tsx, src/neo4j-arc/graph-visualization/models/Node.ts, src/neo4j-arc/graph-visualization/models/Relationship.ts, src/neo4j-arc/graph-visualization/types.ts, src/neo4j-arc/graph-visualization/utils/mapper.ts, src/shared/services/bolt/boltMappings.ts
Before (notice the element ids are just old ids but as strings):
After:
Also adds it to the node properties panel here:
=> fix bug where element-id shows incorrectly in table

src/browser/modules/Stream/CypherFrame/CypherFrame.tsx
If the user exports a result that is very long (over 100 000 rows) Browser crashes with the error  Maximum call stack size exceeded. This fix updates the code to avoid adding calls to the stack.
=> Fix maximum call stack size exceeded for csv export

src/browser/modules/DBMSInfo/DBMSInfo.tsx, src/browser/modules/DBMSInfo/DatabaseSelector.test.tsx, src/browser/modules/DBMSInfo/DatabaseSelector.tsx, src/shared/modules/dbMeta/__snapshots__/dbMetaDuck.test.ts.snap, src/shared/modules/dbMeta/dbMetaDuck.ts, src/shared/modules/dbMeta/dbMetaEpics.ts
It's problematic to run `SHOW ALIASES` as it requires privileges to run, we can figure out if a alias is a composite alias without this.
=> Avoid running `SHOW ALIASES` to show only non-composite aliases in database dropdown

src/browser/modules/Stream/CypherFrame/CypherFrame.tsx, src/browser/modules/Stream/CypherFrame/helpers.test.ts, src/browser/modules/Stream/CypherFrame/helpers.ts, src/shared/services/bolt/cypherTypesFormatting.ts, src/shared/services/utils.ts
This pull request is to remove triple quotes from the csv export of statements. 
Before, exported csv:
```
n.types,n.point,n.cuteness,n.duration2,n.birthDate,n.cool,n.time,n.name,n
"[""Ground"", ""Psychic""]","point({srid:7203, x:3, y:0})",10.3,"""P0M0DT91.123456789S""","""2023-04-28""",true,"""12:50:35.556000000+01:00""","""Baltoy""","(:Query_graph {duration: ""P0M14DT58320S"",types: [""Ground"", ""Psychic""],level: 1,cool: true,cuteness: 10.3,name: ""Baltoy"",duration2: ""P0M0DT91.123456789S"",time: ""12:50:35.556000000+01:00"",birthDate: ""2023-04-28"",point: point({srid:7203, x:3, y:0})})"
```
After with this pr changes, exported csv:
```
n.types,n.point,n.cuteness,n.duration2,n.birthDate,n.cool,n.time,n.name,n
"[Ground, Psychic]","point({srid:7203, x:3, …
```
=> removing triple quotes from csv exports

src/browser/modules/Stream/CypherFrame/VisualizationView/PropertiesPanelContent/StyleableNodeLabel.tsx, src/browser/modules/Stream/CypherFrame/VisualizationView/PropertiesPanelContent/styled.tsx
As demonstrated in the video below, the graph style picker has a white outline in dark mode. This PR fixes that by setting the theme background color with higher specificity.
=> Fix "Graph style picker has white outline in dark mode"

src/browser/modules/Stream/CypherFrame/VisualizationView/VisualizationView.tsx, src/shared/modules/cypher/cypherDuck.ts, src/shared/rootEpic.ts
A client was experiencing an issue expanding a node's neighbours and relationships due to routing being disabled on the requests that these functions were executing.
In this change, we are updating the functions in the vizualization component to use routed requests to query for a node's relationships and neighbours.
=> Fix bug where visualizations were unable to load neighbours/relationships in a cluster environment

src/browser/modules/Stream/CypherFrame/VisualizationView/VisualizationView.tsx
Using the `database` field on the result ensures that the right database is used for node expansion, even if the query dynamically switched database, for example like this:
```
:use neo4j
USE movies MATCH (n) RETURN n;
```
=> Ensure node expansion runs against the correct database

.github/workflows/pr-sso-tests.yml
https://docs.docker.com/compose/releases/migrate/#what-are-the-differences-between-compose-v1-and-compose-v2
GitHub has deprecated the v1 compose command, `docker-compose`, so the pipeline fails to bootup the requisite containers for the SSO e2e tests.
This PR updates the command from v1 to v2, `docker compose`.
=> Updates sso e2e tests workflow action to use v2 compose command

package.json, pom.xml
Next Neo4j release will have the version `2025.01.0`. In order to maintain the consistency between desktop and the browser, and since `npm version` is only supporting semver versioning, this pr aims to manually change the version to `2025.01.0`.
=> manually marking the version to support calver zero-padded versioning

.github/workflows/pr-e2e-tests.yml, .github/workflows/pr-sso-tests.yml
V3 of the upload/download artifact actions have been deprecated, and removed since January 25th https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
This PR migrates to v4.
It doesn't seem necessary to make any additional changes outlined in the migration guide https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md here, since it doesn't look like we were previously mutating uploaded artifacts from different runs.
We are also updating some packages that cypress is dependent on in the image, see https://docs.cypress.io/app/get-started/install-cypress#UbuntuDebian
ubuntu-latest resolves to 24.04 https://github.com/actions/runner-images?tab=readme-ov-file#available-images
=> Migrate upload-artifact action to v4 and update cypress dependent packages

src/browser/modules/Stream/StartPreviewFrame.tsx
This pr is to pass the db and the dbms connection information to the preview experience.
=> passing dbms and db info while passing to the preview experience

src/browser/modules/Stream/Auth/ConnectionFormController.tsx, src/shared/modules/connections/connectionsDuck.test.ts, src/shared/modules/connections/connectionsDuck.ts, src/shared/modules/connections/forceResetPasswordQueryHelper.ts, src/shared/modules/cypher/cypherDuck.ts, src/shared/modules/features/versionedFeatures.ts, src/shared/rootEpic.ts, src/shared/services/bolt/globalDrivers.ts
This PR updates the force password change flow that users go through when their password requires resetting upon login. 
Currently, the flow will use the app's detected version to determine whether to use the dbms function call if the app is on a version lower than 4.0, otherwise it will use the Cypher query.
This is problematic since the server's version will not be in state if this is a first login attempt, so it will try and query the database to get the server version.
Only the user is not authorized to query the database, because their password requires a reset.. so we cannot use the server version to accurately determine which version of the query to use.
If we still don't have a version at this point, we fallback to using a function on the driver to determine if there is multidb …
=> Updates force password change flow to use Cypher first, falling back to dbms function call

src/browser/index.tsx, src/browser/services/preview-optin-service.ts
We wish to execute a controlled rollout of the new Browser as the default experience.
This change will opt in all users on **localhost** by default, excluding those who have previously opted in and then reverted to the old Browser.
=> Add localhost preview-as-default rollout service
